Sofie-Automation/sofie-core

meteor/client/styles/settings.scss, meteor/client/ui/Settings/StudioSettings.tsx, meteor/lib/collections/StudioInstallations.ts, meteor/server/api/templates/nrk-grafikk.ts, meteor/server/api/templates/nrk-graphics.ts, meteor/server/api/templates/nrk-sorlandetBase.ts, meteor/server/api/templates/nrk-tlf.ts, meteor/server/api/templates/templates.ts, meteor/server/mockData/rundownData.ts
@nytamin could you check any naming of things (particularly the db things) and let me know if you aren't happy with any of them.
=> feat: StudioInstallation key-value config store for template settings

README.md
Just a little correction in the README.md instructions, for people trying to install it for the first time :)
=> CD to correct folder when install and run the core

meteor/server/api/snapshot.ts, meteor/server/databaseMigration.ts, meteor/server/databaseMigrationSystemSteps.ts
Adds a missing commit from R4 to master.
The current 18.1 on master is missing this commit.
=> fix: Migration for stk&full audio remapping

meteor/client/ui/RunningOrderView.tsx
Adding ctrl+shift+enter-on-numpad shortcut to reload.
=> add shortcut ctrl+shift+enter-on-numpad to reload

meteor/client/ui/RunningOrderList.tsx
Allow admins to delete synced running orders.
=> feat: allow admins to delete non-unsynced running orders

meteor/lib/api/playout.ts, meteor/server/api/peripheralDevice.ts, meteor/server/api/playout/api.ts, meteor/server/api/playout/playout.ts
* timelineTriggerTime would throw errors because it would refer to id's & core expected _id's
=> fix: issues with timelineTriggerTime

meteor/client/ui/Settings/Migration.tsx
Add vertical spacing here and there for improved readability. Make the inputs full width.
=> Improve migrations readability.

meteor/client/lib/rundown.ts, meteor/client/ui/RundownView/RundownTiming.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx, meteor/lib/collections/MediaObjects.ts, meteor/lib/mediaObjects.ts, meteor/package-lock.json, meteor/package.json
* ~fix issue with timings in GUI~ fix issue with distributing timing information in the GUI
* fix issue with disappearing part when updating some part durations
* fix issue with mediaObjects, causing missing media notifications in GUI
=> Release 13 patch

meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx, meteor/lib/collections/Pieces.ts, meteor/package-lock.json, meteor/package.json
Reverts https://github.com/nrkno/tv-automation-server-core/commit/b796cf7bc83649779eb80af23c02f4411fb5ddbd and provides a proper fix
=> fix: give Piece.transitions simpler typings specific to how it is used

.github/pull-request-template.md
This is a suggestion to add some checkboxes to the PR template.
I think it would be good to have some notion about the test-status of the code submitted, especially when getting external contributions.
The new PR:s will look like this (see **status** below).
**Status**
=> Update PR template

meteor/client/styles/_itemTypeColors.scss, meteor/client/styles/rundownView.scss, meteor/client/styles/shelf/adLibPanel.scss, meteor/client/styles/shelf/dashboard.scss, meteor/client/ui/RundownView/RundownTiming.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx, meteor/client/ui/Shelf/AdLibListItem.tsx, meteor/client/ui/Shelf/AdLibPanel.tsx, meteor/client/ui/Shelf/DashboardPanel.tsx, meteor/client/ui/Shelf/DashboardPieceButton.tsx, meteor/client/ui/Shelf/GlobalAdLibPanel.tsx, meteor/lib/api/prompter.ts, meteor/lib/collections/Parts.ts, meteor/package-lock.json, meteor/package.json, meteor/server/api/playout/actions.ts, meteor/server/api/playout/adlib.ts, meteor/server/api/playout/lib.ts, meteor/server/api/playout/playout.ts, meteor/server/api/userActions.ts
This adds "floated" feature for parts and AdLibs
It's impossible to mark when a part is floated in NRCS. As a result, if it's floated, parts and adlibs need to disappear, even if the NRCS supports sending floated parts/stories.
It allows the blueprints to mark parts & adLibs as floated, which blocks them from playback (as if the part/adLib is invalid) & remove them from timing calculations & prompter (as if they were removed).
This PR requires [this PR](https://github.com/nrkno/tv-automation-sofie-blueprints-integration/pull/54) to be pulled …
=> Feature: Floated part

meteor/__mocks__/helpers/database.ts, meteor/client/ui/Settings/ShowStyleBaseSettings.tsx, meteor/client/ui/Status/SystemStatus.tsx, meteor/lib/__tests__/mediaObjects.test.ts, meteor/package-lock.json, meteor/package.json, meteor/server/api/blueprints/__tests__/migrationContext.test.ts, meteor/server/migration/1_5_0.ts, meteor/server/migration/databaseMigration.ts
Tidies up some unused properties
Implementation of: https://github.com/nrkno/tv-automation-sofie-blueprints-integration/pull/50
**Status**
=> chore: remove unused sourcelayer properties

meteor/server/api/playout/playout.ts
_Note: This PR is happily contributed from TV2 Denmark!_ 😀 
This PR fixes a bug that caused the moveNext function to throw an error when moving past an empty segment.
moveNext function to throw an Error("No parts in segment") if the next-next segment was empty.
No Error, the Next marker moves past the empty segment
**Status**
=> fix: allow Next:ing past an empty segment.

meteor/server/__tests__/codeControl.test.ts
This PR increases some durations for timeouts in the tests for codeControl.
It's of course no ideal to have to depend on actual times in unit tests, but since we're testing code that handles concurrency so...
**Status**
=> chore: make codeControl unit tests slower, decreasing the risk of them failing

meteor/lib/lib.ts, meteor/server/api/asRunLog.ts
Corrects a minor typings error I found while doing some refactoring
**Status**
=> fix: update incorrect typings of asyncCollectionFindOne

meteor/client/lib/clientAPI.ts, meteor/client/ui/RundownView.tsx, meteor/lib/api/userActions.ts, meteor/server/api/__tests__/userActions.test.ts, meteor/server/api/userActions.ts
This adds logging of the UI state in RundownView (focused/blurred)
No logs are produced for window state, complicating troubleshooting.
New events are added in the user log called `guiState.focused` and `guiState.blurred`.
**Status**
=> feat: log focus

meteor/client/ui/RundownView/RundownNotifier.ts, meteor/client/ui/RundownView/RundownSystemStatus.tsx, meteor/lib/api/notes.ts, meteor/lib/api/rundown.ts, meteor/lib/collections/Parts.ts, meteor/lib/collections/RundownPlaylists.ts, meteor/server/api/blueprints/__tests__/context.test.ts, meteor/server/api/blueprints/context.ts, meteor/server/api/ingest/rundownInput.ts
Two parts to this:
1) Any notes generated by the blueprints for a part were not being saved against that part.
2) Any part notes were not being shown in the ui. Neither were any invalidReason notes.
**Status**
=> fix: part notes and invalidReason notes not showing

meteor/client/ui/Settings/DeviceSettings.tsx, meteor/client/ui/Settings/components/INewsSettingsComponent.tsx, meteor/lib/api/peripheralDevice.ts, meteor/lib/collections/PeripheralDeviceSettings/iNews.ts, meteor/lib/collections/PeripheralDevices.ts, meteor/server/api/ingest/__tests__/ingest.test.ts, meteor/server/api/ingest/actions.ts, meteor/server/api/ingest/api.ts, meteor/server/api/ingest/iNewsDevice/actions.ts, meteor/server/api/ingest/iNewsDevics/actions.ts, meteor/server/api/ingest/rundownInput.ts
Feature
Adds support for the iNews gateway: https://github.com/olzzon/tv2-inews-ftp-gateway.git
=> feat: iNews gateway

meteor/client/lib/PointerLockCursor.tsx, meteor/client/ui/RundownView.tsx, meteor/client/ui/SegmentTimeline/SegmentTimeline.scss, meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
Feature
Allows the user to click and drag on the segment timeline to scroll left and right through a segment.
=> feat: Timeline grab to scroll

meteor/client/ui/Shelf/AdLibPanel.tsx, meteor/client/ui/Shelf/DashboardPanel.tsx, meteor/client/ui/Shelf/GlobalAdLibPanel.tsx, meteor/package-lock.json, meteor/server/api/playout/api.ts, meteor/server/api/playout/playout.ts, meteor/server/api/userActions.ts
This PR adds the feature to be able to stop multiple sourceLayers with a single call/button press.
* **What is the current behavior?**
This is not possible, since multiple calls has to be made to Core, which caused timeline to update, which gave errors on the output.
=> Be able to stop multiple sourceLayers

meteor/client/lib/userAction.ts, meteor/client/styles/rundownView.scss, meteor/client/ui/RundownView.tsx, meteor/client/ui/SegmentTimeline/SegmentContextMenu.tsx, meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx, meteor/lib/api/userActions.ts, meteor/lib/collections/Rundowns.ts, meteor/server/api/playout/actions.ts, meteor/server/api/playout/lib.ts, meteor/server/api/playout/playout.ts, meteor/server/api/userActions.ts
Feature
Allows the user to set a **Segment** as Next (not just a Part); so when the playhead reaches the final Part of the current Segment, it'll will be taken to the Segment set as next.
This allows the user to change the order of Segments without necessarily needing to be on the final Part of a Segment, giving greater flexibility and reducing the need to rush to change the part set as next.
=> New feature: Set Next Segment

meteor/client/lib/rundown.ts, meteor/client/ui/RundownView.tsx, meteor/client/ui/RundownView/RundownTiming.tsx, meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
Feature
Allows the user to double-click on a segment (can also be bound to a hotkey) to zoom to a whole-segment view, whereby the entire segment is scaled so that it 
fits within the user's viewport.
*Zoomed out view*
=> Feature: Zoom latch

meteor/client/lib/PointerLockCursor.tsx, meteor/client/lib/localStorage.ts, meteor/client/styles/shelf/dashboard-streamdeck.scss, meteor/client/styles/shelf/shelf.scss, meteor/client/ui/App.tsx, meteor/client/ui/PieceIcons/Renderers/LiveSpeakInput.tsx, meteor/client/ui/RundownView.tsx, meteor/client/ui/RundownView/RundownNotifier.ts, meteor/client/ui/SegmentTimeline/SegmentTimeline.scss, meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx, meteor/client/ui/Settings/ConfigManifestSettings.tsx, meteor/client/ui/Settings/RundownLayoutEditor.tsx, meteor/client/ui/Settings/ShowStyleBaseSettings.tsx, meteor/client/ui/Shelf/Shelf.tsx, meteor/lib/Rundown.ts, meteor/lib/collections/RundownLayouts.ts, meteor/lib/collections/Rundowns.ts, meteor/lib/mediaObjects.ts
This PR features various GUI improvements:
* Auto-rewind when leaving segment (#a6765b24)
* Allow flattening output layers (#e8516fb7)
* Dashboard: allow hiding utility panels (#40152207)
* Allow scaling the UI with zoom parameter (#cb144154)
* Add setting for changing default timeScale (#097ced9e)
* Styling fix for streamdeck dashboard (#da7a6679)
* Fix an issue with presenter countdown icon colors in LiveSpeak (#33817550)
=> Various GUI improvements

meteor/lib/logging.ts, meteor/server/api/logger.ts
This fixes an issue where an Meteor.Error is thrown and logged as just "{}"
**Status**
=> fix: bug fix logger didn't log some Errors

meteor/server/api/ingest/rundownInput.ts, meteor/server/api/playout/lib.ts, meteor/server/api/playout/playout.ts, meteor/server/api/rundown.ts
Fixes ingest changes being visible in the UI, but not affecting playout until another operation triggers a timeline update
**Status**
=> fix: timeline not being updated after data ingest

meteor/server/__tests__/cronjobs.test.ts
This PR implements tests for `server/cronjobs.ts`
There are no tests.
There are tests covering the file: when the cronjobs run and what they do.
**Status**
=> chore: test cronjobs

meteor/__mocks__/helpers/database.ts, meteor/lib/api/playout.ts, meteor/lib/lib.ts, meteor/server/api/playout/__tests__/__snapshots__/playout.test.ts.snap, meteor/server/api/playout/__tests__/api.test.ts, meteor/server/api/playout/__tests__/playout.test.ts, meteor/server/api/playout/api.ts
This PR increases the testing coverage for some of backend playout methods.
The testing coverage in playout is low due to the expansive feature set.
The testing coverage is increased. Some features still aren't tested, such as blueprint callbacks, holds and runtime arguments.
**Status**
=> chore: more playout tests

meteor/server/api/__tests__/userActions/buckets.test.ts, meteor/server/api/__tests__/userActions/general.test.ts, meteor/server/api/buckets.ts, meteor/server/api/userActions.ts
Automated tests of the Buckets API, also refactor userActions tests so that they are more manageable.
There are no automated tests of the Buckets API.
Buckets API have 90% test coverage.
**Status**
=> chore: buckets API tests

meteor/server/api/__tests__/userActions/buckets.test.ts, meteor/server/api/__tests__/userActions/general.test.ts, meteor/server/api/__tests__/userActions/mediaManager.test.ts, meteor/server/api/buckets.ts, meteor/server/api/userActions.ts
This PR adds automated tests for the media manager portion user actions API. It's based on https://github.com/nrkno/tv-automation-server-core/pull/279
The media manager methods are not covered by automated tests.
Media Manager user actions API has 91.53% coverage.
**Status**
=> chore: tests media manager api

meteor/server/api/playout/timeline.ts
This PR fixes an issue with getTimelineRundown.
If a ShowStyle blueprint function called `onTimelineGenerate` crashes when run by `getTimelineRundown` in `timeline.ts`, it can silently prevent playback of a newly taken part. The part becomes the current part and simulated initial playback in the GUI happens (based on the `taken` timestamp), but no actual playout by the playout gateway is done, because `updateTimeline` never finishes and no new timeline is generated. I do not belive this is acceptable behavior.
The call to `onTimelineGenerate` is wrapped in a …
=> fix: prevent a crash in getTimelineRundown by onTimelineGenerate

meteor/package-lock.json, meteor/package.json, meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts, meteor/server/api/blueprints/context/adlibActions.ts
This will let adlib-actions do more things.
The aim here is to let the actions change the transition on the next-part
This needs some unit tests and some more manual testing before being ready to merge
**Status**
=> feat: more adlib-action functions

meteor/server/api/playout/lib.ts
Bug fix
Some data is not removed from db when removing a rundown, due to the cache only contains pieceInstances from the current, next and previous partinstances, so we end up leaving behind any pieceinstances from any other/earlier partinstances
Also some collections that had data owned by rundowns was not handled.
All data is removed
This is targeted to R22, but we should also merge it into R23+.
**Status**
=> bugfix in removeRundownFromCache: make sure all data that belong to Rundown is removed

meteor/client/ui/TestTools/Timeline.tsx, meteor/lib/collections/Timeline.ts, meteor/lib/rundown/pieces.ts, meteor/package-lock.json, meteor/package.json, meteor/server/api/__tests__/peripheralDevice.test.ts, meteor/server/api/blueprints/postProcess.ts, meteor/server/api/peripheralDevice.ts, meteor/server/api/playout/lib.ts, meteor/server/api/playout/lookahead.ts, meteor/server/api/playout/pieces.ts, meteor/server/api/playout/timeline.ts
This updates blueprints-integration to the correct version that will be part of the release.
**Status**
=> fix: update blueprints-integration

.circleci/config.yml, Dockerfile, Dockerfile.circle, meteor/.meteor/packages, meteor/.meteor/release, meteor/.meteor/versions
This PR updates the Meteor framework to a security release 1.11.1
[Meteor 1.11.1 Release notes](https://docs.meteor.com/changelog.html#v111120200916)
**Status**
=> chore: Update to Meteor 1.11.1

meteor/server/ActivationCache.ts
Bugfix
Updating the studiobaseline fails with an error
**Status**
=> fix: ActivationCache.getPeripheralDevices exception when no active playlist

meteor/client/styles/prompter.scss, meteor/client/ui/Prompter/OverUnderTimer.tsx, meteor/client/ui/Prompter/PrompterView.tsx, meteor/lib/api/prompter.ts
This is a new feature
There is no over/under information in the prompter
An over/under timer is shown in the prompter screen:
**Status**
=> feat: prompter over/under timer

meteor/client/ui/ClockView/ClockComponent.tsx, meteor/client/ui/ClockView/ClockView.tsx, meteor/client/ui/ClockView/Timediff.tsx, meteor/client/ui/PieceIcons/PieceIcon.tsx, meteor/client/ui/PieceIcons/PieceName.tsx, meteor/client/ui/PieceIcons/utils.ts, meteor/client/ui/StudioScreenSaver/StudioScreenSaver.tsx
This is a bug fix.
The ClockView (used to render the presenter's screen) sometimes had difficulty figuring out which Piece in a Part to use for displaying the Icon and label.
The logic for selecting the Piece to be displayed has been refactored. Also, the components used by the ClockView have been refactored into smaller files to be more manageable.
**Status**
=> fix: presenter screen sources

meteor/server/api/ingest/rundownInput.ts
This PR improves some logging to aid in troubleshooting an unsynced rundown issue.
=> Troubleshoot unsynced issue

meteor/client/ui/Settings/StudioSettings.tsx, meteor/lib/collections/Timeline.ts, meteor/server/api/playout/lookahead/index.ts
This PR fixes an issue where lookahead timeline objects wasn't routed properly.
(pending testing)
**Status**
=> Fix: route lookaheads

meteor/client/lib/clientAPI.ts, meteor/client/ui/ClockView/ClockComponent.tsx, meteor/client/ui/Prompter/PrompterView.tsx, meteor/client/ui/RundownView.tsx, meteor/client/ui/RundownView/RundownNotifier.tsx, meteor/lib/mediaObjects.ts
Some of the code in some parts of the RundownNotifier used properties which were optimized away using a `field` modifier, making them effectively dead.
The `fields` were updated. Also, there were three subscriptions to PieceInstances in RundownView that essentially did the same thing, so I combined them all into one.
**Status**
=> fix: possible missing properties

packages/blueprints-integration/package.json, packages/yarn.lock
Dependency update
It updates the TSR Types library to a newer version in the blueprints-integration package.
**Status**
=> chore: new TSR

meteor/client/styles/prompter.scss, meteor/client/ui/Prompter/controller/joycon-device.ts, meteor/package-lock.json
=> fix: prompter improvements

.circleci/config.yml, .github/actions/setup-meteor/action.yaml, .github/workflows/node.yaml, meteor/server/api/__tests__/peripheralDevice.test.ts, meteor/server/api/systemTime/systemTime.ts
Tooling update
CircleCI is used for ci, which on the free tier results in a lot of queued jobs
This is now all done on github actions.
From the first few runs, this looks to bring the average runtime (when nothing was blocked on circleci) down to 7 minutes from 11 minutes.
Some parts of the flow have not been tested very well, and should be closely monitored during the first release to ensure it goes smoothly
Some time after this has been merged, the old circleci config can be removed. When this is done, circleci will want to be disabled …
=> feat: github actions

meteor/client/styles/_colorScheme.scss, meteor/client/styles/countdown/overlay.scss, meteor/client/styles/countdown/presenter.scss, meteor/client/styles/rundownView.scss, meteor/client/ui/ClockView/ClockView.tsx, meteor/client/ui/ClockView/OverlayScreenSaver.tsx, meteor/client/ui/StudioScreenSaver/StudioScreenSaver.tsx
This is a bug-fix/styling improvement.
Presenter screen counter colors match the ones used in the Rundown View
**Status**
=> fix(Presenter screen): countdown colors match the ones used in the Rundown View

README.md
=> chore: add readme section about version numbering

meteor/client/ui/Prompter/controller/midi-pedal-device.ts
https://github.com/nrkno/tv-automation-server-core/pull/462 but rebased for R30
**Status**
=> fix(Midi): Filtering of idle information in multi-pedal setups

meteor/client/lib/polyfill/polyfills.ts, meteor/client/lib/polyfill/promise.allSettled.ts, meteor/client/main.tsx, meteor/client/ui/i18n.ts, meteor/package-lock.json, meteor/package.json
Bug fix
Displaying the Presenter screen in CasparCG results in the following:
```
[2021-02-18 15:33:23.469] [13304] [error]   html[https://[sofie]/countdowns/studio0/presenter] Log: Uncaught TypeError: Promise.allSettled is not a function
[2021-02-18 15:33:23.470] [13304] [error]   html[https://[sofie]/countdowns/studio0/presenter] Log: Uncaught TypeError: Cannot destructure property `ServiceConfiguration` of 'undefined' or 'null'.
```
A shim is included to emulate the behavior of `Promise.allSettled` in browser that don't support it (like Chromium in CasparCG …
=> fix: Presenter screen not working

meteor/client/ui/Settings/StudioSettings.tsx, meteor/i18n/nb.po, meteor/i18n/nn.po, meteor/i18n/template.pot, meteor/public/locales/nb/translations.json, meteor/public/locales/nn/translations.json
Also adds qoutation to clearly mark this as a term.
**Status**
=> chore: Removes unmotivated ™ from the "Play from Anywhere" term.

meteor/client/ui/ClockView/PresenterScreen.tsx, meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx, meteor/server/api/ingest/rundownInput.ts, meteor/tsconfig-base.json
This PR merges latest changes from R31 into R32
**Status**
=> chore: merge R31 to R32

meteor/client/lib/EditAttribute.tsx
feature
no feature :)
This PR adds EditAttributeArray to support inputting of basic arrays.
Use arrayType: 'boolean' | 'int' | 'float' | 'string' to set the types of the inner values in the array.
**Status**
=> feat: add EditAttributeArray to support inputting of basic arrays.

packages/playout-gateway/package.json, packages/playout-gateway/src/coreHandler.ts, packages/playout-gateway/src/tsrHandler.ts, packages/yarn.lock
_Original PR: https://github.com/nrkno/tv-automation-playout-gateway/pull/74, already reviewed_
This PR contains various things from the olzzon fork that for some reason hasnt made it upstream yet.
A summary of the changes:
* Now subscribes to expectedPlayoutItems, to support preloading of vizMSE graphics.
* piping of events introduced in nrkno/tv-automation-state-timeline-resolver#176
Note: TSR needs to be updated before merging this.
**Status**
=> Feat: playout gw tv2 contribs

meteor/client/lib/parsers/mos/__tests__/mosSample2.json, meteor/client/lib/parsers/mos/__tests__/mosXml2Js.test.ts, meteor/client/lib/parsers/mos/mosXml2Js.ts, meteor/package-lock.json, meteor/package.json, packages/mos-gateway/package.json, packages/mos-gateway/src/coreHandler.ts, packages/mos-gateway/src/index.ts, packages/mos-gateway/src/mosHandler.ts, packages/yarn.lock
This PR updates MOS-gateway to use the latest and greatest mos-connection version, and a few small bug fixes along the way.
**Status**
=> Use mos connection version 1.x.x

meteor/client/lib/EditAttribute.tsx, meteor/client/lib/SettingsNavigation.tsx, meteor/client/ui/Settings/components/ConfigManifestEntryComponent.tsx, meteor/lib/collections/ExpectedPackages.ts, meteor/lib/collections/PeripheralDevices.ts, meteor/server/systemStatus/systemStatus.ts
This PR adds a few assertNever in various places.
=> chore: add asserNever

meteor/lib/lib.ts, meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts, meteor/server/api/blueprints/events.ts, meteor/server/api/ingest/commit.ts, meteor/server/api/ingest/mosDevice/diff.ts, meteor/server/api/peripheralDevice.ts, meteor/server/api/playout/actions.ts, meteor/server/api/playout/lockFunction.ts, meteor/server/api/playout/lookahead/findForLayer.ts, meteor/server/api/playout/lookahead/index.ts, meteor/server/api/playout/playout.ts, meteor/server/api/studio/lockFunction.ts, meteor/server/cache/CacheCollection.ts, meteor/server/cache/CacheObject.ts, meteor/server/lib/database.ts
performance
From investigating why core got backed up with queued syncFunctions, some quick and easy performance tweaks
**Status**
=> fix: small performance tweaks

DEVELOPER.md, meteor/server/api/playout/DOCS.md
This PR adds 2 files for developers looking to contribute to the project:
- a file containing general information about development and where to find documentation
- a file with some initial documentation for the playout API
=> chore: add developer file & initial playout docs file

packages/playout-gateway/src/configManifest.ts, packages/server-core-integration/src/lib/configManifest.ts
This is a fix
Options for OBS and Singular devices are missing and these cannot be properly configured. Also, some layer mapping configurations for some devices were missing.
The missing entries in the Peripheral Device settings manifest were added and some TypeScript sugar was added as well to at least ensure that when new devices are added to TSR, we will need to add some configuration entries for them for the build to succeed, hopefully making sure that this doesn't happen in the future.
**Status**
=> fix(Playout Gateway): add missing TSR device options and layer mapping options

meteor/client/ui/Shelf/Shelf.tsx
Fix
Scrolling the content of panels in standalone view doesn't work when using the mouse wheel
It now works
**Status**
- [ X] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [ X] The functionality has been tested by the PR author
=> fix: enable scrolling of panels in standalone shelf views

meteor/client/ui/SegmentTimeline/withMediaObjectStatus.tsx, meteor/lib/collections/PackageContainerPackageStatus.ts, meteor/lib/collections/lib.ts, meteor/server/api/integration/expectedPackages.ts, meteor/server/api/snapshot.ts, meteor/server/publications/studio.ts
This PR adds more data into snapshots, related to Packages.
**Status**
=> Fix: package data in snapshots

packages/playout-gateway/package.json, packages/playout-gateway/src/tsrHandler.ts, packages/yarn.lock
This PR adds better logging of slow commands in playout-gateway.
It depends on the PR: https://github.com/nrkno/tv-automation-state-timeline-resolver/pull/189
**Status**
=> chore: improve logging of slow commands

meteor/server/api/playout/adlib.ts, meteor/server/api/userActions.ts
=> feat: remove legacy LOWER_THIRD piece directPlay

README.md, package.json, scripts/reset.js, yarn.lock
By running `yarn reset`, all of the installed modules, dependencies and build-artifacts are removed.
This is useful if you (the developer) gets a very strange install/build error.
**Status**
=> Chore: reset script

meteor/server/codeControl.ts
Bug fix
It is currently possible for multiple calls to API methods, e.g. `dataSegmentUpdate` to run at the same time. This can cause data races.
Work items pushed into the PQueue are now an async function that wraps the `Meteor.bindEnvironment` call on the work function, rather than pushing the bound function directly onto the PQueue. PQueue seems to have issues detecting whether the work inside `Meteor.bindEnvironment` has completed but is able to correctly await an async function containing the bound function.
**Status**
=> fix: PQueue not waiting for promise to resolve

meteor/lib/lib.ts, meteor/lib/rundown/infinites.ts, meteor/server/api/playout/lookahead/__tests__/lookahead.test.ts, meteor/server/api/playout/lookahead/index.ts, meteor/server/api/playout/timeline.ts
fix
* infinite piece continuations would use the wrong startedPlayback timings
**Status**
=> fix: infinite piece continuations wrong timings

package.json
Add script in package.json
```yarn test-all```
The idea is that this does a full run of "checking everything", so type-checking/building, unit-testing, linting. Useful so that one can run just one command locally and then be sure that "everything is fine".
=> chore: Test script

meteor/package-lock.json, meteor/package.json, meteor/server/api/client.ts, meteor/server/api/integration/influx.ts, meteor/server/api/playout/timeline.ts, meteor/server/publications/timeline.ts, packages/playout-gateway/package.json, packages/playout-gateway/src/config.ts, packages/playout-gateway/src/connector.ts, packages/playout-gateway/src/influxdb.ts, packages/playout-gateway/src/tsrHandler.ts, packages/yarn.lock
Adds the option to send performance tracing information from TSR into InfluxDB for use in i.e. Grafana
Adds the option to send user action timings to InfluxDB
**Status**
=> feat: Influxdb performance tracing

meteor/lib/lib.ts, meteor/server/api/blueprints/config.ts, meteor/server/api/blueprints/events.ts, meteor/server/api/ingest/bucketAdlibs.ts, meteor/server/api/ingest/generation.ts, meteor/server/api/ingest/rundownInput.ts, meteor/server/api/ingest/syncChangesToPartInstance.ts, meteor/server/api/playout/actions.ts, meteor/server/api/playout/adlib.ts, meteor/server/api/playout/playout.ts, meteor/server/api/playout/take.ts, meteor/server/api/playout/timeline.ts, meteor/server/api/rundown.ts, meteor/server/api/rundownPlaylist.ts
Roboustness improvement
If blueprints crash, they might impact various operations in Core badly.
Crashes in Blueprints are caught and handled properly.
**Status**
=> Fix: protect against blueprint throws

.vscode/extensions.json
Project doesn't come with any suggested VS Code extensions.
We provide suggested VS Code Extensions to make bootstrapping easier for new developers. This will show up to developers when opening up the Core repo.
**Status**
=> chore: add extensions.json file

.vscode/settings.json.default, README.md
Project doesn't come with any default VS Code settings.
We provide a sample VS Code Settings JSON to make bootstrapping easier for new developers.
**Status**
=> chore: add default VS Code settings

meteor/server/api/blueprints/context/context.ts, meteor/server/api/blueprints/context/syncIngestUpdateToPartInstance.ts
This PR removes a few duplicated lines of code, to reduce code smells reported by SonarCloud.
=> Chore: R38 DRYing

meteor/server/api/ingest/__tests__/ingest.test.ts, meteor/server/api/ingest/commit.ts
=> fix: presenter screen added time after unrelated mos update

meteor/client/lib/rundown.ts, meteor/client/ui/ClockView/OverlayScreen.tsx, meteor/client/ui/ClockView/PresenterScreen.tsx, meteor/client/ui/PieceIcons/PieceCountdown.tsx, meteor/client/ui/PieceIcons/PieceIcon.tsx, meteor/client/ui/PieceIcons/PieceName.tsx, meteor/client/ui/RundownView.tsx, meteor/client/ui/RundownView/RundownTiming/PlaylistEndTiming.tsx, meteor/client/ui/SegmentTimeline/withMediaObjectStatus.tsx, meteor/lib/rundown/rundownTiming.ts, meteor/package-lock.json, packages/blueprints-integration/src/rundown.ts
=> fix: use a unified diff calculation

meteor/server/api/snapshot.ts
Bug fix
When loading a RundownPlaylist snapshot, the expected packages aren't loaded.
ExpectedPackages are now loaded into the collection.
I've also done some refactoring in the restore snapshot function, to strengthen the types a bit.
**Status**
=> Fix: expetedPackages from snapshot

meteor/server/api/playout/__tests__/playout.test.ts, meteor/server/api/playout/cache.ts, meteor/server/api/playout/lib.ts
Bug fix
- Not all rehearsal pieceInstances are removed when resetting the rundown.
- Not all pieceInstances are reset when resetting the rundown.
- Not all pieceInstances from previous instances of the nexted part are reset when setting as next.
- No previous partInstances or pieceInstances are reset when rundown is activated/reset after being deactivated.
When using a rundown playlist that is never deleted, but the content is replaced on a daily basis, it leads to nonreset pieceInstances and partInstances piling up in the database, being hard to dispose of by cron jobs or filter out when storing snapshots.
* **What is the new …
=> fix: reset instances from previous activation or not present in cache

meteor/client/styles/_itemTypeColors.scss, meteor/package-lock.json
New background colors for local (EVS) and live speak (STK) timeline item pieces.
**Status**
=> fix: update timeline item colors for local and live speak pieces

packages/playout-gateway/package.json, packages/playout-gateway/src/configManifest.ts, packages/playout-gateway/src/coreHandler.ts, packages/playout-gateway/src/tsrHandler.ts, packages/yarn.lock
This PR adds support for the TSR option estimateResolveTimeMultiplier 
This PR is dependent of https://github.com/nrkno/sofie-timeline-state-resolver/pull/204
=> fix: TSR: support estimateResolveTimeMultiplier option

meteor/client/ui/RundownView.tsx
Bug fix
When restarting a CasparCG Server from the Rundown View, the user is asked for confirmation before doing the operation. No such prompt is shown when restarting the Playout Gateway, creating an uneaven UX.
A prompt is shown before restarting the Playout Gateway.
**Status**
=> fix: ask confirmation before restarting playout gateway

scripts/run.js
Currently, starting up Core for development takes up to 2 minutes on my machine, 25% of that time spent setting up watchers on packages I'm unlikely to change (playout-gateway, mos-gateway, server-core-integration, blueprints-integration). I understand the usefulness of having everything rebuild all the time and staying in sync, however in my particular case that usefulness is limited, while the bloat is hindering my workflow.
Adds support of a `--ui-only` flag to the default `yarn dev` script, in which all the packages are built once (in case …
=> chore: light run script

meteor/lib/collections/WorkerThreads.ts, meteor/lib/collections/Workers.ts, meteor/server/systemStatus/systemStatus.ts, meteor/server/worker/worker.ts, meteor/server/worker/workerStatus.ts, packages/corelib/src/dataModel/Collections.ts, packages/corelib/src/dataModel/Ids.ts, packages/corelib/src/dataModel/WorkerThreads.ts, packages/job-worker/src/index.ts_, packages/job-worker/src/ipc.ts, packages/job-worker/src/main.ts, packages/job-worker/src/manager.ts, packages/job-worker/src/workers/events/parent.ts, packages/job-worker/src/workers/ingest/parent.ts, packages/job-worker/src/workers/parent-base.ts, packages/job-worker/src/workers/studio/parent.ts, packages/job-worker/src/workers/worker-set.ts
This PR adds a Workers-collection, and monitors the current status of the Worker process.
TODO:
**Status**
=> Feat: worker status

meteor/client/styles/countdown/presenter.scss, meteor/client/ui/PieceIcons/PieceCountdown.tsx, meteor/client/ui/PieceIcons/PieceIcon.tsx, meteor/client/ui/PieceIcons/PieceName.tsx, meteor/client/ui/PieceIcons/Renderers/LocalInput.tsx, meteor/client/ui/PieceIcons/Renderers/RemoteInput.tsx
=> fix(Presenter screen): show channel color on Local sources

meteor/__mocks__/helpers/database.ts, meteor/server/migration/__tests__/migrations.test.ts, packages/blueprints-integration/src/action.ts, packages/blueprints-integration/src/api.ts, packages/blueprints-integration/src/rundown.ts, packages/job-worker/src/__mocks__/context.ts, packages/job-worker/src/blueprints/__tests__/postProcess.test.ts, packages/job-worker/src/blueprints/postProcess.ts
…ypes
fix/feature
generated ids of pieces and other types are not very stable on ingest updates
make the ids more stable, and log if duplicate ids are found, but still allow the pieces
**Status**
=> feat: better handling of non-unqiue externalId for pieces and other types

meteor/client/ui/Shelf/BucketPanel.tsx, meteor/client/ui/Shelf/ExternalFramePanel.tsx, meteor/client/ui/Shelf/RundownViewBuckets.tsx, meteor/lib/api/userActions.ts, meteor/lib/collections/AdLibActions.ts, meteor/lib/collections/BucketAdlibActions.ts, meteor/lib/collections/BucketAdlibs.ts, meteor/server/api/__tests__/userActions/buckets.test.ts, meteor/server/api/blueprints/postProcess.ts, meteor/server/api/buckets.ts, meteor/server/api/ingest/bucketAdlibs.ts, meteor/server/api/ingest/expectedMediaItems.ts, meteor/server/api/userActions.ts, packages/blueprints-integration/src/action.ts, packages/blueprints-integration/src/rundown.ts
This PR is a backport of https://github.com/nrkno/sofie-core/pull/689
It is intended to be merged into Release 38 as a late addition/patch, because the users really crave it.
After it has been merged, @nytamin will handle merges into later release branches, to ultimately replace the contents of this PR with https://github.com/nrkno/sofie-core/pull/689.
=> Fix: bucket items showstyle variants (backport to release38)

packages/playout-gateway/src/coreHandler.ts, packages/playout-gateway/src/index.ts, packages/playout-gateway/src/tsrHandler.ts
fix
enabling 'debug' logging in playout gateway doesnt produce any logging from any device
debug logging is now logged
**Status**
=> fix: missing/broken device debug logging in playout-gateway

meteor/client/lib/localStorage.ts, meteor/client/lib/notifications/notifications.ts, meteor/client/ui/App.tsx, meteor/lib/api/client.ts, meteor/server/api/client.ts
Logs user notifications that are shown immediately in the server logs
**Status**
=> Feat: report user notifications to core

meteor/client/ui/Prompter/controller/joycon-device.ts
New feature/enhanced capatibility
Only a singe L or R or LR(pair) joycon(s) can be connected.
Known problems when going from LR mode to either L or R, where input might get stuck until windows restart.
Multiple LL or RR controllers supported. Less/no problems when going LR to L or R. 
**Status**
=> feat(Prompter): Support for multiple Joycon controller for prompter

meteor/client/styles/_variables.scss, meteor/client/styles/rundownView.scss, meteor/client/styles/shelf/shelf.scss, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnail.scss, meteor/public/images/collapse-triangle.svg, meteor/public/origo-ui/dist/origo.css
Initial attempt at improving segment visibility and stack in order to save horizontal and vertical spacing. The "collapse layer" icon was simplified to avoid it looking like a "Play" icon.
**Status**
=> feat: Improve visibility and clarity of Rundown View

packages/playout-gateway/src/tsrHandler.ts
Feature
If Playout Gateway is unable to configure a device, it will not report it as an issue.
If one of the sub-devices fails to start completely, due to an error during initialization or broken configuration, it will be reported as an issue on the Playout Gateway itself.
**Status**
=> feat(Playout Gateway): Report invalid configuration as state

meteor/.meteor/packages, meteor/client/lib/triggers/ActionAdLibHotkeyPreview.tsx, meteor/lib/api/methods.ts, meteor/package.json, meteor/server/main.ts, meteor/yarn.lock, packages/corelib/src/worker/ingest.ts
=> fix: transpile mos-connection for compatibility with CasparCG

meteor/package.json, meteor/yarn.lock, packages/blueprints-integration/package.json, packages/job-worker/package.json, packages/job-worker/src/blueprints/__tests__/postProcess.test.ts, packages/job-worker/src/blueprints/postProcess.ts, packages/job-worker/src/playout/timeline/generate.ts, packages/playout-gateway/package.json, packages/yarn.lock
Avoiding future issues
* **What is the current behavior?**
There was an issue last week where the Timeline crashed due to having kind-of-invalid data in it.
The Timeline is now getting validated so that such issues are caught early.
**Status**
=> Fix: validate timeline

meteor/client/styles/_itemTypeColors.scss, meteor/client/styles/pieceStatusIcon.scss, meteor/client/styles/rundownView.scss, meteor/client/styles/shelf/adLibPanel.scss, meteor/client/styles/shelf/dashboard.scss
GUI change
Pieces with source-missing display zebra-stripes and a warning icon.
When the Part of the Piece is Nexted or Live, the zebra-stripes and the warning icon is animated.
**Status**
=> Feat: Hightlight zebras on next and live

meteor/client/styles/rundownView.scss
Prototype larger thumbnail previews, changing relevant CSS in the Sofie GUI
Thumbnails are 160x90
Thumbnail are 320x180
**Status**
=> prototype: Larger thumbnail for Media Previews

.github/workflows/node.yaml
Publish docker images to both Docker Hub and Github Container Registry
Images are only pushed to Docker Hub (and only if it's a release branch, master branch or tagged). 
Images are pushed to Docker Hub (on master, release branch or tag). All images are pushed to Github Container Registry
**Status**
=> feat: push images to ghcr

.github/workflows/node.yaml
Removes a slash from the image names 
**Status**
=> chore: package name without slash

meteor/lib/mediaObjects.ts, meteor/public/locales/nb/translations.json, meteor/public/locales/nn/translations.json
=> fix: Removed clip filename and path from notification and hover pop-up

packages/playout-gateway/Dockerfile, packages/playout-gateway/Dockerfile.circle, packages/playout-gateway/package.json, packages/playout-gateway/src/tsrHandler.ts, packages/shared-lib/README.md
docs update
clarify the purpose and intended use of shared-lib
also some minor tidying of removing the unnecessary dependency on bluerpints-integration from playout-gateway
**Status**
=> chore: update shared-lib readme to clarify purpose

meteor/client/lib/localStorage.ts, meteor/client/ui/App.tsx, meteor/client/ui/SegmentContainer/SwitchViewModeButton.tsx
Remove a feature flag
List View Segment display mode is hidden behind a flag
The List View Segment displayMode is always available.
**Status**
=> chore: remove prototype flag for List View

meteor/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx, meteor/server/api/peripheralDevice.ts
Updates the UI for controlling the Spreadsheet-Gateway and its credentials.
Currently, it works, but the CSS needs some updating, to improve UX.
With this change, there are now two options: to reset app credentials or to reset user credentials, depending on what the user wants to perform. The overall style is also updated so it's all aligned well.
**Status**
=> fix: OAuth controls

packages/documentation/docs/user-guide/configuration/_category_.json, packages/documentation/docs/user-guide/features/sofie-views.mdx, packages/documentation/docs/user-guide/installation/_category_.json, packages/documentation/docs/user-guide/installation/installing-package-manager.md, packages/documentation/docs/user-guide/supported-devices.md
Docs update
Add more information about running Package Manager in a production environment. Remove some mentions of Media Manager.
**Status**
=> chore: update package manager documentation

packages/documentation/docs/user-guide/installation/media-manager.md, packages/documentation/docs/user-guide/installation/rundown-editor.md
Docs update
Set up a big warning not to use Media Manager
**Status**
=> chore(docs): add a warning that Media Manager is deprecated

.github/workflows/prune-docker-images.yaml
Untill the issue with attestation info in the images has been handled
**Status**
=> chore: disable scheduled cleanup of docker images

.github/workflows/node.yaml, .github/workflows/prune-container-images.yml
Change the name of a workflow, disable provenance during image build.
**Status**
=> ci: update workflow name, disable provenance

packages/blueprints-integration/src/context.ts, packages/corelib/src/dataModel/PeripheralDevice.ts, packages/job-worker/src/blueprints/context/adlibActions.ts, packages/job-worker/src/events/handle.ts, packages/job-worker/src/peripheralDevice.ts, packages/job-worker/src/playout/__tests__/actions.test.ts, packages/job-worker/src/playout/__tests__/playout.test.ts, packages/job-worker/src/playout/actions.ts, packages/shared-lib/src/core/model/peripheralDevice.ts
peripheralDeviceActions API exposed to blueprints
Blueprints can't use actions
Blueprints can use actions
**Status**
=> feat: Expose peripheralDeviceActions to blueprints

.github/workflows/prune-tags.yml
CI
No workflow
New workflow that should automatically prune old tags.
**Status**
=> ci: Prune tags workflow

meteor/client/ui/Settings/DevicePackageManagerSettings.tsx, meteor/lib/api/client.ts, meteor/server/api/client.ts, meteor/server/security/collections.ts
Bug fix
Rewrites the special Package Manager interface as a functional component and removes the requirement for write access to the PeripheralDeviceCommands collection.
**Status**
=> fix: Package Manager expanded status without needing client write-access to PeripheralDeviceCommands

meteor/lib/mediaObjects.ts
GUI change.
This PR changes the wording of warning messages related to "missing media" (zebra stripes)
~This is a draft PR while we're testing these changes with users.~
**Status**
=> fix: improve package warning messages (Sofie-2113)

.github/workflows/node.yaml
Set a custom cache folder for the different steps that use yarn and run in parallel 
**Status**
=> ci: set yarn cache folders

meteor/lib/mediaObjects.ts
This PR is a backport of PR https://github.com/nrkno/sofie-core/pull/851 to release48
=> fix: improve package warning messages

meteor/client/ui/SegmentTimeline/SegmentContextMenu.tsx
"Set next here" has become broken and this is to disable it so that it doesn't cause confusion
**Status**
=> chore: Hide "Set next here" (SOFIE-2184)

meteor/client/styles/rundownView.scss, meteor/client/ui/FloatingInspectors/VTFloatingInspector.tsx
Better usability through styling the change date differently.
Similar font styling as the rest of the script text.
Tweaked the prominence of the "last updated" string at the bottom of the Script hover pop-up.
**Status**
=> fix: gui tweak script dates

packages/shared-lib/src/lib/JobQueueWithClasses.ts, packages/shared-lib/src/lib/__tests__/JobQueueWithClasses.spec.ts
Fixes to JobQueueWithClasses
A few bugs in JobQueueWithClasses (see commits)
Fixed bugs, added unit test
**Status**
=> fix: JobQueueWithClasses

meteor/client/ui/Shelf/BucketPieceButton.tsx, meteor/client/ui/Shelf/DashboardPieceButton.tsx
Bug fix
Shelf buttons have lost styling due to #848 
Shelf button styling restored
**Status**
=> fix: Restore styling on shelf - SOFIE-2294

meteor/client/lib/lib.tsx, meteor/client/ui/Account/NotLoggedIn/LoginPage.tsx, meteor/client/ui/Account/OrganizationPage.tsx, meteor/client/ui/ActiveRundownView.tsx, meteor/client/ui/App.tsx, meteor/client/ui/ClockView/ClockView.tsx, meteor/client/ui/Header.tsx, meteor/client/ui/Prompter/PrompterView.tsx, meteor/client/ui/RundownList/ActiveProgressBar.tsx, meteor/client/ui/RundownView.tsx, meteor/client/ui/SegmentList/LinePartMainPiece/LinePartMainPiece.tsx, meteor/client/ui/SegmentList/LinePartSecondaryPiece/LinePartSecondaryPiece.tsx, meteor/client/ui/SegmentList/LinePartTimeline.tsx, meteor/client/ui/SegmentList/PieceHoverInspector.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPart.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/Renderers/ThumbnailRendererFactory.ts, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/Renderers/VTThumbnailRenderer.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnail.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnailInner.tsx, meteor/client/ui/Settings.tsx, meteor/client/ui/Settings/BlueprintSettings.tsx, meteor/client/ui/Settings/SettingsMenu.tsx, meteor/client/ui/StudioScreenSaver/Clock.tsx, meteor/client/ui/StudioScreenSaver/Countdown.tsx, meteor/client/ui/TestTools/Timeline.tsx
Refactoring
Sofie has a lot of very simple, legacy components implemented as Class components, even though they can easily be converted to a Functional component.
Implement App and a couple of top-level View components as Functions.
**Status**
=> reafactor(GUI): App as functional component

packages/mos-gateway/src/$schemas/devices.json, packages/mos-gateway/src/$schemas/options.json, packages/mos-gateway/src/generated/devices.ts, packages/mos-gateway/src/generated/options.ts, packages/mos-gateway/src/mosHandler.ts
Feature
MOS Gateway is restricted to standard ports mos-connection now supporting any port
Port settings are exposed in the UI.
**Status**
=> feat: Expose MOS Gateway ports in settings

meteor/client/lib/forms/SchemaFormSectionHeader.tsx, meteor/client/lib/forms/SchemaFormTable/ArrayTable.tsx, meteor/client/lib/forms/SchemaFormTable/ObjectTable.tsx, meteor/client/lib/forms/SchemaFormWithOverrides.tsx, meteor/server/publications/peripheralDeviceForDevice.ts
Feature
There is no unified Header component for the various "container" elements in JSON Schema Forms.
Create a single header component, add these headers whenever a "container" (object or array) specifies a `ui:title`.
**Status**
=> feat: JSON Config Schema header component

meteor/server/migration/X_X_X.ts
Bug fix
If a Peripheral Device exists, and it doesn't have a `configManifest.deviceConfigSchema` or `configManifest.subdeviceManifest`, it can cause the Settings page to crash, because the object doesn't match it's typings.
A migration is added to ensure that the PeripheralDevices that don't match the new typings have their properties modified, so that they match the typings. Once a new version of the PeripheralDevice connects, it can then provide the correct values for those properties.
**Status**
=> fix: JSON Schema Config migration

meteor/client/lib/ReactMeteorData/ReactMeteorData.tsx, meteor/client/ui/Settings/ShowStyle/VariantSettings.tsx, meteor/client/ui/Settings/components/triggeredActions/actionEditors/filterPreviews/AdLibFilter.tsx, meteor/client/ui/Settings/components/triggeredActions/triggerEditors/DeviceEditor.tsx, meteor/client/ui/Shelf/AdLibPanel.tsx, meteor/client/ui/Status/package-status/JobStatusIcon.tsx, meteor/client/ui/Status/package-status/PackageContainerStatus.tsx, meteor/client/ui/Status/package-status/PackageStatus.tsx, meteor/client/ui/Status/package-status/PackageWorkStatus.tsx, meteor/client/ui/Status/package-status/index.tsx, meteor/client/ui/Status/package-status/package-status.scss, meteor/client/ui/TestTools/DeviceTriggers.tsx, packages/playout-gateway/src/tsrHandler.ts
Refactor + change in display of package work statuses.
When PM is offline, Package-statuses are unaffected.
When PM is offline, Package Containers and Work Statuses display differently.
Screenshot:
**Status**
=> Package statuses when Package Manager is offline (SOFIE-1513)

meteor/client/styles/testtools.scss, meteor/client/ui/TestTools/Timeline.tsx, meteor/client/ui/TestTools/TimelineDatastore.tsx
Feature
The various Test Tools tables can be difficult to read at-a-glance.
The styling of these pages has been improved.
I was only able to test this with the Timeline tool. Someone should test with the 3 other tools before merging.
Before:
After:
**Status**
=> feat: improve the styling of Test Tools

meteor/server/migration/X_X_X.ts
bug fix
fixes a bug introduced in #955 where migrations would fail when encountering some overrides
**Status**
=> fix: migrations for devicetype failing on some overrides #955

meteor/client/ui/Status/SystemStatus.tsx
Docs/chore
There is a mysterious eye next to every device on the status page.
The eye has been demystified by adding a hover tooltip to it.
👁
**Status**
=> chore: add a hover tooltip to the mysterious eye button

meteor/server/api/rest/v1/index.ts, packages/corelib/src/error.ts, packages/live-status-gateway/api/schemas/activePlaylist.yaml, packages/live-status-gateway/src/coreHandler.ts, packages/openapi/api/definitions/showstyles.yaml, packages/openapi/api/definitions/studios.yaml, packages/openapi/src/__tests__/devices.spec.ts, packages/openapi/src/__tests__/playlists.spec.ts, packages/openapi/src/__tests__/sofie.spec.ts, packages/openapi/src/__tests__/studios.spec.ts
This PR has been opened by SuperFly.tv on behalf of EVS Broadcast Equipment.
API fixes.
Returned errors are vague, and there's a mismatch between the OpenAPI specification and the implementation.
Implementation and specification have been fixed to the best of out knowledge, and the API now returns more useful errors.
**Status**
=> fix: Improve API responses

packages/blueprints-integration/src/studio.ts, packages/documentation/docs/for-developers/for-blueprint-developers/lookahead.md
docs
A page for blueprint developers about Lookahead.
**Status**
=> chore: write documentation page on lookahead

.github/workflows/node.yaml, .github/workflows/trivy.yml
Add Trivy image scanning to the pipeline. This is just informational at this point, it will not break the pipeline. 
Example output: https://github.com/nrkno/sofie-core/actions/runs/5334276977
**Status**
=> ci: add trivy scanning

.github/workflows/node.yaml
Fixes the issue when several image tags are being generated and being passed to the Trivy scan step.
**Status**
=> ci: fix issue with several tags being generated in the same workflow

.github/workflows/audit.yaml, .github/workflows/node.yaml, .github/workflows/prerelease-libs.yml, .github/workflows/sonar.yaml
Set persist-credentials to false in those workflows where it's not strictly necessary to persist credentials. 
**Status**
=> ci: disable persistent credentials for checkout action

packages/documentation/package.json, packages/documentation/src/components/GitHubReleases.jsx, packages/yarn.lock
Workflow tool update
We use an old version of Docusaurus (2.0.0-beta20)
Updates to the latest stable version of Docusaurus (2.4.1).
**Status**
=> chore: Update Docusaurus

packages/blueprints-integration/src/api/showStyle.ts
Docs update
Expands the documentation on a couple of Blueprint callback endpoints, so that their behavior is less obscure.
**Status**
=> chore: expand `blueprints-integration` code documentation

packages/documentation/docs/for-developers/device-integrations/_category_.json, packages/documentation/docs/for-developers/device-integrations/intro.md, packages/documentation/docs/for-developers/device-integrations/options-and-mappings.md, packages/documentation/docs/for-developers/device-integrations/tsr-actions.md, packages/documentation/docs/for-developers/device-integrations/tsr-api.md, packages/documentation/docs/for-developers/device-integrations/tsr-types.md
=> chore: add docs for device integrations

meteor/client/ui/TestTools/Timeline.tsx, meteor/lib/__tests__/timeline.test.ts, meteor/package.json, meteor/yarn.lock, packages/job-worker/package.json, packages/job-worker/src/blueprints/__tests__/postProcess.test.ts, packages/job-worker/src/playout/timeline/generate.ts, packages/playout-gateway/package.json, packages/shared-lib/package.json, packages/shared-lib/src/core/model/Timeline.ts, packages/yarn.lock, scripts/reset.mjs
Updates TSR and timeline dependencies to use timeline v9
pending https://github.com/nrkno/sofie-timeline-state-resolver/pull/270
**Status**
=> Fix: Update timeline to v9 (SOFIE-2514)

meteor/client/lib/Spinner.tsx, meteor/client/styles/afterBroadcastForm.scss, meteor/client/ui/AfterBroadcastForm.tsx
Bug fix
The Evaluation Form  text area is cleared when it's blured (defocused)
The entered text will be persisted. The send button is disabled while the snapshot is being created.
**Status**
=> fix: evaluation form is cleared on blur (SOFIE-2571)

meteor/client/lib/rundown.ts, meteor/lib/Rundown.ts
cleanup
These properties are never set (as far as I can tell), making this dead code
**Status**
=> chore: remove unused ui properties

meteor/client/ui/ClockView/CameraScreen/useWakeLock.ts, meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx, meteor/server/api/rest/koa.ts
=> chore: fix some of the problems reported by Sonarlint

packages/job-worker/src/playout/take.ts
Add debug logging
Occasionally we see the `No partinstance was found during take` error being logged in production.
We cannot explain how Sofie got into this situation, so this adds some additional logging so that when it next happens we might get an idea of the state of the system.
**Status**
=> fix: Add debug logging for `No partinstance was found during take` SOFIE-2594

packages/job-worker/src/events/integration/rabbitMQ.ts
code and log tidying
The AMQP code will no longer log at the error level, only at warning. The log lines will be more uniform and descriptive.
I found and fixed some race conditions where concurrent calls to `prepare` could result in leaking connection objects
**Status**
=> fix: AMQP connection issues logging SOFIE-2597

meteor/client/ui/ClockView/OverlayScreenSaver.tsx, meteor/client/ui/StudioScreenSaver/StudioScreenSaver.tsx
=> chore: refactor StudioScreenSaver to avoid MeteorReactComponent SOFIE-2751

meteor/client/ui/Settings/SettingsMenu.tsx
=> chore: refactor SettingsMenu to avoid MeteorReactComponent SOFIE-2751

meteor/client/ui/Status.tsx, meteor/client/ui/Status/Evaluations.tsx
=> chore: refactor Status/Evaluations to avoid MeteorReactComponent SOFIE-2751

meteor/client/ui/ClockView/CameraScreen/Segment.tsx, meteor/client/ui/RundownView.tsx, meteor/client/ui/SegmentContainer/withResolvedSegment.ts, meteor/client/ui/SegmentList/SegmentListContainer.tsx, meteor/client/ui/SegmentScratchpad/SegmentScratchpadContainer.tsx, meteor/client/ui/SegmentStoryboard/SegmentStoryboardContainer.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx, meteor/client/ui/SegmentTimeline/withMediaObjectStatus.tsx
The `MeteorReactComponent` class has been found to be not close subscriptions when rerunning computations.  
=> chore: refactor `withMediaObjectStatus` to be functional SOFIE-2751

meteor/client/ui/Shelf/AdLibPanel.tsx, meteor/client/ui/Shelf/DashboardPanel.tsx, meteor/client/ui/Shelf/TimelineDashboardPanel.tsx
=> chore: refactor DashboardPanelInner to avoid MeteorReactComponent SOFIE-2751

meteor/client/ui/Account/AccountPage.tsx, meteor/client/ui/Account/OrganizationPage.tsx, meteor/lib/collections/Users.ts
=> chore: refactor Organization to avoid MeteorReactComponent SOFIE-2751

meteor/client/ui/Shelf/BucketPanel.tsx
=> chore: refactor BucketPanel to avoid MeteorReactComponent SOFIE-2751

meteor/client/lib/lib.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
=> chore: refactor SegmentTimelineContainer to avoid `MeteorReactComponent` SOFIE-2751

meteor/client/lib/ReactMeteorData/ReactMeteorData.tsx, meteor/client/ui/ClockView/OverlayScreen.tsx, meteor/client/ui/ClockView/PresenterScreen.tsx
=> chore: refactor PresenterScreen and OverlayScreen to avoid MeteorReactComponent SOFIE-2751

meteor/client/styles/afterBroadcastForm.scss, meteor/client/ui/AfterBroadcastForm.tsx, meteor/client/ui/Settings/SystemManagement.tsx, meteor/lib/collections/CoreSystem.ts, meteor/server/collections/index.ts, meteor/server/publications/system.ts, meteor/server/security/lib/lib.ts
This is a  Feature
The Evaluation form has a new message bubble that can show a message set in the system settings.  
This is intended to be used to prompt the user to include something specific in their feedback.  
If no message is defined in the settings, or it is not enabled, then nothing new will be shown.
As part of this, some tweaking of styling of other parts of the form was performed.
New look:
Old look:
Settings:
=> feat: Dynamic message in Evaluation form SOFIE-2766

meteor/client/lib/ReactMeteorData/ReactMeteorData.tsx, meteor/client/ui/Prompter/PrompterView.tsx, meteor/client/ui/Prompter/controller/joycon-device.ts, meteor/client/ui/Prompter/controller/keyboard-device.ts, meteor/client/ui/Prompter/controller/manager.ts, meteor/client/ui/Prompter/controller/midi-pedal-device.ts, meteor/client/ui/Prompter/controller/mouse-ish-device.ts, meteor/client/ui/Prompter/controller/shuttle-keyboard-device.ts
=> chore: refactor PrompterView to avoid MeteorReactComponent SOFIE-2751

meteor/client/ui/RundownView.tsx
This is a: 
Bug fix
If you move any story in NRCS that is behind the current playing Part to an earlier time than you are in the active playing rundown the GUI will jump to the moved segment and you will loose anchor to "on-air".
If the "Follow OnAir" mode is enabled, the scroll position should be kept
*    Have a rundown with two Segments, each with two Parts (A1, A2, A3, B1, B2, B3)
*    Start playing B1
*    Switch places A2 and A3
*  The viewport should stay focused on B1
*  “On Air” lock should be ON
=> fix: restore scroll position after segments order changes

packages/documentation/docs/user-guide/concepts-and-architecture.md
This is a: Documentation improvement 
The documentation lacks a description of what Buckets are
Added a paragraph about Buckets, also fixed some punctuation errors, etc.
No testing required, I think.
=> chore: docs dictionary update

packages/documentation/docs/user-guide/features/api.md
This is a: 
The documentation for v1.50.0 is inaccurate, in that the API section does not mention the new 1.0 REST API, nor Live Status Gateway
Sections on REST API 1.0 and Live Status Gateway have been added.
This is a docs update, no test needed.
=> chore: add information about REST API 1.0 and Live Status Gateway

packages/blueprints-integration/package.json
This is a: 
Code improvement
Node version 20 is not allowed in external applications that depend on the blueprints-integration library
Node version 20 is allowed in external applications that depend on the blueprints-integration library
none
=> chore: relax node engine version requirement for published libraries

meteor/client/lib/logStatus.ts, meteor/client/main.tsx, meteor/lib/logging.ts, meteor/server/Connections.ts
This is a: 
Bug fix / Code improvement 
When a client connects or disconnects, the only logs we have are:
```
[debug] Connection count: 2
```
More detailed logs:
```
[debug] Client connected: "ZRAdErn2pzytAikzw", "127.0.0.1"
[info] Client info, 2024-01-26T12:38:41.723Z ClientLog "null"/"beZyPQ2J": Starting up
[info] Client info, 2024-01-26T12:38:41.736Z ClientLog "null"/"beZyPQ2J": Disconnected
[info] Client info, 2024-01-26T12:38:41.736Z ClientLog "null"/"beZyPQ2J": Status "connecting"
[info] Client info, 2024-01-26T12:38:42.037Z ClientLog "2kYDpJJN3dDH36Jii"/"beZyPQ2J": Connected
[info] Client info, 2024-01-26T12:38:42.037Z ClientLog "2kYDpJJN3dDH36Jii"/"beZyPQ2J": Status "connected"
[debug] Connection count: 2
// When disconnected: …
```
=> fix: log connected client info, server side

.github/ISSUE_TEMPLATE/bug_report.yml, .github/PULL-REQUEST-TEMPLATE.md
This is a: 
Github issue templates improvement
This PR adds a couple of form fields to the github templates, as discussed on the NRK team dev meet discussed last week.
=> chore: add a note on time frame to PR template

meteor/client/lib/ModalDialog.tsx, meteor/client/lib/notifications/NotificationCenterPanel.tsx, meteor/client/lib/triggers/TriggersHandler.tsx, meteor/client/lib/ui/icons/looping.tsx, meteor/client/styles/afterBroadcastForm.scss, meteor/client/styles/rundownView.scss, meteor/client/styles/shelf/adLibPanel.scss, meteor/client/styles/shelf/dashboard.scss, meteor/client/styles/shelf/shelf.scss, meteor/client/ui/AfterBroadcastForm.tsx, meteor/client/ui/Header.tsx, meteor/client/ui/RundownList.tsx, meteor/client/ui/RundownList/RundownListItemView.tsx, meteor/client/ui/RundownList/RundownPlaylistUi.tsx, meteor/client/ui/RundownView/MediaStatusPopUp/MediaStatusPopUpHeader.scss, meteor/client/ui/RundownView/MediaStatusPopUp/MediaStatusPopUpHeader.tsx, meteor/client/ui/RundownView/RundownRightHandControls.tsx, meteor/client/ui/RundownView/RundownTiming/RundownName.tsx, meteor/client/ui/SegmentContainer/SwitchViewModeButton.tsx, meteor/client/ui/SegmentTimeline/SegmentTimelineZoomButtons.tsx, meteor/client/ui/Shelf/AdLibPanelToolbar.tsx, meteor/client/ui/Shelf/Shelf.tsx, meteor/client/ui/Shelf/ShelfRundownLayout.tsx, meteor/package.json, meteor/public/origo-ui/dist/origo.css, meteor/yarn.lock, packages/live-status-gateway/src/collections/rundownHandler.ts
This pull request is posted on behalf of the BBC.
This is a: 
Feature / Other: enhancements and refactoring for better accessibility.
There is a number of accessibility issues, as presented in the original RFC: https://github.com/nrkno/sofie-core/issues/1125
Some of the issues were addressed. Some major changes were needed to the `ModalDialog` system in order to allow both _Escape/Enter_ key dismissal/confirmation of them and at the same time support multi-choice ModalDialogs. Also, _Tab_ key is no longer "disabled" in code, but instead will only be disabled if a _Tab_ Action Trigger is assigned.
* Check if the After Broadcast Form (Evaluations) still works as expected
* Check if the _Tab_ key for opening/closing shelf still works as previously
* Check if there are any regressions around …
=> feat: a11y improvements

meteor/client/styles/shelf/externalFramePanel.scss, meteor/client/ui/Settings/components/FilterEditor.tsx, meteor/client/ui/Shelf/BucketPanel.tsx, meteor/client/ui/Shelf/ExternalFramePanel.tsx, meteor/client/ui/Shelf/RundownViewBuckets.tsx, meteor/client/ui/Shelf/Shelf.tsx, meteor/lib/api/triggers/RundownViewEventBus.ts, meteor/lib/collections/RundownLayouts.ts
This is a  Feature
As of this PR is is possible for plugins to veer off the MOS plugin spec and provide a special drop page to be used for drag and drop operations. Sofie will listen for messages from both the external panel and the dropzone page. This mechanism allows us to work around limitations for drag and drop under cross origin policies.
We intend to add public documentation for this mechanism as part of another task.
=> feat: support external url dropzones

meteor/lib/api/pubsub.ts, meteor/server/migration/1_50_0.ts, meteor/server/publications/studio.ts, packages/corelib/src/dataModel/ExpectedPackages.ts, packages/job-worker/src/ingest/expectedPackages.ts
This is a:
Bug fix / Feature
This adds some missing publications and data to publications to allow sofie-prompter-editor to operate on the packages as it needs.
=> feat: support prompter-editor SOFIE-2846

.github/dependabot.yml
add npm security updates, set sofie team as default reviewers, remove docker updates for now
This is a:
Other (CI/Dependabot configuration)
=> ci: update dependabot config

packages/live-status-gateway/src/collections/partInstancesHandler.ts, packages/live-status-gateway/src/collections/pieceInstancesHandler.ts, packages/live-status-gateway/src/topics/activePlaylistTopic.ts
This is a:
Bug fix 
Sometimes the LSG would not send an `activePlaylist` topic update when the next partInstance changed in Sofie, due to some changes that don't affect the collection subscription being discarded by the PartInstancesHandler.
Sometimes the pieces would be missing in `currentPart` and `nextPart` due to a similar issue in the `PieceInstancesHandler`.
Pieces in `nextPart` were from the current partInstance.
`PartInstancesHandler` and `PieceInstancesHandler` notify the subscribers when relevant data changes so that the `activePlaylist` topic can send updates when needed.
Pieces in the `nextPart` are from the next partInstance.
- Set different parts as next multiple times in a row, and verify that each time the LSG sends an …
=> fix(live-status-gw): issues with the currentPart and nextPart of the activePlaylist

DEVELOPER.md
This is a: Documentation improvement
=> chore: fix developer docs for a clean install

meteor/package.json, meteor/yarn.lock, packages/mos-gateway/package.json, packages/mos-gateway/src/CoreMosDeviceHandler.ts, packages/shared-lib/package.json, packages/yarn.lock
This is a: Bug fix / Code improvement
[Latest bug fixes in mos-connection ](https://github.com/nrkno/sofie-mos-connection/blob/master/CHANGELOG.md#410-2024-04-02) are in mos-gateway.
* Normal release testing should suffice. Connect Sofie to a MOS NRCS and run a few mos operations, check that the updates come through.
=> chore: update mos-connection to v4.1.0

meteor/lib/collections/lib.ts, meteor/server/Connections.ts, meteor/server/__tests__/cronjobs.test.ts, meteor/server/api/__tests__/client.test.ts, meteor/server/api/blueprintConfigPresets.ts, meteor/server/api/blueprints/migrationContext.ts, meteor/server/api/integration/expectedPackages.ts, meteor/server/api/peripheralDevice.ts, meteor/server/api/studio/lib.ts, meteor/server/collections/collection.ts, meteor/server/migration/1_40_0.ts
Because the option `{ multi: true }` was missing in some places when calling `mongoCollection.update() .updateAsync() .upsert() .upsertAsync()`, instead of updating all objects, only the first matching document is updated.
New types disallow calling an update method which might affect multiple documents without specifying the `{ multi: boolean }` option.
All objects are now updated properly.
* Nightly cleanup of orphaned `PackageInfos` only marked a single document for later removal
* (unverified) When a PeripheralDevice goes offline, subdevices might not get their status set to offline
* (unverified) When a ShowStylebase changes its blueprint or config preset, not all variant got their blueprintConfigPresetIdUnlinked …
=> Fix: various cases where only one document would be updated (SOFIE-3100)

meteor/client/ui/Settings/SystemManagement.tsx, meteor/server/api/heapSnapshot.ts, meteor/server/api/rest/api.ts
This is a refactor of https://github.com/nrkno/sofie-core/pull/1165, targeting release51
=> fix: add a way to take a heap snapshot.

meteor/client/ui/Settings/SnapshotsView.tsx, meteor/lib/api/shapshot.ts, meteor/server/api/snapshot.ts, packages/corelib/src/worker/studio.ts, packages/job-worker/src/playout/snapshot.ts
When restoring a rundownPlaylist snapshot, only mediaObjects are restored, no other package-related data.
This is a problem when troubleshooting issues with packages, such as zebra stripes in the GUI.
Added a parameter to the restoreSnapshot method to allow the user to choose whether to only restore the rundownPlaylist, or also the studio-related data from the snapshot:
When uploading for debugging, the following additional data is restored:
* mediaObjects
* expectedPackageWorkStatuses
* packageContainerPackageStatuses
* packageInfos
When uploading normally, no additional data is restored.
* Just test that restoring of snapshots still work
=> fix: restore ALL data from snapshot, for debugging

meteor/client/styles/rundownView.scss, meteor/client/ui/SegmentContainer/PieceMultistepChevron.tsx, meteor/client/ui/SegmentList/LinePartMainPiece/LinePartMainPiece.tsx, meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx, meteor/client/ui/SegmentTimeline/Renderers/L3rdSourceRenderer.tsx
This is a:
Feature
The step in the stepped graphics display is shown as a "chevron".
=> feat: new style for step GFX pill (SOFIE-2838)

meteor/client/lib/Components/LabelAndOverrides.tsx, meteor/client/lib/forms/SchemaFormForCollection.tsx, meteor/client/lib/forms/SchemaFormInPlace.tsx, meteor/client/lib/forms/SchemaFormTable/ArrayTable.tsx, meteor/client/lib/forms/SchemaFormTable/ArrayTableOpHelper.tsx, meteor/client/lib/forms/SchemaFormTable/ArrayTableRow.tsx, meteor/client/lib/forms/SchemaFormTable/ObjectTable.tsx, meteor/client/lib/forms/SchemaFormTable/ObjectTableOpHelper.tsx, meteor/client/ui/Settings/ShowStyle/OutputLayer.tsx, meteor/client/ui/Settings/ShowStyle/SourceLayer.tsx, meteor/client/ui/Settings/Studio/Devices/GenericSubDevices.tsx, meteor/client/ui/Settings/Studio/Mappings.tsx, meteor/client/ui/Settings/components/triggeredActions/TriggeredActionEntry.tsx, meteor/client/ui/Settings/components/triggeredActions/actionEditors/ActionEditor.tsx, meteor/client/ui/Settings/util/OverrideOpHelper.tsx, packages/documentation/docs/for-developers/json-config-schema.md, packages/shared-lib/src/lib/JSONSchemaUtil.ts
This is a: Feature 
This adds support for import/export for a json schema object table. It is opt in per-table by setting `ui:import-export` to true.
When importing, it is possible to append to the existing table (replacing any rows with id colliisons), or replace the contents
To make this possible the `OverrideOpHelper` had to be reworked, as it was designed to perform a single change operation and wait for that to sync to meteor and back to the ui before performing the next.
At first I did try to add the batching as an extra portion, but that became quite messy to implement
=> feat: add import/export support to config object tables SOFIE-3138

meteor/client/lib/Components/Base64ImageInput.tsx, meteor/client/lib/forms/SchemaFormTable/ObjectTable.tsx, meteor/client/lib/forms/SchemaFormTable/ObjectTableOpHelper.tsx, meteor/client/ui/Settings/components/triggeredActions/TriggeredActionEntry.tsx, meteor/lib/api/triggeredActions.ts, meteor/lib/collections/TriggeredActions.ts, meteor/server/api/blueprints/migrationContext.ts, meteor/server/api/deviceTriggers/StudioDeviceTriggerManager.ts, meteor/server/api/triggeredActions.ts, meteor/server/migration/upgrades/showStyleBase.ts, meteor/server/publications/triggeredActionsUI.ts, packages/blueprints-integration/src/triggers.ts, packages/shared-lib/src/input-gateway/deviceTriggerPreviews.ts
This is a: Feature 
This adds the concept of `stylePreset`s to action triggers, and propogates them in the previews to the input-gateway.
This allows the input gateway to perform additional styling, defined as part of the config of the input devices. See https://github.com/nrkno/sofie-input-gateway/pull/21 for more info.
This PR affects the input-gateway integration
=> feat: action triggers styleClassNames SOFIE-3138

meteor/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardSecondaryPiece.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/Renderers/ThumbnailRendererFactory.ts, meteor/client/ui/Settings/ShowStyle/SourceLayer.tsx, packages/live-status-gateway/api/schemas/adLibs.yaml, packages/live-status-gateway/src/liveStatusServer.ts, packages/live-status-gateway/src/topics/__tests__/adLibs.spec.ts, packages/live-status-gateway/src/topics/__tests__/utils.ts, packages/live-status-gateway/src/topics/adLibsTopic.ts
This is a:
Bug fix / Feature / Code improvement / Documentation improvement / Other (please specify)
=> feat: live status gateway adlib origin info

packages/live-status-gateway/src/liveStatusServer.ts, packages/live-status-gateway/src/topics/adLibsTopic.ts, packages/live-status-gateway/src/topics/helpers/contentSorting.ts
This is a:
Bug fix / Feature / Code improvement / Documentation improvement / Other (please specify)
=> feat(LSG): sort adlibs to match GUI (SOFIE-3187)

meteor/server/api/rest/koa.ts, meteor/server/api/rest/v1/index.ts
This is a bugfix posted on behalf of NRK
This is a:
Bug fix
The UserActions Log UserEvent string is not very convenient. Also, the remoteAddress information is not extracted from `Forwarded` HTTP headers.
The logged remote address should match the "public" IP address of the callee. The UserActions Log userEvent should be more sensible (REST API, method, endpoint, host)
=> fix: API user actions log

meteor/client/ui/Shelf/DashboardPieceButton.tsx
This is a:
Bug fix
Hoverscrub previews on Bucket AdLibs are positioned incorrectly
Hoverscrub previews on Bucket AdLibs should correctly position themselves in the window (use document coordinate space).
* Ensure that Bucket AdLibs show hoverscrub preview in the correct position when the page is scrolled 
This fix should be potentially merged to release50 and certainly to release51
=> fix: bucket hoverscrub

meteor/client/lib/viewPort.ts
This pull request is posted on behalf of Jesper Stærkær
This is a:
Feature
When loading a playing rundown, the Rundown view will keep updating the scroll position to ensure that the currently playing segment is in view, while stuff shifts around while loading.
If a "wheel" event is issued from user trying to scroll around during that period, the behavior will be stopped.
* ensure that regular producers find the RundownView behaving as it was before.
* RundownView component
=> feat: break out of maintain focus

meteor/client/lib/popperUtils.ts, meteor/client/ui/Settings/components/triggeredActions/TriggeredActionsEditor.scss, meteor/client/ui/Settings/components/triggeredActions/actionEditors/actionSelector/ActionSelector.tsx, meteor/client/ui/Settings/components/triggeredActions/actionEditors/filterPreviews/FilterEditor.tsx, meteor/client/ui/Settings/components/triggeredActions/triggerEditors/TriggerEditor.tsx
This is a:
Bug fix
If a popup in the Action Triggers screen would show up beyond the bounds of the viewport, it will not be visible and it's necessary to scroll to see it.
The pop-up will reposition itself so that it's always visible. Also, a bug that prevented the filter chain construction to progress to next stage when the previous one is closed has been fixed.
* I don't think there's anything to test.
=> fix: always show Action Trigger popups

packages/live-status-gateway/src/collections/partInstancesHandler.ts, packages/live-status-gateway/src/collections/pieceInstancesHandler.ts, packages/live-status-gateway/src/collections/showStyleBaseHandler.ts, packages/live-status-gateway/src/liveStatusServer.ts, packages/live-status-gateway/src/topics/__tests__/activePlaylist.spec.ts
Live status gateway is emitting pieces in its 'activePieces' list which are not active, and will not be played.
This happens because the pieces get pruned before being added to the timeline due to them starting at the same instant as another piece, so the stoppedPlayback numbers never get set
These pieces are now pruned, in the same way as is done when generating the timeline
=> fix: live status gateway including pieces which have been pruned and will never be played SOFIE-3301

packages/live-status-gateway/src/topics/activePiecesTopic.ts, packages/live-status-gateway/src/topics/activePlaylistTopic.ts, packages/live-status-gateway/src/topics/adLibsTopic.ts, packages/live-status-gateway/src/topics/root.ts, packages/live-status-gateway/src/topics/segmentsTopic.ts, packages/live-status-gateway/src/topics/studioTopic.ts, packages/live-status-gateway/src/wsHandler.ts
This is a:
Performance improvement
When testing locally, the size of an ActivePlaylist message is about 170kB. This takes around 1ms to stringify, so if LSG has several/many recipients, those numbers quickly add up.
when sending a message, the message is only stringified once, then sent to the recipients.
=> Fix: live status gateway send message performance

packages/live-status-gateway/src/coreHandler.ts
This is a:
Bug fix
Upon startup LSG doesn't use the device settings from Core, so logLevel will be using `silly`.
If the settings are changed, LSG picks them up properly.
LSG picks up the correct settings upon startup,
=> Fix: live status gateway settings not used

packages/live-status-gateway/api/schemas/adLibs.yaml
This pull request is posted on my behalf.
This is a:
The Live Status Gateway documentation doesn't build
Documentation builds correctly
* This PR affects documentation
I can rebase this PR onto release51 if that makes more sense.
=> fix(LSG): Token "examples" does not exist when running `yarn gendocs`

meteor/client/lib/VirtualElement.tsx, meteor/package.json, meteor/yarn.lock, tsconfig.json
This is a:
Bug fix
We've had an issue where a Segment component has been left in the _optimized-away_ state after it came into the viewport. We were not able to reproduce this issue.
Since we were not able to reproduce the issue, we've decided to try and refactor the `VirtualElement` component into a Functional component, hopefully fixing whatever state-change-race-condition issue this was caused by. This PR also updates the `react-intersection-observer` library that `VirtualElement` uses.
* This PR affects the RundownView
=> fix: Virtual Element (sofie-3264)

.github/workflows/sonar.yaml
This pull request is posted on behalf of the NRK (but via my personal fork).
This is a: CI improvement 
SonarCloud runs on every PR. But for external PRs it fails, due to the `SONAR_TOKEN` not being set.
SonarCloud is skipped for external PRs, but still runs on internal PRs.
See for example how it is [skipped for this PR](https://github.com/nrkno/sofie-core/actions/runs/9856292382/job/27212973979?pr=1224), but [still runs ](https://github.com/nrkno/sofie-core/actions/runs/9856362073/job/27213188890?pr=1225) for an internal PR.
This PR affects the CI only. No testing of Sofie needed.
=> SonarCloud skip on external prs

packages/blueprints-integration/src/context/adlibActionContext.ts, packages/blueprints-integration/src/context/rundownContext.ts, packages/job-worker/src/blueprints/context/RundownActivationContext.ts, packages/job-worker/src/blueprints/context/adlibActions.ts, packages/job-worker/src/playout/datastore.ts, packages/playout-gateway/src/tsrHandler.ts
During `onRundownActivate`, blueprints are expected to execute TSR actions to perform any preperation for playing a rundown.
This change makes it possible to also modify any values in the datastore, which will allow for ensuring any infinite values are defined correctly, or any other values do not have any pre-existing values which are not wanted when starting a rundown
=> feat: modify datastore in `onRundownActivate` SOFIE-3310

meteor/client/lib/KeyboardFocusIndicator.tsx, meteor/lib/api/userActions.ts, meteor/server/api/client.ts, meteor/server/api/rest/v1/index.ts, meteor/server/api/userActions.ts
This is a: Feature 
Related to #1242, this PR aims to make the content a little more compact (often removing two lines) and make it more readable.
This has been done by requiring the logged arguments to be an object, instead of an array. 
Previously we were either logging an object inside an array, or an array of simple parameters that were not obvious how to interpret.
This now always logs an object (not inside an array), making it a bit more compact, and ensuring each value has a name
Before:
After:
=> feat: improve user log clarity SOFIE-3382

packages/job-worker/src/playout/adlibAction.ts, packages/job-worker/src/playout/lookahead/index.ts, packages/job-worker/src/workers/parent-base.ts
This is a:
Minor performance improvements
Slight improvements in performance.
This PR touches playout features, but should not have any impact on functionality.
=> Minor performance improvements (SOFIE-3388)

meteor/client/styles/prompter.scss, meteor/client/ui/Prompter/PrompterView.tsx, meteor/client/ui/Prompter/prompter.ts
This is a:
Feature
Prompter ignores Rundowns and shows all Segments as an integrated continuous list.
Prompter shows inter-titles for Rundowns if there are more than one Rundown in a Playlist
This PR affects the prompter.
This Feature is critical for us, please review and merge it as soon as possible.
=> feat(Prompter): add Rundown name inter-titles

meteor/client/lib/KeyboardFocusIndicator.tsx, meteor/client/lib/collapseJSON.tsx, meteor/client/lib/datePicker.tsx, meteor/client/styles/collapseJSON.scss, meteor/client/ui/Status/UserActivity.tsx, meteor/lib/api/userActions.ts, meteor/server/api/client.ts, meteor/server/api/rest/v1/buckets.ts, meteor/server/api/rest/v1/playlists.ts, meteor/server/api/rest/v1/studios.ts, meteor/server/api/userActions.ts, meteor/server/publications/organization.ts
This is a:
Feature
On the User Activity Log page, the full parameters are displayed, so if the parameters are very long, the view becomes almost unusable due to each entry spanning 100s of lines.
=> fix: improve userAction-log view (SOFIE-3382)

meteor/client/lib/data/nora/browser-plugin-data.ts, meteor/client/ui/FloatingInspectors/L3rdFloatingInspector.tsx, meteor/client/ui/FloatingInspectors/NoraFloatingInspector.tsx, meteor/client/ui/SegmentContainer/PieceMultistepChevron.tsx, meteor/client/ui/Shelf/Inspector/ItemRenderers/NoraItemRenderer.tsx, meteor/server/migration/1_51_0.ts, packages/blueprints-integration/src/content.ts
This is a: Feature / Performance improvement
Inside the `Piece.content` property of nora pieces, the `payload` property contains the payload needed by the nora renderer to display the template. For some types of graphics, this can become a very large multi kb json object.
This object has a high cost for deserializing this object in the backend.
We can instead store the data as a string, and parse it in the ui only when we need to pass it off to nora.
A few fields that the UI uses to display these pieces have been pulled out into separate objects, to make them easily accessible
=> feat: stringify piece NoraContent payload SOFIE-3398

meteor/client/ui/SegmentList/LinePartTimeline.tsx, packages/documentation/docs/user-guide/features/sofie-views.mdx
This is a:
Bug fix
Certain types of graphic overlays displayed on top of a KAM or RM are not visible in List View mode.
If the Piece is infinite _but_ it doesn't have a column assigned to the Source Layer, display it in the Timeline anyway.
This PR affects the Segment List View.
=> fix(Segment List): infinite Pieces are not visible if they don't have a column assigned

meteor/client/lib/Components/TextInput.tsx, meteor/client/lib/EditAttribute.tsx, meteor/client/ui/Settings/components/triggeredActions/actionEditors/actionSelector/actionEditors/AdLibActionEditor.tsx
When editing the triggermode of an action trigger, the cursor keeps jumping to the end of the input field
=> fix: avoid cursor jumping when editing action trigger 'trigger mode' SOFIE-3429

packages/live-status-gateway/src/collections/pieceInstancesHandler.ts
This is a:
Bug fix
Pieces in previous part stays active in LSG
Pieces in previous part are not active in LSG anymore
=> fix: only include previous PieceInstances in active when the previous partInstane hasn't stopped yet (SOFIE-3428)

meteor/client/lib/Components/ToggleSwitch.tsx, meteor/client/lib/EditAttribute.tsx, meteor/client/ui/Settings/components/triggeredActions/actionEditors/actionSelector/ActionSelector.tsx, meteor/client/ui/Settings/components/triggeredActions/actionEditors/actionSelector/actionEditors/AdLibActionEditor.tsx, meteor/client/ui/Settings/components/triggeredActions/actionEditors/filterPreviews/FilterEditor.tsx, meteor/client/ui/Settings/components/triggeredActions/triggerEditors/DeviceEditor.tsx, meteor/client/ui/Settings/components/triggeredActions/triggerEditors/HotkeyEditor.tsx, packages/blueprints-integration/src/migrations.ts
This is a: Code improvement 
Follow up to #1253.
This removes the usages of `EditAttribute` which do not use either the `collection` attribute, or a dynamic type.  
Doing this avoids some extra layers of components and type uncertainty without any change in functionality.
=> chore: remove some unnecessary uses of EditAttribute

meteor/client/ui/SegmentList/LinePartSecondaryPiece/LinePartSecondaryPiece.tsx, meteor/client/ui/SegmentList/LinePartTimeline.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnail.tsx
This is a:
Bug fix
Infinite Lower Third pieces can display incorrectly in List View.
Within-Part Infinite Lower Thirds should display correctly.
* This PR affects the List View and Storyboard View.
=> fix(LinePartTimeline): make rules for findMainPiece consistent (SOFIE-3408)

CONTRIBUTING.md, packages/documentation/docs/for-developers/contribution-guidelines.md
This is a: Documentation change of the Contribution Guidelines
This PR updates the Contribution Guidelines to Require contributions to be based on latest in-development branch.
=> Contribution Guidelines: Require contributions to target in-dev

.github/workflows/node.yaml
This is a:
Other (CI)
Trivy gets rate limited when trying to pull the database image needed for scanning.
Hopefully adding the github token as an environment variable will prevent us from being rate limited
* This PR affects the CI of this repo
=> ci: add github token as environment variable to trivy scanning job

.github/workflows/node.yaml, .github/workflows/trivy.yml
This is a:
Other (CI)
Trivy Github Action is rate limited trying to pull the database image. Adding a Github token doesn not seem to help the issue. Trivy has published the database image to ECR, ref. discussion found here: https://github.com/aquasecurity/trivy/discussions/7538#top
This PR affects the CI of this repo.
=> ci: use custom trivy database image

packages/corelib/src/playout/playlist.ts, packages/job-worker/src/playout/model/implementation/LoadPlayoutModel.ts, packages/job-worker/src/playout/model/implementation/__tests__/LoadPlayoutModel.spec.ts
This is a:
Bug fix
When taking a Part at the very end of a Rundown, selecting next Part can end up with unexpected results, potentially with no Next part at all. This happens because Rundowns are not sorted in the `loadPlayoutModelPreInit()` according to their position in the `RundownPlaylist.rundownIdsInOrder`.
Rundowns in `PlayoutModelPreInit` should be now sorted according to the general rules for ordering Rundowns in a RundownPlaylist.
This PR affects the playout logic in general, specifically selecting the next Part after a take.
=> fix: playout model rundowns not in order (SOFIE-3501)

meteor/server/migration/X_X_X.ts, packages/blueprints-integration/src/abPlayback.ts, packages/corelib/src/dataModel/Studio.ts, packages/corelib/src/overrideOpHelper.ts, packages/job-worker/src/playout/abPlayback/__tests__/abPlayback.spec.ts, packages/job-worker/src/playout/abPlayback/__tests__/abPlaybackResolver.spec.ts, packages/job-worker/src/playout/abPlayback/__tests__/routeSetDisabling.spec.ts, packages/job-worker/src/playout/abPlayback/abPlaybackResolver.ts, packages/job-worker/src/playout/abPlayback/abPlaybackSessions.ts, packages/job-worker/src/playout/abPlayback/applyAssignments.ts, packages/job-worker/src/playout/abPlayback/index.ts, packages/job-worker/src/playout/abPlayback/routeSetDisabling.ts, packages/job-worker/src/playout/upgrade.ts, packages/job-worker/src/studio/model/StudioBaselineHelper.ts, packages/shared-lib/src/core/model/StudioRouteSet.ts, packages/webui/src/client/ui/Settings/Studio/Routings/RouteSetAbPlayers.tsx, packages/webui/src/client/ui/Settings/Studio/Routings/RouteSets.tsx
This builds upon and includes the changes from #1262
This adds the ability for RouteSets to control whether AB players are enabled or disabled.
This is intended to allow the user to disable an AB player in the case of it having issues, and allow Sofie to handle that by not using that player.
We chose to build this into RouteSets, to avoid adding new concepts that have some overlap with existing features. By utilising these, it allows for defining these controls in the existing switchboard panel. And it also allows for more advanced usage of this functionality, as disabling a player can also change some routes which could be setup to cause some side effects.
=> feat: routeset controlled ab player availability

packages/job-worker/src/blueprints/postProcess.ts, packages/job-worker/src/ingest/bucket/import.ts
This is a:
Bug fix
When using `listenToPackageInfoUpdates` on Bucket items, subsequent bucket item regenerations will mangle user edits to labels and rank, reordering the items in the bucket.
Ranks and labels should be kept across regenerations, so that users are not surprised by ordering or label changes.
This PR affects Buckets ingest
=> fix(Bucket AdLibs): maintain rank and label over regeneration of a Bucket Item

meteor/client/ui/Status/ExternalMessages.tsx
This is a:
Bug fix
The "Queued Messages" list in External Messages Status displays the same list as the "Sent Messages".
Queued Messages are displayed in their correct location.
This PR affects the User Interface for monitoring External Messages
=> fix(External Messages Status): Queued Messages List displays sent messages instead

packages/webui/src/client/ui/Prompter/prompter.ts
The prompter will only display script pieces that are arranged to be the first pieces in a part
The prompter will look at all pieces in the part and display any script pieces regardless of their order
Prompter View
=> Fix: prompter skips script pieces

packages/live-status-gateway/api/schemas/activePlaylist.yaml, packages/live-status-gateway/src/topics/__tests__/activePlaylist.spec.ts, packages/live-status-gateway/src/topics/activePlaylistTopic.ts
This is an Improvement
Playlist timings (timing type, expected start, duration and end) are exposed via the Live Status Gateway
Live Status Gateway
=> Add playlist timings to LSG

meteor/client/ui/SegmentStoryboard/SegmentStoryboard.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/Renderers/ThumbnailRendererFactory.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnail.tsx, meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnailInner.tsx
This is a:
Bug fix
Because ThumbnailRenderer is used _like_ a React Component, but is in fact _not a React component_ - it may end up breaking some of React's rules of hooks under some Piece mutation circumstances.
ThumbnailRenderer is transformed into a regular React component, resolving any issues where it may make hooks look to be "conditionally executed".
* This PR affects the Segment Thumbnail view.
We intend to finish the development on this feature in two weeks time.
=> fix: Segment component crash (sofie-3542)

packages/blueprints-integration/src/context/adlibActionContext.ts, packages/blueprints-integration/src/context/routeSetContext.ts, packages/job-worker/src/blueprints/context/adlibActions.ts, packages/webui/src/client/ui/Status/SystemStatus/SystemStatus.tsx
This is a feature/enhancement
A method on the AdlibActionContext is provided which returns the routesets
This PR affects the Adlib Action Context.
- [x Relevant unit tests has been added / updated.
=> Feature: list routesets in adlib actions

packages/corelib/src/playout/playlist.ts, packages/job-worker/src/playout/model/PlayoutModel.ts, packages/job-worker/src/playout/model/implementation/LoadPlayoutModel.ts, packages/job-worker/src/playout/model/implementation/__tests__/LoadPlayoutModel.spec.ts
This is a:
Bug fix
When creating a Playout Model from an Ingest Model, the Rundowns will not be in correct order. This can cause very unexpected behavior when next-selection mechanism is run after an Ingest.
Rundowns should now be sorted in playlist order when creating a Playout Model from an Ingest Model.
This PR affects playout logic when dealing with playout side-effects from ingest.
=> fix: Playout Model has unsorted Rundowns when it's created from an Ingest Model (SOFIE-3501)

meteor/client/ui/ActiveRundownView.tsx, meteor/client/ui/util/useSetDocumentClass.ts
This is a:
Bug fix
When using the `/activeRundown/:studioId` endpoint, the UI may go from "dark mode" to "light mode" when showing a status message such as "There is no Rundown active in this Studio", etc.
The view should consistently stay in "dark mode"
* This PR affects the "Active Rundown" view.
* This Bug Fix is not critical, but we intend to include it in the nearest patch release.
=> fix: ActiveRundownView doesn't keep being dark

packages/shared-lib/src/package-manager/packageInfo.ts
This is a:
Bug fix
JSON document type for PackageInfo is missing, even though it's used in the wild.
Add a JSON document type as used in practice.
I'm not sure if it makes sense to include in 1.51.x branch, or to direct this towards 1.52.x.
=> fix: packageInfo JSON type is missing (SOFIE-3617)

packages/job-worker/src/playout/resolvedPieces.ts, packages/job-worker/src/playout/timeline/generate.ts, packages/job-worker/src/playout/timings/partPlayback.ts, packages/job-worker/src/playout/timings/timelineTriggerTime.ts
This is a:
Bug fix
We have been experiencing a wierd issue where the resolvedDuration is negative, thus causing downstream issues in onTimelineGenerate in blueprints when handling pieces during transitions.
The NextPartStarted is only set when there is an autonext about to happen, thus not capping the current part in many cases
This PR affects the playout logic in general.
=> fix: negative resolvedDuration (SOFIE-3559)

packages/live-status-gateway/Dockerfile.circle, packages/mos-gateway/Dockerfile.circle, packages/playout-gateway/Dockerfile.circle
=> fix: change CMD in GHA Dockerfile

packages/documentation/docs/for-developers/url-query-parameters.md, packages/documentation/docs/user-guide/features/access-levels.md
This pull request is posted on behalf of SuperFly.tv
This is a:
Many URL query parameters were not documented.
Added a new page that collects all the URL query parameters.
Documentation
* Not urgent
- [] Relevant unit tests has been added / updated.
=> Documentation updated with URL query parameters

packages/documentation/docs/user-guide/installation/installing-package-manager.md, packages/shared-lib/src/pubsub/peripheralDevice.ts
This is a: Bug fix / Documentation improvement
This adds some documentation based on our exploration of deploying package manager in its 'distributed' form. This was out of a need for running it across multiple casparcg machines, with no direct access between the machines.
Additionally, this includes a fix for the publication typings for package-manager to be compatible when #1331 is enabled.
=> chore: add docs for distributed package-manager

meteor/server/lib/rest/v1/studios.ts
There was a typo in #1347 which is causing a type error
=> chore: fix typo

packages/job-worker/src/ingest/commit.ts, packages/job-worker/src/ingest/lock.ts, packages/job-worker/src/ingest/mosDevice/diff.ts, packages/job-worker/src/ingest/syncChangesToPartInstance.ts, packages/job-worker/src/playout/adlibJobs.ts, packages/job-worker/src/playout/infinites.ts, packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts, packages/job-worker/src/playout/setNext.ts
This is a:
Bug fix
Next PartInstance can become invalid, if the underlying Part is floated and the source Segment disappears.
The behavior from earlier releases is restored where in this case a new "Next" will be selected.
This PR affects playout operations.
=> fix: Next PartInstance can become invalid if it's Part gets deleted, resulting in a critical crash in worker

meteor/package.json, meteor/yarn.lock, packages/meteor-lib/package.json, packages/mos-gateway/package.json, packages/shared-lib/package.json, packages/yarn.lock
This is a:
Bug fix
In MOS data from an NRCS, if a `ExternalMetadata.MosPayload` contains a string content, it is passed through as an empty string.
`ExternalMetadata.MosPayload` is passed through properly.
=> fix: ExternalMetadata.MosPayload pass through string content (SOFIE-3744)

packages/webui/src/client/lib/ModalDialog.tsx, packages/webui/src/client/styles/modalDialog.scss, packages/webui/src/client/ui/RundownView.tsx
Currently there some inconsistency in Rundown activation
This PR is based on RFC: Consistent Rundown Activation Options for On Air Mode https://github.com/nrkno/sofie-core/issues/1316 and make the rundown activation more consistent for the end user.
This PR affects rundown activation and ModalDialog
=> Feat: Consistent rundown activation logic

packages/blueprints-integration/src/ingest.ts, packages/blueprints-integration/src/userEditing.ts, packages/corelib/src/dataModel/UserEditingDefinitions.ts, packages/job-worker/src/blueprints/context/lib.ts, packages/webui/src/client/styles/rundownView.scss, packages/webui/src/client/ui/SegmentTimeline/Parts/SegmentTimelinePart.tsx, packages/webui/src/client/ui/Shelf/ExternalFramePanel.tsx, packages/webui/src/client/ui/UserEditOperations/RenderUserEditOperations.tsx
_Note: this PR is based on the Properties Panel PR (#1342), look at the last commit to see changes relevant to this feature_
This pull request is posted on behalf of the **BBC**.
This is a **Feature**.
MOS Items can only be dragged from plugins into buckets from where they can be played out.
A MOS Item from a plug-in can be dragged onto a Part, the Blueprints implement a method to process this operation. An example would be to replace the current media in the part.
This PR mostly affects the drag operations in the UI. It's a fairly concise implementation.
- The Bucket system currently supports a second type of plug-ins which involves hosting an iframe in the drop zone. I've ignored that system for this …
=> Drag MOS Item on a Part to ingest

packages/meteor-lib/src/api/pubsub.ts
This is a:
Bug fix (affecting logs only)
_False_ errors about two publications removed from Sofie are logged, because the publication names remain in the `MeteorPubSub` enum
Aforementioned errors are gone
Just logs
Not urgent
=> fix: remove leftover publication names

meteor/server/api/blueprints/api.ts, meteor/server/publications/pieceContentStatusUI/__tests__/checkPieceContentStatus.test.ts, meteor/server/publications/pieceContentStatusUI/bucket/bucketContentCache.ts, meteor/server/publications/pieceContentStatusUI/bucket/bucketContentObserver.ts, meteor/server/publications/pieceContentStatusUI/bucket/publication.ts, meteor/server/publications/pieceContentStatusUI/bucket/regenerateForItem.ts, meteor/server/publications/pieceContentStatusUI/checkPieceContentStatus.ts, meteor/server/publications/pieceContentStatusUI/messageFactory.ts, meteor/server/publications/pieceContentStatusUI/rundown/publication.ts, meteor/server/publications/pieceContentStatusUI/rundown/reactiveContentCache.ts, meteor/server/publications/pieceContentStatusUI/rundown/regenerateItems.ts, meteor/server/publications/pieceContentStatusUI/rundown/rundownContentObserver.ts, packages/blueprints-integration/src/api/showStyle.ts, packages/corelib/src/dataModel/Blueprint.ts, packages/meteor-lib/src/collections/ExpectedPackages.ts, packages/shared-lib/src/packageStatusMessages.ts, packages/webui/src/client/lib/dev.ts, packages/webui/src/client/ui/FloatingInspectors/VTFloatingInspector.tsx, packages/webui/src/client/ui/RundownView/RundownNotifier.tsx
This pull request is posted on behalf of the BBC.
This implements the RFC #1349 as agreed.
The ShowStyle blueprints are now able to define a new property `packageStatusMessages` which are used in the pieceContentStatus checks instead of the builtin strings.
Additionally, this has made a few tweaks to how the messages are handled.
* In the UI when there were multiple messages they were being printed one one line separated by a `;`. They will now be split into multiple lines to aid readability.
* If there are multiple containers expecting the same package for different devices, this would often cause the same message to be repeated, once for each container. These now get merged. For translation purposes there `containerLabels` value which contains a comma separated list …
=> feat: customizable package status messages #1349

packages/blueprints-integration/src/context/onSetAsNextContext.ts, packages/blueprints-integration/src/context/partsAndPieceActionContext.ts, packages/job-worker/src/blueprints/__tests__/context-OnSetAsNextContext.test.ts, packages/job-worker/src/blueprints/__tests__/context-OnTakeContext.test.ts, packages/job-worker/src/blueprints/__tests__/context-adlibActions.test.ts, packages/job-worker/src/blueprints/context/OnSetAsNextContext.ts, packages/job-worker/src/blueprints/context/OnTakeContext.ts, packages/job-worker/src/blueprints/context/adlibActions.ts, packages/job-worker/src/blueprints/context/services/PartAndPieceInstanceActionService.ts, packages/job-worker/src/blueprints/context/services/__tests__/PartAndPieceInstanceActionService.test.ts
Allow adlib actions to remove pieceinstances from the current partinstance.
This was previously explicitly blocked with the comment `Note: For now we only allow removing from the next, but this might change to include current if there is justification`. Our justification is to allow for removing of pieceinstances which have not started playback, which may cause glitches if they begin during the outtransition, or could confuse other logic which looks at the pieces on the timeline
=> feat: allow adlib-actions to remove pieces from the current partInstance

meteor/client/styles/shelf/shelf.scss, meteor/client/ui/Shelf/ShelfRundownLayout.tsx
This is a:
Feature
Tabs in the Shelf have a fixed width. Shortcuts tab is separated when tab overflow needs to happen.
Shelf tabs will now have varying size depending on the length of the label. In most cases, this will result in more narrow Tabs, compacting this area of the UI. Shortcuts tab is also included in the overflow, allowing it to be off-screen, when switching between the Tabs the users are using the most.
This PR affects the Shelf component.
This Bug Fix is critical for us, please review and merge it as soon as possible. We would like this to be included in the `1.51.x` version family.
=> feat: shelf tabs are narrower (sofie-3849)

meteor/server/api/deviceTriggers/PieceInstancesObserver.ts, meteor/server/api/deviceTriggers/StudioDeviceTriggerManager.ts, meteor/server/api/deviceTriggers/StudioObserver.ts, meteor/server/api/deviceTriggers/TagsService.ts, meteor/server/api/deviceTriggers/__tests__/TagsService.test.ts, meteor/server/api/deviceTriggers/observer.ts, meteor/server/api/deviceTriggers/reactiveContentCacheForPieceInstances.ts, packages/corelib/src/lib.ts, packages/meteor-lib/src/triggers/actionFilterChainCompilers.ts, packages/shared-lib/src/input-gateway/deviceTriggerPreviews.ts
This is a:
Feature
Tally information, based on the existing tally-tags system (`currentPieceTags`) is added to the device trigger previews
This PR affects the device triggers publication that the Input Gateway consumes
Not urgent, but it would be nice to have in release 52
=> feat: implement tally for device trigger previews

packages/webui/src/client/ui/SegmentList/SegmentListContainer.tsx, packages/webui/src/client/ui/SegmentStoryboard/SegmentStoryboardContainer.tsx
Bug fix / Feature / Code improvement / Documentation improvement / Other (please specify)
Currently the mini shelf is only available in the normal rundown view.
Mini shelf are now available in all 3 views.
This PR only affects Storyboard view and segment list view.
Has been approved by BBC
=> feat: mini shelfview

packages/webui/src/client/ui/SegmentStoryboard/SegmentStoryboard.tsx, packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardPartSecondaryPieces.tsx, packages/webui/src/client/ui/SegmentTimeline/SegmentTimeline.tsx
This is a:
Bug fix
Source Layers and Output Groups are not sorted according to Rank in the Segment Storyboard Mode.
Source Layers and Output Groups are sorted in the same way they are sorted in Segment Timeline view.
* Ensure that the Segment Storyboard view works correctly.
This PR affects the Segment Storyboard mode.
We intend to finish the development on this feature in two weeks time.
=> fix(Segment Storyboard): sorted storyboard sourcelayers (SOFIE-3433)

packages/documentation/docs/user-guide/concepts-and-architecture.md, packages/documentation/docs/user-guide/features/prompter.md, packages/documentation/docs/user-guide/features/sofie-views-and-screens.mdx
This pull request is posted on behalf of SuperFly.tv.
This is a:
Documentation used the terms "view"/"screen"/"mode" in an inconsistent and jumbled way.
Added definition of the terms, and updated relevant pages to use the terms that are defined.
*  This PR only affects the documentation.
=> Documentation clarification on Screens and Views

packages/documentation/docs/for-developers/for-blueprint-developers/manipulating-ingest-data.md
This is a: Documentation improvement 
This adds some documentation for blueprint developers on how to utilise https://github.com/nrkno/sofie-core/pull/1293
=> chore: add documentation page for `processIngestData`

packages/webui/src/client/ui/PreviewPopUp/PreviewPopUpContext.tsx
Bug fix
Updates the new hover previews to include #1355, which was already included functionally just not exposed yet (missed a todo during a rebase)
=> Enable in/out words in new VT previews

packages/blueprints-integration/src/context/syncIngestChangesContext.ts, packages/job-worker/src/blueprints/context/SyncIngestUpdateToPartInstanceContext.ts, packages/job-worker/src/ingest/__tests__/syncChangesToPartInstance.test.ts, packages/job-worker/src/ingest/syncChangesToPartInstance.ts
This is a regression believed to be introduced by https://github.com/nrkno/sofie-core/pull/1035
The `removePartInstance` method on `SyncIngestUpdateToPartInstanceContext` is broken, it did not reset the PartInstance correctly.
This PR reimplements this for the new model approach.
As part of this, some refactoring was done first, to make it easier to unit test portions of this logic. Not many tests have been added as part of this, but tests have been added for `removePartInstance`.
I have not looked into backporting this fix to earlier releases, but I suspect it would be pretty straightforward to rebase it without the refactoring or unit tests.
=> fix: reimplement removePartInstance flow for `syncChangesToPartInstances`

packages/webui/src/client/ui/App.tsx, packages/webui/src/client/ui/RundownList.tsx, packages/webui/src/client/ui/Settings.tsx, packages/webui/src/client/ui/Status.tsx, packages/webui/src/client/ui/TestTools/index.tsx
https://github.com/nrkno/sofie-core/pull/1400 did some refactoring to remove the root container, moving it and the 'header-clear' class into each of the pages which needed it.
When merged to r53, this appears to have been largely reverted (I assume accidentally), except for in the rundown view causing a gap at the top
This restores the refactoring of #1400
=> fix: bad header-clear merge

packages/webui/src/client/ui/Prompter/PrompterView.tsx
This PR is opened on behalf of TV 2 Norge
This is a:
Bug fix
The prompter view refuses to scroll automatically with `followtake=1`, nor does it scroll when triggering scroll to next, prev etc. through a controller device.
Correct scrolling is brought back by fixing the usage of `animate`
Affects the PrompterView only, including with different controller devices
Quite a critical issue for those using PrompterView 
I can see that when getting rid of velocity-react, durations of all affected scroll animations were changed to 0.4s, which looks fine to me, so I left it at that.
=> fix(PrompterView): make prompter scroll

packages/webui/src/client/styles/countdown/director.scss, packages/webui/src/client/ui/ClockView/ClockView.tsx, packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewPieceIcons.scss, packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/RemoteSpeakInputIcon.tsx
this PR is made on behalf of SuperFly
UI Bug fix
Icon and Piece text was not aligned
split Icons did not use the correct variables
Aligned and color corrected
Director's Screen
=> Fix: Directors screen - Align icon and text, and fix split colors

meteor/package.json, meteor/yarn.lock, packages/job-worker/package.json, packages/playout-gateway/package.json, packages/shared-lib/package.json, packages/yarn.lock
This is a:
Bug fix
Technically, this is only a dependency update. See https://github.com/nrkno/sofie-timeline-state-resolver/pull/378 for details.
=> fix: update timeline-state-resolver to a version containing a fix for B-A-B issue (SOFIE-3889)

meteor/package.json, meteor/yarn.lock, packages/job-worker/package.json, packages/playout-gateway/package.json, packages/yarn.lock
This is a:
Bug fix
This is technically just a dependency update.
=> fix: device state goes B-A-B (SOFIE-3889)

packages/documentation/docs/user-guide/installation/installing-sofie-server-core.md
This is a:
Information that Container images will now run as UID 1000 is added.
* This PR does not affect any functional area.
=> chore(docs): add infromation about the Sofie container image UID change

packages/documentation/docs/user-guide/concepts-and-architecture.md, packages/documentation/docs/user-guide/configuration/settings-view.md, packages/documentation/docs/user-guide/configuration/sofie-core-settings.md, packages/documentation/docs/user-guide/features/access-levels.md, packages/documentation/docs/user-guide/features/api.md, packages/documentation/docs/user-guide/features/prompter.md, packages/documentation/docs/user-guide/features/sofie-views-and-screens.mdx, packages/documentation/docs/user-guide/further-reading.md, packages/documentation/docs/user-guide/installation/installing-a-gateway/playout-gateway.md, packages/documentation/docs/user-guide/installation/installing-a-gateway/rundown-or-newsroom-system-connection/inews-gateway.md, packages/documentation/docs/user-guide/installation/installing-a-gateway/rundown-or-newsroom-system-connection/installing-sofie-with-google-spreadsheet-support.md, packages/documentation/docs/user-guide/installation/installing-a-gateway/rundown-or-newsroom-system-connection/intro.md, packages/documentation/docs/user-guide/installation/installing-blueprints.md, packages/documentation/docs/user-guide/installation/installing-connections-and-additional-hardware/README.md, packages/documentation/docs/user-guide/installation/installing-connections-and-additional-hardware/casparcg-server-installation.md, packages/documentation/docs/user-guide/installation/installing-connections-and-additional-hardware/ffmpeg-installation.md, packages/documentation/docs/user-guide/installation/installing-sofie-server-core.md, packages/documentation/docs/user-guide/installation/intro.md, packages/documentation/docs/user-guide/intro.md, packages/documentation/docs/user-guide/supported-devices.md
On behalf of SuperFly.tv
This is a Documentation improvement
This PR affects the user guide, fixing some errors and updating to reflect changes to the system.
n/a
- n/a The functionality has been tested by the author.
- n/a Relevant unit tests has been added / updated.
=> docs: General improvements to User Guide

packages/live-status-gateway-api/api/schemas/buckets.yaml, packages/live-status-gateway-api/src/generated/schema.ts
This pull request is posted on behalf of TV 2 Norge.
This is a:
Bug fix (?) - making the types and definitions exposed by live-status-gateway-api more in line with reality
Properties of BucketStatus are optional, even though they are always present in the output, and make no sense to be undefined
Properties of BucketStatus are marked required; additional properties are disallowed.
Those changes affect Live Status Gateway API package only, and IMO it's safe to treat them as non-breaking from the perspective of consumers of the package
=> fix: make buckets properties required in LSG API

packages/openapi/README.md
This pull request is posted on behalf of Superfly.
This is a: Documentation improvement
Example code is missing instantiation of SofieApi and PlaylistsApi.
Example code is now a functional example.
=> chore: update example in openapi readme

packages/documentation/src/components/HomepageFeatures.js
This pull request is posted on behalf of SuperFly.tv.
This is a:
One of the links on the main page of the docs is incorrect.
Link has been corrected.
* This PR affects the documentation.
* Not urgent, but a safe fix than can just be merged.
=> chore: Corrected expired Slack invite link

packages/live-status-gateway-api/package.json, packages/live-status-gateway-api/scripts/generate-schema-types.mjs
This pull request is posted on behalf of SuperFly.tv
This is a:
Code improvement
~This PR excludes the generated types in the LSG API from the reformatting script, and regenerates them in their original, unchanged form.~
This PR adds a formatting step when generating the LSG API types, to keep the generated types consistent with the rest of the code.
This makes contributions easier as it avoids merge conflicts when re-generating the types.
No practical changes, code formatting only.
=> Format LSG API type file

meteor/server/publications/lib/quickLoop.ts, meteor/server/publications/partInstancesUI/publication.ts, meteor/server/publications/partInstancesUI/reactiveContentCache.ts, meteor/server/publications/partInstancesUI/rundownContentObserver.ts
This is made on behalf of bbc
This is a bug fix, that has not been merged upstream
This looks like a fix for the findMarkerPosition
Testing is unknown, but the fix is in production at bbc
=> fix: findMarkerPosition always needs all parts available

packages/webui/src/client/ui/RundownList.tsx
This PR is made on behalf of bbc
Fix
This is a small UI fix, that was not merged upstream 
In production at bbc
=> fix: adjust padding of rundownlist

packages/blueprints-integration/src/context/onSetAsNextContext.ts, packages/job-worker/src/blueprints/__tests__/context-OnSetAsNextContext.test.ts, packages/job-worker/src/blueprints/context/OnSetAsNextContext.ts, packages/job-worker/src/playout/setNext.ts
This pull request is posted on behalf of TV 2 Norge.
This is a:
Feature
During the `onSetAsNext` callback, it is impossible to tell whether it is the user that selected the next part, or if it's a result of Sofie auto-selecting it (e.g. after a Take).
The `IOnSetAsNextContext` has a `manuallySelected` property, which will be `true`, when the part being set as next was selected by the user.
This PR affects the playout logic and Blueprints API (non-breaking addition) in the context provided to the `onSetAsNext` blueprint callback.
=> feat: add `manuallySelected` to OnSetAsNextContext

meteor/yarn.lock, packages/documentation/docs/for-developers/device-integrations/tsr-plugins.md, packages/playout-gateway/package.json, packages/playout-gateway/src/configManifest.ts, packages/playout-gateway/src/coreHandler.ts, packages/playout-gateway/src/index.ts, packages/playout-gateway/src/tsrDeviceRegistry.ts, packages/playout-gateway/src/tsrHandler.ts, packages/shared-lib/package.json, packages/yarn.lock
This pull request is posted on behalf of SuperFly
Partner to https://github.com/Sofie-Automation/sofie-timeline-state-resolver/pull/375, to update the library in sofie and utilise the new changes
=> feat: support loading TSR devices as 'plugins'

packages/webui/src/client/styles/prompter.scss, packages/webui/src/client/ui/ClockView/PresenterScreen.tsx, packages/webui/src/client/ui/Prompter/OverUnderTimer.tsx
This is a:
Bug fix
The "Presenter's Countdown screen" shows incorrect DIFF values.
The DIFF value on the Presenter screen matches the DIFF in the Rundown View header and the prompter.
The problem is that the Countdown view doesn't pull all the data from the subscription that are needed.
=> fix(Presenter Screen): Diff is showing incorrect values

packages/webui/src/client/ui/AfterBroadcastForm.tsx
This is a:
Bug fix
After Evaluation Form shows the _Send message_ option when the rundown is not looping and _Send message and Deactivate Rundown_ when rundown is looping.
The After Evaluation Form correctly shows the _Send message and Deactivate Rundown_ when the rundown is not looping and _Send message_ when the rundown is looping.
This PR affects the Rundown View/After Broadcast Evaluation Form.
We intend to finish the development on this feature in two weeks time.
=> fix(AfterBroadcastForm): shouldDeactivateRundown should be true when loop is _not_ running (SOFIE-4100)

meteor/package.json, meteor/yarn.lock, packages/meteor-lib/package.json, packages/mos-gateway/package.json, packages/mos-gateway/src/coreHandler.ts, packages/mos-gateway/src/mosHandler.ts, packages/playout-gateway/src/coreHandler.ts, packages/shared-lib/package.json, packages/yarn.lock
This pull request is posted on behalf of NRK.
* Improves some logging of mos-gateway (useful data was getting lost in winston)
* mos-connection is updated, so that receiving a message with an empty mosID is now allowed. This mitigates the error we are seeing
https://github.com/nrkno/sofie-nrk-core/pull/9
=> fix: update mos-connection for missing mosID bug fix (#9)

packages/mos-gateway/src/index.ts, packages/mos-gateway/src/mosHandler.ts
This is a:
Bug fix
If running Mos Gateway in strict mode, there is an error from Mos-connection library that `onRequestAllRunningOrders` is missing.
This is technically required, and has always been. Sofie doesn't really support the functionality itself so I'll just leave the implementation a stub for now.
No error.
Not urgent, but annoying.
=> Fix: Mos-Gateway Implement required callbacks for profile 4

meteor/package.json, meteor/yarn.lock, packages/job-worker/package.json, packages/playout-gateway/package.json, packages/playout-gateway/src/coreHandler.ts, packages/shared-lib/package.json, packages/yarn.lock
This is a: Bug fix / Feature / Code improvement 
This updates TSR and removes the remaining method calls to recently removed TSR methods.  
There are not any calls being made to these methods with sofie, they have been dead code for a while
=> fix: update tsr and remove deprecated playout-gateway methods
