- meteor/client/ui/Settings/DeviceSettings.tsx
Add button for debug logging in Media Manager tab. Tested, seems to be working as expected.
> feat: add checkbox for debugLogging in media manager

- meteor/client/lib/reactiveData/reactiveData.ts
- meteor/client/ui/RundownView/RundownNotifier.ts
- meteor/lib/collections/ExternalMessageQueue.ts
Addressed @nytamin concerns about text translation and reduced the subscription scope to studioId and rundownId.
> fix: more performant subscription based on studioId and rundownId

- meteor/client/ui/RundownView/RundownTiming.tsx
Issue was that if KAM part has display duration (based on script take point) of 0, expected duration set to 0 and that it is always first in a group, the overall expected duration of the entire group has not been accumulated yet. This pull request sets the segLineDisplayDuration (via local variable displayDuration) to the default when no other values are available.
> fix: default duration for KAM in timing group

- meteor/client/styles/_colorScheme.scss
- meteor/client/styles/notifications.scss
- meteor/client/styles/rundownSystemStatus.scss
- meteor/client/styles/systemStatus.scss
Modify css such that this warning pill:
Becomes more readable:
> Make warning text readable.

- meteor/client/ui/Settings/StudioSettings.tsx
- meteor/client/ui/Settings/components/PlayoutDeviceSettingsComponent.tsx
- meteor/server/api/playout/lookahead.ts
This fix makes lookahead respect a class from the Previous Part such that a transition can be enabled.
I've noticed that when Parts are played out of order the lookahead will "forget" what part was before the current part and it will remove the transition right before actually playing and then add it back when sending the play command. I haven't quite looked into what happens there, but I think in the current implementation of lookahead that's reasonable limitation and won't happen when parts are nicely played in order.
> fix: lookahead transitions respect prev_full class

- meteor/client/styles/shelf/dashboard-streamdeck.scss
- meteor/client/styles/shelf/dashboard.scss
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
This PR introduces support for displaying the dashboard on an Elgato Stream Deck device using a web browser renderer. I'm using this Electron-based tool: [jstarpl/stream-deck-browser](https://github.com/jstarpl/stream-deck-browser) to display the dashboard layout on the Stream Deck.
The proper formatting for the device (alignment of virtual buttons to hardware buttons) is achieved using CSS Media Queries.
> Feature: streamdeck

- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
**What is happening?**
Segment Timeline (Viewport) manipulation doesn't work since Chrome 73, when scroll events became passive.
**What should happen?**
It should be possible to manipulate the segment timeline using the mouse wheel and modifiers (alt & ctrl) or if the mouse supports horizontal wheel: using the horizontal wheel without any modifiers.
**What this PR changes?**
This has happened, because React attaches event listeners on the document root and therefore mouse wheel events on the Segment Timeline are treated as if they are scroll events. This PR removes the native react event handler and attaches the mouse wheel event handler directly to the Timeline element.
> Fix: segment viewport manipulation using scroll wheel

- Jenkinsfile
Disable to automatically push a new release for commits to master.
Automatically push a new release for commits to master.
Should be triggered manually instead.
> disable jenkins version release

- meteor/server/api/integration/rabbitMQ.ts
This PR contains two fixes solving one problem:
* Calling close on a closed AMQP connection throws an error
* Handling failure of intialization such that future initalizations do not get blocked
> Hotfix: AMQP reconnection failing

- meteor/__mocks__/helpers/database.ts
- meteor/server/api/blueprints/__tests__/cache.test.ts
- meteor/server/api/blueprints/__tests__/lib.ts
- meteor/server/migration/0_1_0.ts
- meteor/server/migration/0_25_0.ts
- meteor/server/migration/__tests__/migrations.test.ts
- meteor/server/migration/api.ts
- meteor/server/migration/databaseMigration.ts
This PR adds the feature to run system migrations before blueprint-blueprints.
It also deals with several issues that came up during implementation:
* Added tests for initial migrations
* Remove requirement of MOS-gateway. Since there are other ingest gateways that could be used, it doesn't make sense to require this one during installation.
TODO:
> System migrations

- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/lib/Settings.ts
This PR introduces an optional automatic rewind of the segment timeline when leaving a given segment.
Currently, when leaving the segment, the timeline is left in the state as-is, until the SegmentTimeline component is destroyed (when it is outside of the viewport), when the entire component is rebuilt with the scroll position at 0.
When `autoRewindLeavingSegment` setting in the public settings is turned on, the segment will be rewound after it stops being live.
> Automatically rewind segment that stopped being live

- meteor/server/api/blueprints/__tests__/context.test.ts
- meteor/server/api/blueprints/context.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/playout/playout.ts
This is bug fix for SegmentContext/PartContext in blueprints API
Segment notes have origin name set to the name of the Rundown, resulting in the label in the UI making them indistinguishable from Rundown notes. Also, they make it difficult to make out which segment a given note refers to.
This PR provides the proper contextName for SegmentContexts, using the IngestSegment.name as the context name.
> fix: warnings on segments should now have segment-sourced labels

- meteor/client/styles/rundownView.scss
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownTiming.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
This adds a copy of the live line part countdown to the top header.
There is no countdown in the header. Also, time remaining calculations are done in the SegmentTimeline component.
Adds a copy of the countdown to the top header in the RundownView. It also moves certain time remaining calculations into the RundownTiming component as well as adds a utility check for "will this part autonext". Also adds two React components to display time remaining and "will autonext" flags.
> Add a copy of live line countdown to the top header

- meteor/client/main.js
Bug fix
Registering the service worker from a non-https and non-localhost server will cause an exception that wasn't handled.
The promise is handled and protocol and hostname is checked before trying to register the ServiceWorker.
**Status**
> fix: check if loaded over https before trying to register service worker

- meteor/client/styles/systemStatus.scss
- meteor/client/ui/Status/SystemStatus.tsx
- meteor/lib/api/userActions.ts
- meteor/server/api/__tests__/userActions.test.ts
- meteor/server/api/userActions.ts
This PR adds Restart Core from status page feature
There is no way to restart Core from within the application itself.
Allows users with the developer or configure access level to restart core from the status page. Also, Core status and version number is shown on the status page.
**Status**
> Feat: restart core from status

- meteor/client/lib/ModalDialog.tsx
- meteor/client/lib/mousetrapHelper.ts
- meteor/client/lib/userAction.ts
- meteor/client/styles/modalDialog.scss
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/GlobalAdLibPanel.tsx
Bug fix
When certain kinds of hotkeys overlap (for example Rundown Arguments and Source Layer activators), the view will crash completely.
Overlapping hotkeys will not cause a crash.
Binding and unbinding hotkeys using mousetrapHelper have been generally improved.
**Status**
> fix: hotkey overlap crash

- meteor/server/api/snapshot.ts
Bug fix
Rundown layouts are not included in system snapshots.
Adds rundown layouts as an optional field in the snapshot, so as to be backwards-compatible.
**Status**
> fix: support rundown layouts in snapshots

- meteor/client/ui/RundownView/RundownTiming.tsx
This PR makes sure that an invalid part doesn't have it's duration reset to 0. The displayDuration is still reset to 0 so that invalid parts behave as they do now.
> fix: don't reset invalid part actual duration, only displayDuration

- meteor/server/api/playout/lib.ts
_Note: This PR is happily contributed from TV2 Denmark!_ 😀
This PR fixes an issue where it was not possible to "Reset Rundown" when the _first_ Part is playing.
Core threw an error "Not allowed to Next the currently playing Part"
No error thrown, rundown is reset
**Status**
> fix: bugfix: not able to reset rundown when first part was playing

- meteor/server/api/ExternalMessageQueue.ts
This PR changes what the system-status will be when there are unsent items in the externalMessageQueue.
We no longer consider these to be critical to the broadcast.
System status is BAD when there are more than 10 items on queue
System status is WARNING_MINOR when there are less than 10 items on queue
System status is WARNING_MAJOR when there are any items on queue.
**Status**
> fix: don't emit status.BAD for messages in queue. 

- meteor/lib/mediaObjects.ts
- meteor/package-lock.json
- meteor/package.json
Adds option to VT pieces to allow for media status checks to be ignored
Core assets will show a full status of meaningless issues (eg freeze frames during vignett). These are not useful or relevent to the producer and just add noise
The blueprints can tell core to skip these checks, and always say that the media is online and valid
blueprints-integration: https://github.com/nrkno/tv-automation-sofie-blueprints-integration/commit/a7fc8c8254009a14c8e1650675d18c0402395f1b
**Status**
> feat: ignore piece media status

- Dockerfile
Doing a fresh install of meteor installs 1.9, which is using node12.
This affects the version of meteor-tools installed, until meteor has been setup for our project.
The steps in the Dockerfile are not invoking a true meteor command until after the `meteor npm install` and so meteor was not being setup to the version we needed.
This meant it was trying to install our dependencies on node12, and failing.
Doing a `meteor --version` triggers meteor to setup the tools to the correct versions, allowing `meteor npm install` to run happily.
The change to the curl line may not be needed, and may not even help. But I dont see any harm in having it there too.
I don't quite understand why it broke today (perhaps it was triggered by #151 changing something for itself?) …
> fix: meteor build error in jenkins

- meteor/lib/collections/Rundowns.ts
- meteor/server/api/playout/playout.ts
This PR introduces two fixes in order to prevent a bad state where the system will keep looping between 2 parts. One is the prevention of doing a manual take shortly before an autotake and the other is to prevent agressive measures when the playout gateway reports the wrong part has started playback.
**Status**
> Hotfix for looping between 2 parts

- meteor/lib/lib.ts
- meteor/server/__tests__/codeControl.test.ts
- meteor/server/codeControl.ts
This PR fixes an issue with `asyncCollectionFindFetch` that @Julusian found, that essentially caused it to not run assynchronously at all.
There should be no functional changes.
**Status**
> fix asyncCollectionFindFetch implementation

- meteor/client/ui/Settings/components/GenericDeviceSettingsComponent.tsx
When creating "default" rows in tables, a truthy check is done on the `defaultVal` for each field before creating. This causes a problem if the default value is an empty string, 0 or false.
It uses a `!== undefined` to verify that the `defaultVal` is defined.
**Status**
> Fix: DeviceConfigManifest: creating default table rows

- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownOverview.tsx
- meteor/lib/collections/Segments.ts
Support of a new feature: "Hidden Segments".
A Segment can now be set as "hidden" in the blueprints.
A Hidden segment will not be shown in the RundownView, but will be shown in the Shelf.
This is useful for example for adding Adlibs without nessesarily having them related to a certain Segment.
> Hidden Segments

- meteor/client/styles/rundownView.scss
- meteor/client/ui/RundownView.tsx
- meteor/lib/Settings.ts
The blur border (notification that the Rundown view is unfocused) is now animated for better peripheral vision functionality.
The blur border is static.
The unfocused border is now animated.
**Status**
> feat: animated unfocused border in rundown

- meteor/server/api/playout/adlib.ts
- meteor/server/api/playout/playout.ts
Feature
Allows an adlib to indicate that it should always be queued when added to the timeline, rather than being immediately taken on air.
An example usecase is allowing the inserting of transitions as adlibs, where they may need to be created as their own part for timing calculations
to work.
> feat: Queued adlibs

- meteor/server/api/playout/actions.ts
Partner: https://github.com/nrkno/tv-automation-playout-gateway/pull/60
Remove the calls of uploadFileToAtem to playout-gateway.
Playout-gateway should internally handle ensuring the media loaded to the device is correct.
This code will trigger an upload of media based on old and incorrect data, overriding correct media with outdated ones.
The media upload process is left to playout-gateway
**Status**
> fix: dont call uploadFileToAtem as part of deviceMakeReady

- meteor/client/ui/Settings/components/MosDeviceSettingsComponent.tsx
Add option for the dontUseQueryPort property on MOS-devices, used to suppress errors when the query port is not open on the MOS server.
(I'm also adding this to the config manifest of MOS gateway)
Feel free to merge this right away after review. :)
**Status**
> dontUseQueryPort 

- meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
The "scissors" icon visibility logic is broken. It shows in situations where it shouldn't and then doesn't show when a clip is cut using IN/OUT points.
The "scissor" icon will show when `editorialDuration` is not undefined and `editorialDuration` is not equal `sourceDuration`.
**Status**
> fix: cut icon logic for marking trimmed clips

- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/client/ui/SegmentTimeline/SourceLayerItemContainer.tsx
This PR resolves an issue with `contentMetaData` not being attached to the correct object within `SourceLayerItemContainer`
Hoverscrub box doesn't show up, even if it should (mediaPreviewsUrl is set up and the MediaObject is found)
The `contentMetaData` is now placed in the correct position, where `VTRenderer` and other Piece renderers can pick it up.
**Status**
> fix: Part Instances contentMetaData broken

- meteor/client/ui/ConnectionStatusNotification.tsx
Make connection status text generation more organized and easier to localize
There is some code-based concatenation of strings in `getStatusText` that could make translations impossible into some languages (non-VSO or -SVO word-order).
The Sofie Automation Server string is translated and then used as an input to the connection status strings, allowing full localization.
**Status**
> chore: refactor connection status notification strings

- meteor/client/lib/resizeObserver.ts
- meteor/client/ui/SegmentTimeline/SegmentTimelineZoomControls.tsx
- meteor/client/ui/SegmentTimeline/TimelineGrid.tsx
- meteor/package-lock.json
- meteor/package.json
Removes a dependency on `element-resize-event` and uses ResizeObserver instead.
Sofie uses an external dependency called `element-resize-event` that emulates a resize event by using an empty `iframe` and listening to it's resize events.
Instead of using the external dependency, the `ResizeObserver` browser API is used to monitor changing display sizes of various elements. The added benefit is that `ResizeObserver` is supposed to measure the sizes of elements at a convenient time for the browser engine, so less element measurements need to be taken, thus the resize …
> feat: use ResizeObserver instead of element-resize-event

- meteor/client/ui/SegmentTimeline/Renderers/SplitsSourceRenderer.tsx
This fixes a warning about `SplitsSourceRenderer` that shows up in RundownView
A warning is produced when showing a rundown with splits:
```
Warning: `%s` uses `getDerivedStateFromProps` but its initial state is %s. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `%s`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape.
```
Proper shape of the state object is ensured by the constructor of `SplitsSourceRenderer`.
**Status**
> fix: splits constructor initial state to avoid warnings

- meteor/lib/lib.ts
- meteor/server/api/client.ts
- meteor/server/api/userActions.ts
This PR fixes a bug with the `MINIMUM_TAKE_SPAN` protection.
There is a short window of opportunity where a slow response from the DB at the right moment, when switching between two non-autonext parts, can cause a double-take to happen.
The userActions take method is now a `syncFunction`, so that only a single `take` userAction can be executed at any time for a rundownPlaylist. This should ensure that the already existing `MINIMUM_TAKE_SPAN` check can work correctly.
**Status**
> fix: make the userActions.take method be a syncFunction on a rundownPlaylist

- meteor/client/styles/tooltips.scss
- meteor/client/ui/ClipTrimPanel/ClipTrimDialog.tsx
- meteor/client/ui/ClipTrimPanel/ClipTrimPanel.scss
- meteor/client/ui/ClipTrimPanel/ClipTrimPanel.tsx
This feature adds a "reset" button feature to the Trim Clip dialog.
Removing a trim requires multiple clicks.
There is a "reset" button next to the "In", "Out" and "Duration" inputs. Resetting "in" causes the in point to be set to 0. Resetting "out" causes the out point to be cleared. Resetting "duration" causes both to be reset.
**Status**
> feat: reset in-out-duration in ClipTrimPanel

- meteor/client/ui/RundownView/RundownNotifier.ts
- meteor/lib/api/rundown.ts
- meteor/lib/collections/ShowStyleVariants.ts
- meteor/server/api/blueprints/config.ts
- meteor/server/api/blueprints/context.ts
- meteor/server/api/playout/lib.ts
- meteor/server/api/rundown.ts
- meteor/server/coreSystem.ts
This will make core validate that all the required blueprint config fields are defined for the rundown being viewed.
It is up to the blueprints to do this check. This means that every segment in the show will end up logging a warning for each missing field.
Core now does the check at the same interval as checking if the configuration has changed since the rundown has been imported. It will then present up to 2 notifications to warn of the missing fields.
This is much less repetitive and easier to read then before. Additionally, any blueprint hooks wont log the same …
> feat: add validateBlueprintConfig and notifications in the rundown view

- meteor/server/api/playout/timeline.ts
This fixes the case where an infinite is running in part A, part B overrides it briefly at the start.
During an autonext, the layer would go to the override, then back to the original infinite until the new timeline had been resolved and applied.
To fix this, we look ahead at the next part to see if the infinite is there and with and end time. If so and we are going to autonext, then we use that end time for the current part.
**Status**
> fix: infinites spanning an autonext should take the end from the next part

- meteor/client/ui/Prompter/PrompterView.tsx
This is a bugfix for a crash in the Prompter component that sometimes would happen since R19.
Certain conditions can cause the Prompter to crash, because an underlying method would throw an exception if a rundown playlist could not be found. Specific, reproduceable sequence of events was not determined, but a static code analysis was enough to pinpoint the issue.
The component doesn't crash if a Rundown Playlist cannot be found.
**Status**
> hotfix: prompter

- meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
- meteor/server/api/playout/adlib.ts
Feature
All pieces on sticky layers are sticky.
Adds an optional setting to showstyle such that adlibs are not sticky.
> feat: option for sticky items to only make 'original' pieces sticky

- meteor/lib/api/pubsub.ts
- meteor/lib/collections/ExpectedPlayoutItems.ts
- meteor/lib/collections/Parts.ts
- meteor/lib/collections/Pieces.ts
- meteor/lib/collections/Rundowns.ts
- meteor/server/api/ingest/expectedPlayoutItems.ts
- meteor/server/api/ingest/ingestCache.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/playout/actions.ts
- meteor/server/api/playout/infinites.ts
- meteor/server/api/playout/lib.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/rundown.ts
- meteor/server/api/snapshot.ts
- meteor/server/publications/expectedPlayoutItems.ts
- meteor/server/security/expectedPlayoutItems.ts
Feature
Adds a new collection called expectedPlayoutItems which is used by the blueprints to report to the Playout-gateway that a list of items (e.g. graphics) is expected to be needed soon.
In the case of the VizMSE-integration, this is used to load all of the graphics when a rundown is activated so that all graphics are preloaded by the time they are taken on-air.
> ExpectedPlayoutItems

- meteor/client/ui/Settings/StudioSettings.tsx
Feature
Adds the option "preview when not on air" to CasparCG layer mappings, allowing for the first frame of a video to be loaded on a caspar player that is about
to be taken on air (set as next).
This can be used with A/B playback to show a preview of the next clip to be played while a clip is still on-air.
> feat: Add field for CasparCG mappings previewWhenNotOnAir property

- meteor/server/api/playout/actions.ts
- meteor/server/api/playout/playout.ts
Feature
Better handling of the makeReady & standDown signals, that is sent from Core to Playout-gateway before (and after) a show.
Now makeReady is also sent upon _activation of a rundown_, not only on "prepare rundown".
Note: This should be tested by NRK before merging, to ensure the system still works as intended.
> MakeReady & StandDown

- meteor/.gitignore
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
Feature
Provides a compact view of the segments in a rundown, where segments are collapsed by default. As a segment is set as next / taken on air it expands.
This is opt-in and set by the settings `defaultToCollapsed` and `autoExpandCurrentNextSegment`
*Compact View*
> feat: auto-expanding/collapsed segments

- meteor/lib/collections/Rundowns.ts
- meteor/server/api/ingest/ingestCache.ts
- meteor/server/api/playout/lib.ts
- meteor/server/api/snapshot.ts
This PR fixes some issues with how Snapshots are handled.
The most prominent change is: When restoring a rundown from a snapshot, always restore into a new rundown-id.
> Snapshots handling

- meteor/client/ui/SegmentTimeline/SourceLayerItemContainer.tsx
- meteor/lib/mediaObjects.ts
Feature
If the source duration of a VT/Server piece is not set by the blueprints, the actual length of the clip from the mediaObjects collection is used.
> feat: Use source duration as fallback for VT

- meteor/client/lib/invalidatingTime.ts
- meteor/client/styles/shelf/dashboard.scss
- meteor/client/styles/shelf/externalFramePanel.scss
- meteor/client/ui/SegmentTimeline/SourceLayerItemContainer.tsx
- meteor/client/ui/Settings/RundownLayoutEditor.tsx
- meteor/client/ui/Shelf/AdLibListItem.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/client/ui/Shelf/ExternalFramePanel.tsx
- meteor/client/ui/Shelf/Shelf.tsx
- meteor/client/ui/Shelf/TimelineDashboardPanel.tsx
- meteor/lib/api/rundownLayouts.ts
- meteor/lib/collections/RundownLayouts.ts
- meteor/server/api/playout/infinites.ts
- meteor/server/api/playout/pieces.ts
Feature
- Improves dashboard / shelf layouts to allow for "toggling" adlibs.
- Provides a "timeline" view whereby an indicator is given of which adlibs belong to a particular piont in a show.
- Adds an option of using an "External frame" panel, that is an iframe with an API to exchange events with Sofie
Timeline view:
Adlib toggle:
> Feature: Dashboard panel improvements: timeline view, external frame

- meteor/lib/collections/Pieces.ts
- meteor/server/api/playout/infinites.ts
- meteor/server/api/playout/lib.ts
- meteor/server/api/playout/timeline.ts
This PR adds an optimization for the situation where many adlibs are played while staying in one part.
This is fixed by adding a filter in Core that removes old-and-stopped-adlibs after a while, making calculations and timeline to run faster.
* **What is the current behavior?**
System slows down to a crawl after 15-30 adlibs (we experienced this when cutting between cameras)
* **What is the new behavior?**
Adds the property "definitelyEnded" to pieces to allow for efficient trimming of pieces that no longer need to be evaluated to calculate the current state, increasing performance.
> Optimization when doing many Adlibs 

- meteor/lib/lib.ts
- meteor/server/api/ingest/mosDevice/ingest.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/rundown.ts
This PR contains some code updates for how ingest-data is handled.
It improves on how "unsynced" is determined and fixes some crucial bugs along the way.
This PR paves the path for the future "protecting primaries"-feature (that can be started on after PartInstances).
> Better Ingest-data management & unsync handling

- meteor/client/lib/ModalDialog.tsx
- meteor/client/lib/mousetrapHelper.ts
- meteor/client/lib/viewPort.ts
- meteor/client/main.js
- meteor/client/styles/modalDialog.scss
- meteor/client/styles/shelf/dashboard.scss
- meteor/client/ui/PieceIcons/Renderers/SplitInput.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/client/ui/Settings/RundownLayoutEditor.tsx
- meteor/client/ui/Shelf/AdLibListItem.tsx
- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/client/ui/Shelf/GlobalAdLibPanel.tsx
- meteor/client/ui/Shelf/Shelf.tsx
**What kind of change does this PR introduce?**
This PR features various GUI fixes and minor features:
**Minor features**
* Use both numpad enter and normal enter to accept ModalDialogs (#9b767795)
* Display rundown name if no start-time set (#4f39a852)
**Bug fixes**
* Segment viewport manipulation using scroll wheel (#2760997d)
* Segment notes: don't take up space if not present (#be78315f)
* Guard against negative width of liveline shade (#0bf16a40)
* Shelf hiding (#d23586f0)
* In-viewport detection and scrolling (#e7d9ec7b)
* Resolve issues with hotkeys in ModialDialogs (#b3fd84c0)
* Update mediaObject subscriptions for AdLibListItems and DashboardPieceButtons (#2e69fe8d)
* Check if loaded over https before trying to register service worker (#c4b98037)
* Hotkey overlap crash (#135) …
> Various GUI fixes

- meteor/client/ui/Settings/StudioSettings.tsx
- meteor/server/api/playout/adlib.ts
- meteor/server/api/playout/lookahead.ts
This PR adds a setting for "lookahead maxSearchDistance".
This limits how far ahead the lookahead will look for content. Improving performance in long running shows.
> Optimization: Lookahead max search distance

- meteor/client/lib/ModalDialog.tsx
- meteor/client/styles/modalDialog.scss
- meteor/client/ui/ClipTrimPanel/ClipTrimDialog.tsx
- meteor/lib/api/peripheralDevice.ts
- meteor/server/api/ingest/mosDevice/actions.ts
- meteor/server/api/userActions.ts
This implements validation of trimming operations through MOS by adding a using the new mos gateway feature where item changes can be validated in later roFullStory by sending a diff of the changes.
The promise for the change of parameters in an Item resolves as soon as an ACK is received from the NRCS. Some implementations will not change the Item immediately, before sending the ACK, but at a later time, due to an internal locking and queuing mechanism.
The change request will be validated against incoming messages and the promise will only resolve once a MOS …
> feat: validate in- & out-point change in MOS

- meteor/server/api/blueprints/postProcess.ts
- meteor/server/api/playout/pieces.ts
- meteor/server/api/playout/timeline.ts
This fixes a bug introduced in the TV2 contributions. They have fixed this in a different way in their fork, but the changes did not make it into the original batch of PRs.
This was causing some adlib pieces to think they start at 0 within the part, which causes the timings in them to be off. 
**Status**
> fix: some pieces starting at non-zero time being forced to zero-time

- meteor/client/lib/documentTitle.ts
- meteor/client/ui/ConnectionStatusNotification.tsx
- meteor/client/ui/RundownView.tsx
This is a new feature to set the title of the tab/window to the name of the currently open rundown. Also the theme-color is changed for RundownViews to black.
The title of the tab/window is the same for all Sofie views.
With the current setup, if multiple views of Sofie are open, it's impossible to differentiate between them. With this change, it's now clear, at least for the RundownViews, which Rundown is open in every window. I didn't make the other views change the title, because that's a bit more complicated due to their general tree structure, so a more informed change is needed there.
**Status**
> feat: show rundown name in document title

- meteor/client/lib/mousetrapHelper.ts
This PR adds additional key aliases for NOB keyboard. Some keys are prefixed with `nb` to make it easier.
New keys aliases:
* `nbPlus` - this is the `+` key that follows the number keys in the main keyboard area
* `nbBackslash` - this is the `\` key, followint the `+` and the number keys 
* `å` - this is the key next to the `P` key
* `¨` - this is the key next to the `å` key, in the same row as the `P` key
* `ø` - this is the key next to the `L` key
* `æ` - this is the key next to the `ø` key, in the same row as the `L` key
* `'` - this is the key next to the `æ` key, in the same row as the `L` key
* `nbPeriod` - this (`.`) is the key between …
> feat: additional NB keyboard aliases

- meteor/client/lib/viewPort.ts
- meteor/client/styles/rundownView.scss
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.scss
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
- meteor/lib/collections/Parts.ts
- meteor/lib/collections/Segments.ts
This PR adds support for:
These are small human-readable unique strings that show the relation between a segment in Sofie and the data in the newsroom control system. The identifiers must be added through the blueprints and will then be rendered as a pseudo element such that the position and styling can be customised through custom CSS.
These are similar to segment identifiers in that they are showing a relation between a part in Sofie and data in the NRCS. They achieve this on a more atomic level though. These identifiers are rendered in both the Timeline view as well as clickable items in the segment header. Where clicking on an identifier in the segment header moves the timeline to that part.
_Note: this PR modifies the **scrollToPart** and **scrollToPartInstance** to also scroll the …
> feat: segment and part identifier

- meteor/.prettierignore
- meteor/lint-staged.config.js
- meteor/package.json
This fixes a workflow bug where lint-staged could produce commands that are too long for the Windows shell to work.
The lint-staged can fail if there are a lot of files staged. `meteor npm run quickformat` won't work at all on Windows.
**Status**
> chore: fix lint-staged on Windows

- meteor/client/ui/Settings/RundownLayoutEditor.tsx
The Rundown Layout editor has duplicated widgets, my guess is that it came from a malformed merge of features contributed by TV2.
Duplicated widgets are removed.
**Status**
> fix: duplicated rundown layout editor widgets

- meteor/client/lib/EditAttribute.tsx
- meteor/client/ui/Settings/ConfigManifestSettings.tsx
- meteor/client/ui/Settings/components/ConfigManifestEntryComponent.tsx
- meteor/lib/api/deviceConfig.ts
Adds the MULTILINE_STRING config manifest entry type, allowing devices and blueprints to request input that may include newlines. Each new line in the text field is stored as a string in an array for strings. IE:
```
Hello
World
```
Is stored as `["Hello", "World"]`.
This entry type is useful for devices such as Viz which need to send plain-text commands that are sent as one batch, but as separate messages; represented to the user as multiple lines of commands to be sent together.
Requires https://github.com/nrkno/tv-automation-sofie-blueprints-integration/pull/66
Requires https://github.com/nrkno/tv-automation-server-core-integration/pull/31
**Status**
> feat: Multiline config manifest entry + device manifest entry

- meteor/client/lib/rundown.ts
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownTiming.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/lib/Rundown.ts
- meteor/lib/Settings.ts
Adds the core setting `defaultDisplayDuration` (default value 3000) to make this hard-coded value configurable. This allows different Sofie installations to set a different "default duration" of parts that have no timing information set.
Although this would be a 1-line difference between the NRK version of Sofie and any fork, this setting would allow this entirely cosmetic change to be adjusted using pre-built Sofie images, and would allow different installations within one organisation to use different default durations.
The motivator for this setting is that the origin fork for this feature branch uses a default duration of 4 seconds for parts.
**Status**
> feat: Default display duration setting

- meteor/client/lib/EditAttribute.tsx
- meteor/client/styles/editAttribute.scss
- meteor/client/ui/Settings/ConfigManifestSettings.tsx
Adds the JSON config manifest entry type, which is automatically checked to be valid JSON.
An example use case is to allow Sofie admins to add a new DVE layout by building the layout on an ATEM and using the atem connection library to pull the JSON representation of this layout. They can then copy the JSON into showstyle settings, where it will be validated to prevent copying errors.
Requires https://github.com/nrkno/tv-automation-sofie-blueprints-integration/pull/65
**Status**
> feat: JSON config manifest entry type

- meteor/client/ui/RundownView.tsx
- meteor/lib/Settings.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/userActions.ts
This PR adds the meteor setting `allowRundownResetOnAir`, which allows the user to reset a rundown playlist while it is active.
This is useful for use cases where a single rundown is being reused continually across many shows - the rundown can be replaced with new data from the NRCS and the user can use the reset shortcut to jump to the top of the rundown and ensure a safe state.
The setting is disabled by default, so by default resets will not be allowed while a playlist is active.
**Status**
> feat: Allow rundown reset while on-air

- meteor/server/api/playout/pieces.ts
Fixes a bug where an adlib such as an infinite VT piece with an expectedDuration set would have its duration set, causing the infinite to become stopped when moving to the next part. This also stops duration being set on the queued adlibs. The part will inherit the expected duration from the adlib, but if the user goes beyond the expected duration then they will not end up cutting to black / falling back to the baseline due to the piece stopping.
**Status**
> fix: Don't set adlib piece duration if queued or infinite

- meteor/client/ui/Shelf/TimelineDashboardPanel.tsx
This fixes a bug where the Timeline dashboard panel would crash due to missing props when the component was mounted.
**Status**
> fix: Timeline dashboard panel crashing due to missing props

- meteor/client/ui/Shelf/ShelfDashboardLayout.tsx
Fixes a bug where adLib regions were not being displayed in dashboard layouts.
**Status**
> fix: Add adlib region to dashboard panel

- meteor/client/ui/ConnectionStatusNotification.tsx
- meteor/lib/collections/CoreSystem.ts
- meteor/server/__tests__/api/serviceMessages/postHandler.test.ts
- meteor/server/__tests__/api/serviceMessages/serviceMessagesApi.test.ts
- meteor/server/api/serviceMessages/postHandler.ts
- meteor/server/api/serviceMessages/serviceMessagesApi.ts
- meteor/server/migration/X_X_X.ts
This is a bugfix for a typing/database serialization issue with Service Messages.
At some points, there will be an Error message logged to console:
```TypeError: message.timestamp.getMilliseconds() is not a function```
No error message should be thrown. Existing ServiceMessages should be upgraded by migrations.
**Status**
> fix: service messages types

- meteor/lib/api/peripheralDevice.ts
- meteor/server/cronjobs.ts
* **What kind of change does this PR introduce?** 
Bug fix:
There are a lot of timeouts on the restartCasparCG cronjobs currently. this PR aims to fix that issue by increasing the timeout from the default 1s to 10s.
**Status**
> Fix: timeout errors

- meteor/i18n/template.pot
- meteor/package-lock.json
- meteor/package.json
- meteor/scripts/extract-i18next-pot.js
This PR removes the dev dependency on `i18next-extract-gettext` and uses an internal script instead.
The `i18next-extract-gettext` package was unmaintained and had some very outdated dependencies that caused our dependency validation checks to fail resulting in a permanent failed check state for all commits.
I have copied the contents of the `i18next-extract-gettext` and used new dependencies. I have replaced the `minimist` package as this wasn't used by any other dependency and replaced it with `yargs` that was already used by a couple of other dependencies.
* …
> chore: own i18next extract gettext

- meteor/server/api/__tests__/rundownLayouts.test.ts
- meteor/server/api/rundownLayouts.ts
This adds more automated tests for Rundown Layouts API, specifically HTTP endpoints.
HTTP endpoints are not covered by automated testing.
Rundown Layouts API have 93.51% test coverage.
**Status**
> chore: test rundown layouts more

- meteor/server/DatabaseCache.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/playout/lib.ts
Fixes a bug where `refreshParts` would cause a data race and crash.
The `_initialize` function is called once for every part that is being refreshed.
The `_initialize` should be called once per segment that is affected by the refresh. There is also a lock placed on `_initialize` so that subsequent calls wait for previous to finish executing to avoid data races.
CC @Julusian 
**Status**
> fix: race condition in refresh part function

- README.md
- meteor/client/styles/shelf/dashboard-streamdeck.scss
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/Shelf/BucketPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/client/ui/Shelf/RundownViewBuckets.tsx
- meteor/client/ui/Shelf/Shelf.tsx
This PR creates a feature for displaying bucket adlibs in auxiliary screens, like Stream Decks.
If buckets are created, a Stream Deck display will be malformed.
There are now url parameters for controlling displaying of Buckets and the Inspector in a Detached Shelf. If needed, these
components can be displayed or hidden using the following additional url arguments:
| Query parameter                     | Description                                                             |
| ----------------------------------- | …
> feat: streamdeck buckets

- meteor/client/ui/Shelf/AdLibListItem.tsx
- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/AdLibRegionPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
This PR includes a number of changes to allow adLib actions to display and be executed withing dashboard layouts.
Changes include:
- Copying tags for adLib actions
- Fixed a bug where two memoizedIsolatedAutorun functions had the same name but different return types causing dashboards to crash
- Call the correct user action when taking an adLib action from a dashboard
- Sort adLibs and actions together according to rank
**Status**
> Adlib actions in dashboard

- meteor/client/lib/viewPort.ts
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
* **What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Does not use a hard-coded value for Header height, but instead attempts to measure it from the DOM.
* **What is the current behavior? (You can also link to an open issue here)**
The header height is a hard-coded constant, thus causing some problems with Follow On Air (broadly speaking).
The height of the header is measured when it's first used, allowing customizations of the header to not affect "Follow On Air".
* **Other Information:**
Original author @jstarpl 
**Status**
> fix: measure HEADER_HEIGHT value for viewPort intersection and scrollTo

- meteor/.meteor/packages
- meteor/.meteor/versions
- meteor/__mocks__/_setupMocks.ts
- meteor/__mocks__/meteor-elastic-apm.ts
- meteor/client/ui/Settings.tsx
- meteor/client/ui/Settings/SystemManagement.tsx
- meteor/lib/__tests__/lib.test.ts
- meteor/lib/collections/CoreSystem.ts
- meteor/lib/lib.ts
- meteor/server/DatabaseCache.ts
- meteor/server/DatabaseCaches.ts
- meteor/server/api/asRunLog.ts
- meteor/server/api/blueprints/__tests__/context.test.ts
- meteor/server/api/blueprints/__tests__/postProcess.test.ts
- meteor/server/api/blueprints/context/context.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/playout/actions.ts
- meteor/server/api/playout/adlib.ts
- meteor/server/api/playout/infinites.ts
- meteor/server/api/playout/lib.ts
- meteor/server/api/playout/lookahead.ts
- meteor/server/api/playout/pieces.ts
- meteor/server/api/playout/take.ts
- meteor/server/api/playout/timeline.ts
- meteor/server/api/snapshot.ts
- meteor/server/api/userActions.ts
- meteor/server/coreSystem.ts
- meteor/server/publications/system.ts
- meteor/server/security/collections.ts
- meteor/server/typings/meteor-kschingiz-elastic-apm.d.ts
This PR adds optional monitoring through Elastic APM if a host is specified through the environment variable "APM_HOST". Optionally the secretToken can be supplied through the "APM_SECRET" env variable.
This also includes settings in the UI for enabling / disabling the monitoring and setting the trace resolution. A trace resolution of 1 will trace all calls but will make the execution significantly slower. A trace resolution of -1 will only report transaction times but none of the other traces. Performance will then be similar to not having any tracing.
**Status**
> feat: elastic APM tracing

- meteor/server/DatabaseCache.ts
- meteor/server/DatabaseCaches.ts
- meteor/server/api/asRunLog.ts
- meteor/server/api/playout/actions.ts
- meteor/server/api/playout/adlib.ts
- meteor/server/api/playout/infinites.ts
- meteor/server/api/playout/lib.ts
- meteor/server/api/playout/lookahead.ts
- meteor/server/api/playout/pieces.ts
- meteor/server/api/playout/take.ts
- meteor/server/api/playout/timeline.ts
- meteor/server/api/profiler.ts
- meteor/server/api/userActions.ts
- meteor/server/coreSystem.ts
This wraps any calls to the APM Agent such that we will only make calls to `Agent` if APM is currently enabled on the system. This is because we have seen evidence of these Agent calls taking a lot of time, even if APM is not connected - particularly in places like `savePreparedChangesIntoCache` where we spend time looping over a lot of object.
**Status**
> Fix: APM Slowdown

- meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
- meteor/lib/collections/PieceInstances.ts
- meteor/lib/rundown/__tests__/infinites.test.ts
- meteor/lib/rundown/infinites.ts
- meteor/server/api/__tests__/peripheralDevice.test.ts
- meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts
- meteor/server/api/blueprints/context/adlibActions.ts
- meteor/server/api/peripheralDevice.ts
- meteor/server/api/playout/__tests__/__snapshots__/api.test.ts.snap
- meteor/server/api/playout/adlib.ts
- meteor/server/api/playout/pieces.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/playout/take.ts
What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This ensures that when adlibs are executed in rapid succession, we ensure that any adlibs that didnt get de-nowified (due to not having a chance to be played) get disabled, so they dont try to play later
When we run an adlib if another gets run soon after, the first may not get played out. But it gets left with a `start: 'now'` so at the next updateTimeline it may start playing
When we get the timelineTriggerTime callback from playout gateway, any adlibs inserted before the one being de-nowified get disabled.
Also, the prune pieces logic was not ignoring disabled pieces …
> fix: ensure older adlibs that never started dont play again later

- meteor/lib/rundownNotifications.ts
This PR is a bug fix for media issues notifications not appearing in the Notification Center.
Notifications with missing media etc. are not present in the Notification Center.
The bug is fixed by changing `rundownId` to `startRundownId` in Pieces selector in `getMediaObjectIssues` function.
**Status**
> fix: Media object status notifications not appearing

- meteor/server/api/blueprints/__tests__/postProcess.test.ts
- meteor/server/api/blueprints/postProcess.ts
Removes null checking from blueprints post processing functions where the function signature types does not allow for null items in input arguments.
> chore(refactor): remove superfluous null checking

- meteor/client/ui/TestTools/Timeline.tsx
- meteor/lib/__tests__/lib.test.ts
- meteor/lib/__tests__/timeline.test.ts
- meteor/lib/collections/Timeline.ts
- meteor/lib/rundown/pieces.ts
- meteor/lib/timeline.ts
- meteor/server/api/__tests__/peripheralDevice.test.ts
- meteor/server/api/blueprints/__tests__/postProcess.test.ts
- meteor/server/api/blueprints/postProcess.ts
- meteor/server/api/manualPlayout.ts
- meteor/server/api/peripheralDevice.ts
- meteor/server/api/playout/__tests__/__snapshots__/playout.test.ts.snap
- meteor/server/api/playout/__tests__/__snapshots__/timeline.test.ts.snap
- meteor/server/api/playout/lookahead.ts
- meteor/server/api/playout/pieces.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/playout/timeline.ts
- meteor/server/api/testTools.ts
- meteor/server/migration/0_25_0.ts
- meteor/server/migration/deprecatedDataTypes/1_12_0.ts
- meteor/server/publications/timeline.ts
With the move to store `TimelineComplete` in the database, the individual objects don't need a studioId defined, or to have the secondary _id field. _id was kept as a guaranteed system unique copy of id to avoid data collisions if multiple studios were in a single sofie instance. This means that id can be left to be for the timeline and only needs to be unique within a timeline
This removes those two properties as they have no longer have a benefit
**Status**
> chore: remove old properties from TimelineObjGeneric

- meteor/server/api/playout/lib.ts
- meteor/server/api/snapshot.ts
This PR adds the `asRunLog` into RundownPlaylistSnapshots, to help with future troubleshooting.
I specifically DONT restore the asRunLog when restoring, since that is a log of what the system has done, so it should not be polluted by restoring snapshots.
**Status**
> asRunLog in snapshot

- meteor/client/ui/Shelf/DashboardPanel.tsx
Sticky hotkeys are treated as a kind of virtual adLib in `fetchAndFilter`, so get evaluated when we loop over `rundownBaselineAdLibs` in the dashboard. The block of code removed by this PR caused the hotkey to be registered twice as we have already dealt with sticky pieces in `fetchAndFilter`.
**Status**
> fix: Don't register sticky piece hotkeys twice in dashboard

- meteor/lib/api/peripheralDevice.ts
- meteor/server/api/integration/media-scanner.ts
- meteor/server/api/peripheralDevice.ts
This PR adds a `clearMediaObjectCollection` method to the `PeripheralDeviceAPI`. This method allows removing documents from the MediaObjects collection, where the given `collectionId` and the `studioId` of the device match.
* **What is the current behavior?**
There is no way to empty the MediaObjects collection other than removing each document explicitly.
The `clearMediaObjectCollection` removes all Media Objects where the given `collectionId` and the `studioId` of the requesting device match.
This can be used e.g. by the Playout Gateway to manage MediaObjects used for reporting statuses of Viz elements.
**Status**
> feat: Add method to remove MediaObjects with specific collectionId

- meteor/client/lib/clientAPI.ts
- meteor/client/lib/dev.ts
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx
- meteor/client/ui/Status/SystemStatus.tsx
- meteor/lib/api/client.ts
- meteor/lib/api/peripheralDevice.ts
- meteor/lib/constants.ts
- meteor/server/api/__tests__/client.test.ts
- meteor/server/api/client.ts
- meteor/server/cronjobs.ts
This PR adds timeoutTime to callPeripheralDeviceFunction, so that it's easier to specify custom timeouts.
Along with this, it fixes a timeout issue where when calling 'casparcgRestart'.
**Status**
> Fix: call functions with custom timeout

- meteor/server/api/playout/adlib.ts
Before, sourceLayerOnPartStop would stop all pieces that it could find on a given source layer. The expected behavior is to stop only the currently playing pieces.
All pieces on a given source layer are stopped. As a result, pieces with effective negative length (with enable: X, and userDuration.end: Y, X > Y) would be set.
The method filters the pieces resolvedStart value to only mutate pieces that should be currently playing.
**Status**
> fix: ensure that the piece is actually playing in sourceLayerOnPartStop

- meteor/client/styles/rundownView.scss
- meteor/client/ui/App.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.scss
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/lib/rundown/infinites.ts
- meteor/server/api/ingest/expectedPlayoutItems.ts
- meteor/server/api/playout/infinites.ts
A variety of fixed are included in this PR:
- Copy adLibSourceId to continuation pieces for an infinite
- Fixes a bug where continuation pieces of an infinite would not have the adLibSourceId copied to them, which is required for "toggling" and infinite in dashboards.
- chore: use cache for expected playout items for adLibs
- Previously this would make a direct database call, rather than the cache. This has no performance benefit right now, but is more consistent and may mean that a performance improvement is seen in the future with continued work on the caching system.
- fix: Standalone shelf route
- The routing for standalone shelf views had been lost at some point, this restores the missing route.
- …
> Contribute: Various fixes from TV 2

- meteor/lib/lib.ts
- meteor/server/api/systemTime/systemTime.ts
Instead of always setting systemStatus to ERROR, only show it as a warning if a previous setting of time was successful.
This means that if the time-retrieval fails on initial startup, it'll show as an ERROR.
But if it fails later, it'll show as a warning.
**Status**
> fix: Warning, not Error on failed NTP-time update

- meteor/client/ui/ClipTrimPanel/ClipTrimDialog.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownNotifier.tsx
- meteor/client/ui/RundownView/RundownSystemStatus.tsx
- meteor/client/ui/Settings/ConfigManifestSettings.tsx
the i18n-extract-pot script does apparently only want javascript in the i18n expressions.
I got errors like Unable to parse code "{ nrcsName: this.props.firstRundown?.externalNRCSName || 'NRCS' }"
**Status**
> fix: downgraded i18n expressions to not use any fancy typescript

- meteor/client/ui/RundownView.tsx
This is a new feature for confirming that a snapshot has been taken.
If taking the snapshot takes a short amount of time (the way it usually does), no confirmation message is shown.
There should be a confirmation message shown after the snapshot is taken either using a shortcut, the context menu or from the support panel.
**Status**
> feat: show message after manual snapshot

- meteor/CHANGELOG.md
- meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
- meteor/package-lock.json
- meteor/package.json
SourceDuration markers (shown when a Piece is longer than it's source content) aren't shown.
SourceDuration markers are now shown on all Pieces.
As a result of the refactoring, a simple "infinite piece" check was replaced with a requirement of the Piece's lifetime to be other than "WithinPart". As a result, most of the Piece source duration markers were gone.
**Status**
> fix: restore sourceDuration display on all Pieces

- meteor/server/api/blueprints/config.ts
- meteor/server/api/blueprints/context/context.ts
- meteor/server/mockData/rundownData.ts
Bug fix
When a new blueprint is uploaded, the config cache is not cleared. This means that the blueprint can be given a stale cache that does not match the typings it expects.
Whenever the blueprint is modified, the relevant caches are cleared too.
Additionally some other lifecycle bits are handled, such as clearing caches for removed documents, and handling some less likely property changes
**Status**
> fix: clear the blueprint config caches when the blueprint is updated

- meteor/client/lib/EditAttribute.tsx
- meteor/client/styles/editAttribute.scss
- meteor/client/ui/Settings/StudioSettings.tsx
- meteor/lib/collections/Studios.ts
- meteor/lib/collections/Timeline.ts
This PR adds some additional functionality to the routeSets.
Mainly, it allows "no layer" to be routed into "some layer". This means that a user should be able to define ALL layer mappings in routeSets, should that be desireable.
**Status**
> RouteSets: allow "no layers" be routed into "some layers"

- meteor/client/lib/switchboardIcons.tsx
- meteor/client/styles/statusbar.scss
- meteor/client/styles/supportPanel.scss
- meteor/client/ui/RundownView/RundownRightHandControls.tsx
- meteor/client/ui/RundownView/SwitchboardPopUp.tsx
- meteor/client/ui/Settings/StudioSettings.tsx
This is a chore implementation of a change of the name of the "Route Sets".
The panel in the Rundown View is named "Route Sets", the same as the backend feature is called.
The panel (and all of it's components) are now renamed to Switchboard.
**Status**
> chore: rename Route Sets panel to Switchboard

- meteor/client/ui/RundownView.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/lib/lib.ts
This is a new feature
State of infinites across all segments is correctly shown only on page load and in current segment
The change causes all Segments to update when infinites are cropped/inserted, but should not add additional re-renders beyond that.
**Status**
> feat: show the state of infinites in all segments depending on playback

- meteor/client/lib/notifications/NotificationCenterPanel.tsx
- meteor/client/lib/notifications/notifications.ts
- meteor/client/styles/rundownView.scss
- meteor/client/styles/shelf/inspector.scss
- meteor/client/styles/shelf/shelf.scss
- meteor/client/ui/RundownView/RundownDividerHeader.tsx
- meteor/client/ui/RundownView/RundownNotifier.tsx
- meteor/lib/collections/RundownPlaylists.ts
This is a new feature/improvement
The Rundown View uses a simple rundown divider, with just the name of the rundown visible.
This uses a new Rundown Divider Header that shows additional information about the rundown:
**Status**
> feat: improved rundown divider

- .circleci/config.yml
CI config fix
> On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow.
> 
> Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.
> 
> We …
> chore(circleci): add auth params for pulling images

- meteor/lib/collections/PeripheralDevices.ts
- meteor/server/api/peripheralDevice.ts
A small feature
Devices can't modify their names, its set on first connection then won't change.
The the user hasn't modified the name, it'll be updated to the device name whenever the device reconnects.
**Status**
> fix: PeripheralDevice name fix

- meteor/client/styles/_itemTypeColors.scss
- meteor/client/styles/rundownView.scss
- meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
- meteor/client/ui/SegmentTimeline/Renderers/VTSourceRenderer.tsx
- meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
Bug fix
In some situations, the "time overflow" label may not be legible, as it overlaps with the left-anchored label (usually, the Piece name)
Some fixes to ensure that the left-anchored label has a set `max-width` as well as styling improvements to make the "time overflow" label more prominent.
**Status**
> fix: ensure visible overflow time label on Pieces

- meteor/lib/api/peripheralDevice.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/peripheralDevice.ts
Adds the `dataSegmentGet` peripheral device method, which returns an ingest segment reference by external Id. It is based on the existing `dataRundownGet` method. This allows devices like the iNews gateway to fetch the cached ingest data from core for an individual segment to compare against before sending any updates.
Requires https://github.com/nrkno/tv-automation-server-core-integration/pull/35
**Status**
> Feat: dataSegmentGet peripheral device method

- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/rundown.ts
Cleans up segments from `ingestDataCache` when `dataSegmentDelete` is recieved.
The cached ingest data for a segment remains after a segment is deleted from the NRCS.
The ingest data will be cleaned up.
**Status**
> fix: Remove deleted segments from ingestDataCache

- meteor/client/lib/uncaughtErrorHandler.ts
- meteor/package-lock.json
This PR adds an ignore for the "ResizeObserver loop limit exceeded" error, to reduce noise in the logs.
The error is emitted for me when use `hover` feature of `rc-tooltip`. No issues in GUI are observed.
According to https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded the error is benign and can be ignored.
**Status**
> fix: ignore "ResizeObserver loop limit exceeded" errors

- meteor/client/styles/rundownView.scss
- meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
- meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
A change of UX
When an output group is collapsed, hoverscrub is disabled.
The hoverscrub should always be available, regardless of collapsed state. Also, when an output group is collapsed and it only has a single source layer present, the items in that layer will no longer span the entire height of the output group, but instead show up using only half of the height.
**Status**
> feat: show inspector on collapsed layers

- meteor/client/styles/rundownView.scss
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownDividerHeader.tsx
- meteor/package-lock.json
This is a bugfix/feature change.
In the Rundown View, only the Playlist name is displayed.
Now, the name of the rundown containing the Current Part (or the next, if no current) is shown, with the playlist name appended to it:
If there is only a single rundown of the same name as the playlist, we fall back to existing behavior.
**Status**
> fix: current rundown name

- meteor/__mocks__/_setupMocks.ts
- meteor/__mocks__/tracker.ts
- meteor/client/lib/invalidatingTime.ts
- meteor/client/lib/rundown.ts
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
- meteor/lib/Rundown.ts
This is a fix/improvement.
When a PartInstance is instantiated, it may be that it's PieceInstances take a little bit to stream into the Client. In order to avoid an empty Part, the GUI keeps a Part unupdated for a little while, until the PieceInstances stream in. There may unfortunately be a little bit of a jank at the Segment level.
The simulation of the PieceInstances is now moved to the `RundownUtils.getResolvedSegment` and it's internal functions. When using a simulation of a PartInstance's contents, a reactive dependency is registered to force the segment to be …
> fix: better part instance simulation

- meteor/server/api/ingest/expectedPlayoutItems.ts
This PR fixes a performance issue related to updating ExpectedPlayoutItems, that is done in `updateExpectedPlayoutItemsOnRundown`, called at the end of the ingest methods.
`getAllPiecesFromCache` and `getAllAdLibPiecesFromCache`, performing `findFetch` on the cached collections, are executed for every Part, which makes the whole process extremely slow for long rundown because of the need for iterating over all the Pieces and AdlibPieces multiple times. O(m x n)
Pieces and AdLibPieces are fetched and grouped by their `startPartId` or `partId`. O(n)
* **Other …
> fix: Ingest performance in updateExpectedPlayoutItemsOnRundown

- meteor/client/ui/RundownView.tsx
- meteor/lib/api/__tests__/client.test.ts
- meteor/lib/api/client.ts
- meteor/lib/api/playout.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/userActions.ts
When no Piece can be found to be disabled/undo-disabled, the method will throw a Meteor.Error
Instead of throwing an Error in a situation that can just regularly happen during normal operation, the method shall now return a `ClientResponseError` object and the GUI will check for that object and error code and show a custom message with just "Warning" level of criticality, instead of showing this as a Critical Error level of notification.
This PR also adds some tests for the ClientAPI functions to check that it doesn't …
> fix: return clientResponseError when normal operations instead of throwing in disableNextPiece

- meteor/client/lib/localStorage.ts
- meteor/client/lib/notifications/NotificationCenterPanel.tsx
- meteor/client/lib/notifications/notifications.ts
- meteor/client/ui/RundownList/RundownListItemView.tsx
- meteor/client/ui/RundownList/RundownPlaylistUi.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownNotifier.tsx
- meteor/client/ui/Status/MediaManager.tsx
- meteor/client/ui/Status/SystemStatus.tsx
This PR hides / disables a number of buttons & functions for users that doesn't have studio permissions.
Most notable are:
* Buttons in Notifications are now disabled
* Reordering (dragging) of rundowns is now disabled
* Device-buttons in status view are hidden
**Status**
> fix: Hide/disable buttons for user without studio permissions

- meteor/lib/collections/PartInstances.ts
- meteor/server/api/playout/take.ts
- meteor/server/api/playout/timeline.ts
A transition on a part can delay pieces inside that part. When leaving the part the overlap with the next part is calculated, during said calculation we need to consider the transition properties such that the timing of the pieces will remain correct. In order to do this without looking at the previous previous part we should save these transition properties on the part instances.
This PR changes:
* Save the transition properties on the part instance during a take
* Consider the transition properties during transformation from the _previous_ part to timeline
> fix: evaluate transition properties when leaving part

- meteor/client/styles/_itemTypeColors.scss
- meteor/client/styles/defaultColors.scss
- meteor/client/ui/PieceIcons/Renderers/SplitInput.tsx
- meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
- packages/blueprints-integration/src/content.ts
This adds the "LOCAL" source layer type, which can be used to represent sources that are not controlled by Sofie but are available and controlled within the gallery e.g. delayed playback (EVS in this case), telestrator etc. This creates a visual distinction for sources that are often treated like cameras / live inputs but don't fit into either of those categories and may be controlled by an operator within the gallery. Below is a screenshot of what the current colour chosen for this layer looks like.
**Status**
> Feat: Local source layer type

- meteor/client/lib/rundown.ts
- meteor/client/ui/RundownView/RundownTiming/SegmentDuration.tsx
- meteor/client/ui/SegmentTimeline/SegmentContextMenu.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/lib/Rundown.ts
- meteor/lib/rundown/infinites.ts
- meteor/package-lock.json
- meteor/server/DatabaseCache.ts
- meteor/server/DatabaseCaches.ts
- meteor/server/api/__tests__/DatabaseCaches.test.ts
- meteor/server/api/playout/playout.ts
There have been a couple of issues with Disable/Undo Disable functionality:
1. First of all, the GUI would not show disabled pieces, because shared backend-fronted methods used by getResolvedSegment() for processing Piece Instances would filter them out, because backend doesn't care about disabled pieces. 
2. In some conditions, when trying to undo-disable a Piece, the Piece would not be found, because the method would end too early due to it breaking out of a loop too quickly.
3. An error was being printed out if no piece do be disabled/re-enabled was found, because a cache was created, but - since no …
> fix: disable & undo disable doesn't work, hides Pieces from timeline or throws errors

- meteor/client/ui/Prompter/controller/joycon-device.ts
- meteor/package-lock.json
Better parsing of gamepad names, to match a broader set of indicators.
Only matches a specific ID, which turns out to not be the only possible outcome when connecting.
Matches a broader and more common part of the ID, which will catch both variants that we have experienced.
**Status**
> fix: prompter generic gamepad

- meteor/server/codeControl.ts
This PR adds a check in the syncFunction execution which checks how long it has waited for other syncFunctions to complete before starting executing.
If the wait is too long, a message with the functions it waited on is logged as a warning.
**Status**
> Fix: syncfunction emit warning when waiting

- meteor/client/styles/rundownView.scss
- meteor/client/ui/FloatingInspectors/NoraFloatingInspector.tsx
Adds checking of viewport boundaries for hover preview, and flips the preview location relative to the cursor to prevent going out of bounds.
Hover preview can be partially outside of the viewport and the graphics element is not on screen
**Status**
> Fix: graphics hover preview stays in viewport

- meteor/server/api/playout/timeline.ts
- packages/blueprints-integration/src/timeline.ts
Adds a timeline class that is added to the timeline when the rundown is active but no part has been taken yet. This allows blueprints developer to add special behavior for this state.
**Status**
> feat: special timeline class for when the first part hasn't been taken

- meteor/client/styles/countdown/overlay.scss
- meteor/client/styles/rundownView.scss
- meteor/client/ui/ClockView/OverlayScreenSaver.tsx
- meteor/client/ui/RundownView/RundownTiming/CurrentPartRemaining.tsx
- meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
- meteor/client/ui/SegmentTimeline/Renderers/SplitsSourceRenderer.tsx
- meteor/client/ui/SegmentTimeline/Renderers/VTSourceRenderer.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
- meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
This is a new feature
There is no countdown displayed to the end of content (freeze frame for clips).
This PR adds a feature where if:
* On a On Air Part (current part)
* A Piece is currently On Air (so it should have started and hasn't ended yet)
* Has a defined `content.sourceDuration` property (this info may also be injected from a MediaObject, if not set by the blueprints)
* And either: 
* The Part will Auto-Next, but the end of Piece content is before the end of Part
* The Part will not Auto-Next and the difference between expected end of Part (based on …
> feat: piece freeze frame countdown

- meteor/server/api/blueprints/context/adlibActions.ts
- packages/blueprints-integration/src/context.ts
Allows for getting the part metadata for a piece found via findLastPieceOnLayer
feature
During an adlib-action, it is not possible to get the PartInstance for a PieceInstance returned from `findLastPieceOnLayer`. For the nrk case, this is a problem as any 'primary' piece simply states it was primary in its metadata, and the part metadata should be referenced for the properties needed to regenerate it.
This means it is not possible to regenerate the piece as a new piece for the current part (ie, a lazy generated adlib piece) without copying the same properties into the pieceMetadata causing the piece type to get even heavier
* …
> feat: add getPartInstanceForPreviousPiece method to ActionExecutionContext

- meteor/lib/collections/PartInstances.ts
- meteor/server/DatabaseCaches.ts
- meteor/server/api/rundown.ts
This PR improves performance by preventing too many partInstances from being fetched by the GUI and into the cache
When parts that were played back are removed, their partInstances stay in the database and are still fetched into the cache and by the GUI. In a workflow where one rundown is reused, and segments are inserted and removed multiple times, it causes the number of processed partInstances to unnecessarily grow over time and slow down server and client.
1. When removing a part, mark its partInstances as reset.
2. Fetch only non-reset partInstances into the …
> fix: Reset partInstances for removed parts

- meteor/client/lib/lib.tsx
- meteor/client/styles/shelf/dashboard-streamdeck.scss
- meteor/client/styles/shelf/dashboard.scss
- meteor/client/ui/FloatingInspectors/NoraFloatingInspector.tsx
- meteor/client/ui/Settings/RundownLayoutEditor.tsx
- meteor/client/ui/Shelf/BucketPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/client/ui/Shelf/RundownViewBuckets.tsx
- meteor/client/ui/Shelf/Shelf.tsx
- meteor/client/ui/Shelf/ShelfDashboardLayout.tsx
- meteor/client/ui/Shelf/TimelineDashboardPanel.tsx
- meteor/lib/collections/RundownLayouts.ts
This is a feature/behavior change
Currently, AdLibs in the Dashboard and Buckets can be triggered by a single click, a tap on a touchscreen and they can be inspected using the context menu. Stream Deck requires a single button press (that is translated to a simulated mouse click)
In order to make the behavior model the same for both the regular Shelf and the Bucket and Dashboard panels, when using a mouse, the user will single click on an AdLib to Select it, Double-click on an AdLib to trigger & single-tap (using a touchscreen) to trigger. A single button press on a …
> feat: double click on AdLib in the Dashboard and Buckets to trigger

- meteor/client/lib/ui/icons/looping.tsx
- meteor/client/styles/rundownView.scss
- meteor/client/ui/RundownList/RundownListItemView.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownDividerHeader.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
- meteor/server/api/playout/lib.ts
This PR fixes the behaviour for looping rundown playlists. All that was missing was selecting the next part. Besides that it adds some markers in the UI to clarify that the current rundown playlist will loop.
**Status**
> Fix: looping playlists

- meteor/client/ui/RundownView.tsx
This PR contains the following changes:
- Fix: Clarify all uses of "activation" to contain either "rehearsal" or "on-air" such that it is clear to users what the system will do
- Feature: Add an option to directly activate to on-air mode when the planned start of the rundown is close or has passed
- Feature: When the users does a take on an inactive rundown we ask the user if they want to activate (the assumption here is that they think it is already active)
> Better activation ux

- meteor/client/ui/RundownList/util.ts
- meteor/client/ui/RundownView.tsx
- meteor/server/api/rundown.ts
This PR changes the behavior of how re-syncing a missing rundown is handled and some related UI changes.
If a Rundown/Segment is unsynced in Sofie, when user resyncs it, the Unsynced flag will be taken off and a request to the Ingest device will be fired off. If the device returns a "MISSING" state, the Rundown/Segment is left in the "fake synced" state and a message is shown through the notification center for the user to make a decision what to do about it, but only when doing "re-syncing" from the Rundown View. When doing it from the lobby, no message is shown. …
> fix: resync missing rundown

- meteor/server/api/blueprints/context/adlibActions.ts
- meteor/server/api/ingest/mosDevice/ingest.ts
- meteor/server/api/ingest/rundownInput.ts
bug fix
1) adlib partinstances get an invalid takeCount, meaning some ordering logic will fail
1) the rundown will become unsynced if the current part is an adlib part during any ingest change
**Status**
> fix: r28 unsync issues

- meteor/client/lib/rundown.ts
- meteor/client/styles/countdown/overlay.scss
- meteor/client/styles/countdown/presenter.scss
- meteor/client/ui/ClockView/ClockView.tsx
- meteor/client/ui/ClockView/OverlayScreen.tsx
- meteor/client/ui/ClockView/PresenterScreen.tsx
- meteor/client/ui/FloatingInspector.tsx
- meteor/client/ui/FloatingInspectors/L3rdFloatingInspector.tsx
- meteor/client/ui/FloatingInspectors/MicFloatingInspector.tsx
- meteor/client/ui/FloatingInspectors/NoraFloatingInspector.tsx
- meteor/client/ui/FloatingInspectors/SplitsFloatingInspector.tsx
- meteor/client/ui/FloatingInspectors/VTFloatingInspector.tsx
- meteor/client/ui/PieceIcons/Renderers/SplitInput.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/client/ui/Shelf/GlobalAdLibPanel.tsx
- meteor/package-lock.json
This is a fix
The hoverscrub previews for graphics and clips in the Shelf scrolls with the Rundown.
Hoverscrub previews in the Shelf should not scroll, but be attached to the list item/button they are related to.
**Status**
> fix: hoverscrub in shelf scrolls

- meteor/__mocks__/helpers/snapshot.ts
- meteor/server/DatabaseCache.ts
- meteor/server/api/ingest/ingestCache.ts
- meteor/server/api/ingest/mosDevice/__tests__/__snapshots__/mosIngest.test.ts.snap
- meteor/server/api/ingest/mosDevice/__tests__/diffSegmentEntries.test.ts
- meteor/server/api/ingest/mosDevice/__tests__/mosIngest.test.ts
- meteor/server/api/ingest/mosDevice/ingest.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/rundown.ts
bug fix
If a mos segment name changes as part of a resync operation, this will cause the segment to be treated as a new segment.
This will cause it to lose the PartInstances (as-played state), and if it is currently playing will cause it to become unsynced
The same logic used for determining segmentId changes on smaller mos operations is applied, so that segments are preserved as much as possible.
**Status**
> feat: translate segment ids on mos rundown ingest

- meteor/client/ui/Prompter/controller/midi-pedal-device.ts
Adds the ability to have multiple midi devices (pedals) connected to the prompter at the same time.
Only allows for a single device at the time.
Listens to all connected inputs. Accepts CC notes on channel 8 from all active inputs.
**Status**
> feat(Midi): Adds support for multiple midi inputs

- meteor/server/api/blueprints/context/lib.ts
- meteor/server/api/playout/timeline.ts
- packages/blueprints-integration/src/rundown.ts
fix
Once a piece is determined to have definitely ended it is no longer added to the timeline, to minimise the size of the timeline as a performance improvment.
Some pieces can have side effects that cause state changes when they are removed. Any piece which sets a class does this, but most of the time this does not matter.
It is important when the class enables a clip, and we continue playback in the replacement piece. By removing some of the enable class usage, the clip will seek as its calculated current position changes
The blueprints can tell core that a piece …
> fix: add IBlueprintPiece.hasSideEffects property to not prune 'definitely ended' piece (#456) [publish]

- meteor/server/api/blueprints/config.ts
- meteor/server/api/rundown.ts
- packages/blueprints-integration/src/api.ts
Fix
Ensures every blueprint method has a context parameter. Some got lost during conflicts in https://github.com/nrkno/tv-automation-server-core/pull/287
**Status**
> fix: add missing contexts to blueprint api methods [publish]

- meteor/lib/collections/Parts.ts
- meteor/server/api/ingest/rundownInput.ts
- packages/blueprints-integration/src/rundown.ts
- packages/blueprints-integration/src/translations.ts
The `invalidReason` property can not be translated using the blueprint i18n feature.
The `invalidReason` field on a Part is redesigned to make it possible to translate the message. Also, the property is simplified, since the previous structure of `title` and `description` wasn't really used anyway.
> fix: invalidReason translation

- meteor/package.json
- scripts/checkLicenses.js
The checkLicenses.js script hanged/froze, due to the Legally library having changed how it was outputting the licenses.
So i fixed it.
> chore: fix check licenses script

- meteor/client/ui/RundownView/RundownTiming/RundownTimingProvider.tsx
- meteor/package.json
- scripts/checkLicenses.js
Bug fix
During a take, the duration of the "previous" part is unstable, because `timings.duration` is set only once `stoppedPlayback` callback happens. As a result, the following "current" part, if a member of a display duration group will receive all of the "previous" part's `expectedDuration`, causing the part countdown to shift a bit.
The `timings.takeOut` timestamp, which is being set by Core on user action is temporarily used as a duration. There still is a bit of a shift from the difference between `startedPlayback - takeOut` and `duration`, but it's not …
> fix: display duration group display duration instability after a take

- meteor/server/api/snapshot.ts
Allows snapshots to be uploaded if the externalId is missing on a part (e.g. dynamically inserted parts).
Trying to import a snapshot that contains a part that does not have an externalId will result in the snapshot being rejected. This happens in snapshots containing dynamically inserted (queued) parts as the externalId is set to an empty string https://github.com/nrkno/tv-automation-server-core/blob/f48a4aaae286423f2adda630f402e02c30a52f41/meteor/server/api/playout/adlib.ts#L276
Rather than creating the the part id using the external Id, a new random Id will be …
> fix: Upload snapshots where part externalId is missing

- meteor/server/migration/1_12_0.ts
Fixes a bug causing the Blueprint Configuration on studios and showStyles to be lost when restoring a system snapshot.
When restoring a system snapshot, Blueprint Configuration on the studios and showStyles is dropped entirely instead of being restored from the snapshot. The cause is using `migrateConfigToBlueprintConfigOnObject`, which assumes that `blueprintConfig` is missing, when restoring snapshots.
Blueprint Configuration is restored correctly. `migrateConfigToBlueprintConfigOnObject` handles both cases - when `blueprintConfig` is present and when it's …
> fix: blueprintConfig dropped when restoring a snapshot

- meteor/client/styles/rundownList.scss
- meteor/client/styles/splitDropdown.scss
- meteor/client/ui/RundownList.tsx
- meteor/client/ui/RundownList/DragAndDropTypes.ts
- meteor/client/ui/RundownList/RundownListItem.tsx
- meteor/client/ui/RundownList/RundownListItemView.tsx
- meteor/client/ui/RundownList/RundownPlaylistDragLayer.tsx
- meteor/client/ui/RundownList/RundownPlaylistUi.tsx
- meteor/client/ui/RundownList/RundownShelfLayoutSelection.tsx
Re-adds the "shelf layout" selection to the lobby (see https://github.com/nrkno/tv-automation-server-core/pull/256 for details).
Cannot select shelf layout from the lobby.
Re-adds the dropdown to select shelf layout. If no shelf layouts have been marked as selectable options (the default behaviour) then the text "Default" will be displayed in this column (screenshot below). There is a limitation to this implementation, as it will only work for playlists containing a single rundown for now.
**Status**
> fix: Restore shelf layout selection to lobby

- meteor/server/api/systemTime/systemTime.ts
- meteor/server/coreSystem.ts
- meteor/server/systemStatus/__tests__/systemStatus.test.ts
Prevents the use of NTP servers in test environments.
A number of tests use the mock meteor module, which calls the Meteor.startup registered functions when it mocks startup. This means that a number of tests make calls to an NTP server, which can lead to the tests failing if these request get blocked due to rate limiting.
Calls to NTP servers are disabled if the environment variable JEST_WORKER_ID is set, indicating that the code is being run in the test environment. The time diff is faked in this scenario.
**Status**
> fix: Don't use NTP servers in tests

- meteor/client/ui/RundownView/RundownNotifier.tsx
- packages/server-core-integration/src/lib/corePeripherals.ts
The "Restart Device" button will only be shown where a device has set its status to WARNING_MAJOR or anything more severe.
The "Restart Device" button is shown in notifications for all status messages that do not have the status code "GOOD".
The "Restart Device" button will not be shown in a device status notification unless the status is >= WARNING_MAJOR. This allows WARNING_MINOR to be used to send device status updates to the user without making the user think that some intervention is required. An example use case is sending a notification to indicate that Viz …
> Show restart button only for device notifications >= WARNING_MAJOR

- meteor/server/api/playout/take.ts
Fixes a bug where you could not have an adlib action queue and `takeAfterExecute` a part at the end of a rundown.
`takeNextPartInnerSync` will throw an error because `dbPlaylist` has no `nextPartInstanceId`
The checks for `activationId` and `nextPartInstanceId` will happen on the playlist fetched from the cache, so in the case where we have an existing cache that we're operationg on we won't be checking this against the database copy.
**Status**
> Fix: Take after execute cache usage in takeNextPartInnerSync

- meteor/client/styles/prompter.scss
- meteor/client/ui/Prompter/PrompterView.tsx
- meteor/client/ui/Prompter/controller/joycon-device.ts
- meteor/client/ui/Prompter/controller/midi-pedal-device.ts
- meteor/client/ui/Prompter/controller/shuttle-keyboard-device.ts
Listing of button id's for L, R, and L+R mode for JoyCon.
Adjusted the R JoyCon to take into account that it is less sensitive than the L JoyCon.
The R JoyCon never reaches full speed ahead / reverse, which L JoyCon does.
L and R are now more equal in response / sensitivity for the joystick.
**Status**
> Added button overview, and adjusted the R joystick

- meteor/client/styles/_itemTypeColors.scss
Full screen Graphics and Lower Thirds are indistinguishable. LIVE_SPEAK items have a split background, that is similar to actual splits.
Full screen graphics use a darker shade of orange. LIVE_SPEAK items have a bright-blue background.
**Status**
> feat: change colors for live-speak, vt, graphics, lower-thirds

- meteor/lib/collections/PartInstances.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/playout/__tests__/api.test.ts
- meteor/server/api/playout/__tests__/lib.test.ts
- meteor/server/api/playout/actions.ts
- meteor/server/api/playout/debug.ts
- meteor/server/api/playout/lib.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/playout/take.ts
- meteor/server/cache/CacheCollection.ts
feature
PartInstances are only reset by an explicit reset operation for the whole playlist, or when the part is set as next. (Other rules apply for orphaned instances)
When the segment has finished playback it is reset
When the next point is set earlier in the segment it will reset instances as appropriate to show what is planned
Additionally, the nextSegmentId has been tested a bit and fixed 
**Status**
> feat: reset segments upon leaving

- meteor/client/styles/countdown/overlay.scss
- meteor/client/styles/countdown/presenter.scss
- meteor/client/ui/ClockView/OverlayScreen.tsx
- meteor/client/ui/ClockView/PresenterScreen.tsx
- meteor/client/ui/RundownView.tsx
The countdown for ad-lib parts is not shown on the presenters' screen. When an ad-lib part (such as a BTS) is played, the display is blank.
Ad-Lib parts (PartInstances without a backing Part) are displayed in the same way as other Parts.
**Status**
> fix(Presenter screen): BTS countdown on presenter screen

- meteor/lib/api/playout.ts
- meteor/server/api/__tests__/peripheralDevice.test.ts
- meteor/server/api/ingest/__tests__/ingest.test.ts
- meteor/server/api/ingest/actions.ts
- meteor/server/api/lib.ts
- meteor/server/api/playout/__tests__/playout-executeAction.test.ts
- meteor/server/api/playout/__tests__/playout.test.ts
- meteor/server/api/playout/__tests__/timeline.test.ts
- meteor/server/api/playout/adlib.ts
- meteor/server/api/playout/api.ts
- meteor/server/api/playout/lockFunction.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/rundown.ts
- meteor/server/api/rundownPlaylist.ts
- meteor/server/api/userActions.ts
- meteor/server/security/rundownPlaylist.ts
- meteor/server/security/studio.ts
Fix
Some security warnings are thrown at startup in development. 
Fixes these warnings. This is done mostly by splitting the security check out of the lock functions, with the result of the check being passed into the lock function instead
We have discussed removing a lot of the `ServerPlayoutAPI` as the `UserActionsAPI` should always be used.
I have done that as part of this, as otherwise each method needs updating to be hooked into the security correctly.
**Status**
> feat: split security check out of lock functions

- packages/blueprints-integration/package.json
- packages/mos-gateway/package.json
- packages/package.json
- packages/playout-gateway/package.json
- packages/server-core-integration/package.json
This is a workflow bugfix where the husky linting precommit hook prevented commits because the linting would fail.
If making changes in `packages`, the husky precommit hook will trigger and will fail because the root `package.json` doesn't contain any `lint-fix` task.
Based on [#1](https://github.com/lerna/lerna/tree/main/core/filter-options) [#2](https://github.com/typicode/husky/issues/624) [#3](https://medium.com/rewrite-tech/how-to-create-a-monorepo-with-lerna-3ed6dfec5021) and [#4](https://dev.to/try_catch/top-5-handy-lerna-flags-for-your-monorepo-10fa), this …
> chore: lerna precommit hook

- .github/workflows/node.yaml
This is a feature for the CI system.
To find out the version of the pre-release library published using the CI flow, one needs to rummage through GitHub actions logs
GitHub Actions will post a comment on the PR if a pre-release library version was published to NPM.
**Status**
> chore(ci): publish comment of prerelease version number

- packages/playout-gateway/src/atemUploader.ts
- packages/playout-gateway/src/tsrHandler.ts
Currently the playout-gateway can upload stills to the atem switcher, this PR adds clip uploading to that functionality.
Because the uploading functionality has matured a fair bit since the original implementation I've changed the uploading to upload all assets from a single process rather than spawn new processes for every upload. In addition this means the media is uploaded one after the other instead of all at once.
**Status**
> feat: playout-gw atem clip uploading

- meteor/client/ui/Settings/ConfigManifestSettings.tsx
- meteor/client/ui/Settings/StudioSettings.tsx
- packages/blueprints-integration/package.json
- packages/playout-gateway/src/configManifest.ts
- packages/yarn.lock
Adds support for configuring the `layerName` of a mapping and uses it in the layer mapping dropdown in settings.
No feature.
A setting is added to mapping settings to allow the input of a layer name, this name is then used instead of the layer Id in the mapping table.
Additionally, where the layer mapping dropdown type is used in settings, the layer name will be used if it's available (here GFX Ident is displayed instead of `graphic_layer_ident`)
See https://github.com/nrkno/tv-automation-state-timeline-resolver/pull/178 for information on …
> Feat: Layer name

- meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts
- meteor/server/api/blueprints/context/adlibActions.ts
- meteor/server/api/playout/adlib.ts
- packages/blueprints-integration/src/context.ts
Adds a pair of functions to allow adLib actions to look backwards in the script from the current point to find the last *scripted* piece on a layer as apposed to the last played piece.
AdLib actions can only find the last played piece.
AdLib actions can call `findLastScriptedPieceOnLayer` which will look backwards from the current part to find the piece on a given sourcelayer that appears closest to the current part. The use case for this is, for example, a producer is on a VT going into an interview over a Live feed, but the interviewee is not ready yet. The …
> Feat: Find last scripted piece on layer

- meteor/client/lib/StyledTimecode.tsx
- meteor/client/ui/FloatingInspectors/L3rdFloatingInspector.tsx
- meteor/client/ui/FloatingInspectors/VTFloatingInspector.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/Settings/StudioSettings.tsx
- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
This PR encompasses a number of fixes including:
- Removing an `[object Object]` message displayed in the mapping settings when a route set is active.
- Fix a bug where graphic duration does not get displayed in `L3rdFloatingInspector`.
- Prevent attempts to scroll to segments/focus parts when in a shelf-only view of a rundown.
- Sort global adLibs by rank before assigning shortcuts in adLib panels.
- Ensure `mediaPreviewUrl` has a trailing slash before using it to get a preview/thumbnail URL.
- Wrap some aspects of `StyledTimecode` in `<span>` tags with class names to allow styling of timecode by custom CSS at TV 2 (does not affect how timecode is displayed for NRK).
**Status**
> Various fixes from TV 2 for Release 33

- meteor/client/ui/Settings/RundownLayoutEditor.tsx
- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/GlobalAdLibPanel.tsx
- meteor/client/ui/Shelf/TimelineDashboardPanel.tsx
- meteor/lib/api/rundownLayouts.ts
- meteor/lib/collections/RundownLayouts.ts
- packages/blueprints-integration/src/action.ts
- packages/blueprints-integration/src/rundown.ts
This PR allows blueprints to generate an identifier for adLibs/adLib actions that can then be used to only display one "copy" of a given adLib to the user.
The use case for this is a script writing workflow where, for example, a lower third might be entered into the script for every segment in which an interviewee is expected to appear. This PR allows Sofie to just show one copy of the generated lower third adlib instead of one per segment.
No feature.
The blueprints can add a `uniquenessId` to adLibs/adLib actions, it is left to the blueprint writer to determine …
> feat: Add duplicate AdLibs filtering

- meteor/server/migration/X_X_X.ts
- meteor/server/migration/currentSystemVersion.ts
- meteor/server/migration/expectedDeviceVersions.ts
- meteor/server/migration/migrations.ts
feature/workflow improvement
(For release34)
For each release a migration is added to update the expected version of the playout and mos gateways
Now that the gateways follow the same versioning scheme as core, a migration has been added to update the expected version to match the current version of core. This means that one doesnt have to be added for each release.
**Status**
> feat: migrations to ensure the playout and mos gateways are matching the version of core

- meteor/package-lock.json
- meteor/server/api/playout/take.ts
After playback of a segment ends, PartInstances inside are reset. This causes problems for timing in the GUI as reset PartInstances are not sent to the GUI and are not taken under consideration for timing purposes.
PartInstances inside segments that stop playing are only reset if the playlist is looping.
**Status**
> fix: only reset previous segment on looping rundowns

- packages/playout-gateway/src/configManifest.ts
Adds in the missing vMix Config Manifest details to allow configuration in the Sofie UI
You can't configure vMix devices via the UI
You can configure vMix devices via the UI
**Status**
> fix: Add vMix Config Manifest

- meteor/client/ui/Shelf/ShelfContextMenu.tsx
- meteor/lib/api/TranslatableMessage.ts
- meteor/lib/collections/AdLibActions.ts
- meteor/lib/collections/BucketAdlibActions.ts
- meteor/lib/lib.ts
- meteor/server/api/blueprints/postProcess.ts
Action trigger mode labels are not translated in the UI, because proper namespaces are not stored alongside those strings and aren't used in the `t` function.
Incoming ITranslatableMessage objects for AdLib Actions are now post-processed by core, namespace data is injected and messages are properly handled when being displayed.
**Status**
> fix: adlib action trigger mode labels are not translated

- meteor/client/ui/RundownView/RundownTiming/RundownTimingProvider.tsx
- meteor/client/ui/RundownView/RundownTiming/SegmentDuration.tsx
- meteor/lib/collections/Parts.ts
- meteor/server/api/blueprints/events.ts
- meteor/server/api/playout/take.ts
- packages/blueprints-integration/src/rundown.ts
This is a new feature.
All playable parts are counted towards show time and as-played time - unless they are "invalid" or "floated", which renders them unplayable.
A Part can be marked as "untimed" which will keep them playable, but cause them to:
* not trigger blueprints "firstTake" callback
* not set `startedPlayback` on a playlist when they are taken, the `startedPlayback` will be set once a not-"untimed" part is taken
* not count towards segment time budget
* there will be a countdown to the end of an "untimed" part (unless it's `expectedDuration` is 0) and the …
> feat: untimed parts

- meteor/client/ui/Settings/ConfigManifestSettings.tsx
- meteor/client/ui/Settings/StudioSettings.tsx
- meteor/client/ui/Settings/components/ConfigManifestEntryComponent.tsx
- meteor/lib/api/deviceConfig.ts
- packages/blueprints-integration/src/config.ts
- packages/playout-gateway/src/configManifest.ts
- packages/server-core-integration/src/lib/configManifest.ts
This adds a property to integer config manifest entries named `zeroBased`, which indicates that this is a value that should be stored in the databse as a value starting from 0, but makes more sense to show to the user as a value starting from 1. For example, an ATEM Aux makes more sense to show to the user as AUX 1->X than AUX 0-> Y.
Currently all numerical config values are displayed to the user as whatever is stored in the database, which is usually the value required by the consuming device/blueprint.
Integer config fields for both blueprints and device manifests …
> feat: zero-based integers in settings

- meteor/__mocks__/helpers/database.ts
- meteor/package-lock.json
- meteor/server/api/__tests__/rundownPlaylist.test.ts
- meteor/server/api/ingest/commit.ts
- meteor/server/api/ingest/mosDevice/__tests__/mosIngest.test.ts
- meteor/server/api/rundownPlaylist.ts
- packages/yarn.lock
Fix
When a rundown is removed from a playlist, the playlist is not regenerated.
This means that the name, timing or any other properties can refer to the recently removed rundown.
Whenever a rundown is removed from a playlist (or moved out of a playlist), that playlist gets regenerated in the same way as when we add/update a rundown in the playlist.
If the ordering is calculated by the blueprints, the order of the remaining rundowns will be updated too.
I am unsure if this is targetting the correct release, it might want to be delayed to …
> fix: Update playlist after removing rundown

- meteor/lib/collections/PartInstances.ts
- meteor/server/api/blueprints/context/adlibActions.ts
- meteor/server/api/playout/take.ts
- packages/blueprints-integration/src/api.ts
- packages/blueprints-integration/src/context.ts
- packages/blueprints-integration/src/rundown.ts
Feature
Adlib actions are unable to access the `PartEndState` of the previous part. This data is owned by the blueprints, and is currently only consumed by `onTimelineGenerate` and future calls to `getPartEndState`
Adlib actions are now able to get access this `PartEndState` directly on any `IBlueprintPartInstance`.
`getPartEndState` has been modified to have access to the full `IBlueprintPartInstance` too, so that it can use the `metaData` or other properties.
**Status**
> feat: expose PartEndState to the adlib actions (#518) [publish]

- meteor/client/styles/rundownView.scss
- meteor/client/ui/FloatingInspectors/NoraFloatingInspector.tsx
- meteor/client/ui/SegmentTimeline/Renderers/L3rdSourceRenderer.tsx
- meteor/public/images/multi-step-chevrons-default.svg
- meteor/public/images/multi-step-chevrons.svg
This is a new feature
The GUI has no special features to display the state of multi-step graphics.
Multi-step graphics are now displayed with special "chevrons" that the graphic has multiple, user-triggerable steps and indicate the step the graphics will be on - once displayed. The hoverscrub preview of graphics should follow the assigned step as well as show the total amount of steps available.
**Status**
> feat: multistep graphics UI

- meteor/lib/api/peripheralDevice.ts
- meteor/server/api/ingest/rundownInput.ts
- meteor/server/api/peripheralDevice.ts
- packages/blueprints-integration/src/ingest.ts
- packages/server-core-integration/src/lib/corePeripherals.ts
Adds the `dataPlaylistGet` peripheral device API method.
New feature.
The `dataPlaylistGet` method can be used to get the ingest data cache for an entire rundown playlist, similar to how `dataRundownGet` gets the ingest data for an individual rundown. This PR does not implement any of the other `dataRundown*` methods for playlists.
**Status**
> Feat: dataPlaylistGet

- packages/playout-gateway/src/configManifest.ts
- packages/playout-gateway/src/coreHandler.ts
- packages/playout-gateway/src/tsrHandler.ts
A feature and minor config manifest changes related to https://github.com/nrkno/tv-automation-state-timeline-resolver/pull/182
- Adds baseline expectedPlayoutItems support
- Adds config for Viz Engine REST port config
- Fixes config property name
**Status**
> feat: add baseline expectedPlayoutItems support to Playout Gateway

- meteor/package-lock.json
- meteor/package.json
- meteor/server/api/__tests__/rundownPlaylist.test.ts
- meteor/server/api/blueprints/context/syncIngestUpdateToPartInstance.ts
- meteor/server/api/ingest/cache.ts
- meteor/server/api/ingest/commit.ts
- meteor/server/api/ingest/expectedPackages.ts
- meteor/server/api/ingest/expectedPlayoutItems.ts
- meteor/server/api/ingest/generation.ts
- meteor/server/api/ingest/ingestCache.ts
- meteor/server/api/peripheralDevice.ts
- meteor/server/api/playout/cache.ts
- meteor/server/api/playout/lockFunction.ts
- meteor/server/api/rundownPlaylist.ts
- meteor/server/api/studio/cache.ts
- meteor/server/cache/CacheBase.ts
- meteor/server/cache/CacheCollection.ts
- meteor/server/cache/CacheObject.ts
- meteor/server/lib/lazy.ts
code cleanup
The DbCacheReadObject and DbCacheReadCollection support being lazy initialised.
We only make use of this for a couple of collections, and supporting it makes it hard to understand whether an operation on the cache collection will yield the fiber or not.
Additionally, for the cases where we were lazy initialising, by knowing we might be doing so, we can optimise by running the loads in parallel. Currently we would be loading them one at a time, as the code was not aware they would need loading
The collections no longer support being lazy initialised. …
> feat: Remove delayed initialisation from DbCacheReadObject and DbCacheReadCollection

- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/GlobalAdLibPanel.tsx
- meteor/client/ui/Shelf/TimelineDashboardPanel.tsx
Bugfix
Search for ad lib in shelf, change to a different tab, go back to first tab: search bar is clear but the results (or lack thereof) from the previous search are still there. looks like a bunch of adlibs have disappeared magically.
When the search filter should now be persisted until the page is refreshed or user navigates away.
**Status**
> fix: search bar cleared when switching tabs in shelf

- meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
- meteor/lib/rundownNotifications.ts
- meteor/package-lock.json
Bug fix/feature change
If there is a media status-having Pieces in an invalid Parts, they still produce notifications.
Notifications from invalid Parts will not be produced. Plus, invalid Parts will not produce notifications if `.invalidReason` is set. Plus, an "Invalid" label is removed from invalid Parts.
**Status**
> fix: invalid notifications

- meteor/server/api/ingest/commit.ts
- meteor/server/api/rundownPlaylist.ts
Bug fix
Rundowns appear out of order due to function that assigns the ranks from blueprints treating the keys in the ranks map as `_id` values, when they are `rundownExternalId` values according to the `blueprints-integration` typings. This results in every rundown getting the default rank of 0 as a result, as all the assignments fail.
Ranks are assigned using `rundownExternalId` as the typings direct, resulting in the correct ordering.
**Status**
> fix: Assign ranks according to playlist order by rundownExternalId

- meteor/server/api/playout/adlib.ts
Bug fix
Only adLibs from the current rundown can be taken. AdLibs from future or previous rundowns cannot be started.
AdLibs from any rundown can be taken as long as the rundown they originate from has the same showstyle variant as the current rundown.
**Status**
> fix: AdLibs from other Rundowns in a Playlist can't be started, even uf they use the same ShowStyleVariant

- meteor/server/api/playout/playout.ts
Bug fix
When playing a segment with just one part, the Next Up action (shift+f10) doesn't work, because the logic for selecting allowed segments is reversed. 
**Status**
> fix: moveNext when using segmentDelta

- meteor/client/ui/RundownView/RundownNotifier.tsx
- meteor/lib/api/rundownNotifications.ts
- meteor/lib/lib.ts
- meteor/server/api/rundownNotifications.ts
Bug fix + performance improvement
* The first commits adds a cache in front of the method `getMediaObjectIssues`, so that when having multiple clients open that request the same status, the result is reused.
* The second commit fixes a bug, where an interval isn't cleaned up when leaving the rundown view. (can be a problem if going into and out of rundowns many times, as the setIntervals accumulates.)
**Status**
> Fix: media status polling

- meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
- meteor/client/ui/Shelf/AdLibListItem.tsx
- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/BucketPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/GlobalAdLibPanel.tsx
- meteor/lib/api/triggers/actionFilterChainCompilers.ts
- meteor/server/migration/1_37_0.ts
- packages/blueprints-integration/src/showStyle.ts
This is mostly a clean-up PR, removing old hotkey properties on ISourceLayer that were superseded by Action Triggers.
Properties describing GUI hotkey behavior were placed on ISourceLayer objects of ShowStyleBase objects.
These properties are now removed and `clearKeyboardHotkey` is migrated to a boolean `isClearable` value.
**Status**
> chore: remove hotkey props

- meteor/client/ui/RundownView.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
This is a feature improvement.
Updates to Segment components after an invalidation (re-resolving the segment) is done as follows: the current & next segment are updated immediately, all the other ones are staggered in a window of 500-2500ms post change.
The new behavior injects a third step between those two: the segment following the current one is updated before the 500-2500ms window. 
**Status**
> feat: improved staggered updates

- meteor/client/ui/SegmentTimeline/Renderers/EvsLayerItemRenderer.tsx
- meteor/client/ui/Shelf/BucketPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/lib/collections/BucketAdlibActions.ts
It's not possible to select and rename Bucket Adlibs, because they aren't selectable and the infrastructure for TranslatableMessages in AdLib Action names makes it impossible to pick up on the user-defined name.
These bugs are fixed.
**Status**
> fix: it's not possible to select bucket adlibs and rename them

- meteor/server/api/blueprints/context/lib.ts
- meteor/server/api/playout/adlib.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/userActions.ts
- packages/blueprints-integration/src/rundown.ts
Feature
When a piece is double clicked, it gets 'direct played' as an adlib piece. This is only allowed for LOWER_THIRD pieces, as they are known to be safe to do this with.
This introduces a new rule that lets the blueprints say which pieces are safe to use as an adlib like this.
Additionally, it states whether it should be used as an adlib or if an adlib-action should be executed instead.
**Status**
> feat: pieces can specify how to be direct-played

- meteor/lib/api/prompter.ts
Changes in script of played-out Parts is not shown, because they are not reset. This includes having the rundown in a "parked" state after a rehearsal.
Non-current or next partInstances are treated as if they were reset, for the purpose of the prompter script.
> fix(Prompter): show changes in played-out Parts

- .vscode/launch.json
VSCode configuration fix
Can't debug the frontend with VSCode because breakpoints are unbound
Debugging the frontend with VSCode is possible.
Changed type to pwa-chrome to use the built-in tools instead of the deprecated extension.
Fixed the source map path override to make breakpoints bind correctly.
**Status**
> chore: fix vscode debugging configuration

- meteor/client/ui/Shelf/AdLibRegionPanel.tsx
- meteor/client/ui/Shelf/BucketPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/PieceCountdownPanel.tsx
- meteor/client/ui/Shelf/ShelfDashboardLayout.tsx
- meteor/client/ui/Shelf/TimelineDashboardPanel.tsx
Bug fix
When a onRundownChange piece is ended by an onRundownEnd piece, the onRundownChange one is still shown as being on-air.
This is because the piece exists, but the infinite logic prunes the piece out as it is determined to be 0 length. This causes it to not get correct playout timings, and so the ui thinks it is playing.
The pieceInstances are run through the same infinite processing logic that is used elsewhere before filtering down to the active ones.
**Status**
> fix: getUnfinishedPieceInstancesReactive not considering interactions between infinite pieces

- meteor/client/lib/localStorage.ts
Feature improvement
All queries for one of the GUI flags go directly to localStorage. While it's fast, it's still at least 100x slower than normal variable lookup ([1](https://stackoverflow.com/questions/8074218/speed-cost-of-localstorage))
Puts an in-memory cache in front of the localStorage get/set.
**Status**
> feat: cache local storage UI flags

- meteor/lib/collections/PartInstances.ts
- meteor/lib/collections/PieceInstances.ts
- meteor/server/api/playout/cache.ts
Thinking about the slowness with old rundowns, I discovered that CacheForPlayout was using queries that did not have an appropriate index.
Hopefully these are close enough to help it, but I am not sure if the PartInstance one is good enough
**Status**
> chore: add new index to PartInstance and PieceInstance for populating CacheForPlayout

- meteor/client/ui/App.tsx
- meteor/client/ui/RundownView.tsx
Feature
The Follow OnAir state is disabled only when the segment leaves the viewport.
This changes the behavior so that the Follow OnAir state is disabled when mouse wheel interactions happen and the segment leaves the top area of the Rundown View.
**Status**
> feat: wheel detach follow on air

- .husky/pre-commit
- meteor/eslint-rules/README.md
- meteor/eslint-rules/noFocusedTestRule.js
- meteor/eslint-rules/noFocusedTestRule.ts
- meteor/eslint-rules/utils.js
- meteor/eslint-rules/utils.ts
- meteor/lib/lib.ts
- meteor/package-lock.json
- meteor/package.json
- packages/blueprints-integration/package.json
- packages/mos-gateway/package.json
- packages/package.json
- packages/playout-gateway/package.json
- packages/server-core-integration/package.json
- packages/yarn.lock
fix
* The pre-commit hooks would only run for either meteor, or the packages. Never both
* The hooks would do a full lint of the project, not just the changed files
* The pre-commit hooks are run for both meteor and the packages
* The hooks will lint only the changed files
**Status**
> fix: update code-preset, lints only changed files

- meteor/client/lib/EditAttribute.tsx
- meteor/client/ui/Settings/components/triggeredActions/TriggeredActionEntry.tsx
- meteor/client/ui/Settings/components/triggeredActions/TriggeredActionsEditor.tsx
- meteor/client/ui/Settings/components/triggeredActions/actionEditors/filterPreviews/AdLibFilter.tsx
- meteor/client/ui/Settings/components/triggeredActions/actionEditors/filterPreviews/FilterEditor.tsx
Feature & Bug fix
When editing the tags field in the Action Triggers, the field is a free text field, with no information on the tags available
When editing the tags filter, a list of available tag suggestions will be displayed, based on the selected "sample" rundown. Since this list may not be exhaustive, the field is still non-validated (you can still input multiple comma separated tags), but it should give a bit more help during manual setup.
This PR also fixes an issue with the performance of that view, because all of the components were reactive whenever any of …
> feat: Action Triggers tag filter suggestions

- meteor/client/ui/SegmentTimeline/SegmentContextMenu.tsx
Feature
It's impossible to use the option of "Set Segment as Next" when context-clicking on a Part.
All spots will show the option of "Set Segment as Next", with a separator and the "Set this Part as Next" option below a separator.
**Status**
> feat: show "set segment as next" in Part context as well

- meteor/client/ui/SegmentTimeline/Renderers/VTSourceRenderer.tsx
- meteor/lib/mediaObjects.ts
This PR fixes a few issues related to Package Manager media statuses.
* A few bugs, causing them to never show up
* Don't display freeze/black frames with 0 duration
* explicit handling of the media situations "not checked yet by Package Manager" vs "checked and not found"
**Status**
> Fix: package info

- meteor/server/api/playout/lockFunction.ts
- meteor/server/api/studio/lockFunction.ts
minor fix
"saveAllToDatabase never called" is logged (a few seconds later) every time an error is thrown in the lockFunctions.
Upon error, "saveAllToDatabase never called" is not logged.
**Status**
> Fix: supress not saved cache

- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
Bug fix
1. Sometimes segments doesn't rewind, with autoRewindLeavingSegment enabled.
2. When setting a part as next, it is not scrolled into the viewport, when it should be.
1. Segments rewind with autoRewindLeavingSegment enabled.
The bug was caused from a condition dependent on a state attribute that was set asynchronous with setState. Thus the condition sometimes received the old and sometimes the new state.
2. When setting a part as next, if the segment is not live and the part is outside of the SegmentTimelineContainer viewport, the part is scrolled to the …
> fix: rewinding and scrolling next part

- meteor/server/api/playout/lib.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/playout/take.ts
- meteor/server/api/userActions.ts
Bug fix in the Queued (Next) Segment feature
In various edge cases the queued segment starts looping infinitely (until cleared manually), or is queued an extra time.
Sample steps to reproduce the unwanted behavior:
Case 1:
- Take a Part in segment A
- Queue segment B
- Set first part of Segment B as next
- Queue Segment A twice
- Take - Segment A will loop until manually unqueued
Case 2:
- Take the first part in a segment (A) that has multiple parts
- Queue a segment (B) that has only one part
- Set as next segment B
- Take - Segment A will loop until manually unqueued
Case 3:
- Take the first part in a segment A, that has …
> fix: Queued segment looping until cleared manually

- meteor/server/api/peripheralDevice.ts
- meteor/server/api/playout/timeline.ts
- meteor/server/lib/optimizedObserver.ts
- meteor/server/publications/fastTrack.ts
- meteor/server/publications/timeline.ts
Performance improvement
When a new timeline is generated:
1. The timeline is generated and is put into the in-memory Cache
2. The timeline is saved into MongoDB
3. MongoDB emits the change back to Core
4. The publication picks up the change and starts recalculating (routing) the timeline.
5. The publication sends the new timeline to Playout-gateway
In my local tests, the time from 1 to 4 is about **20-30 ms**.
When a new timeline is generated:
1. The timeline is generated and is put into the in-memory Cache
2. The timeline is also fast-tracked and sent directly to the …
> feat: Optimize timeline publication

- meteor/server/migration/1_37_0.ts
- meteor/server/migration/X_X_X.ts
Bug fix.
It's currently not possible for System migrations to change / remove the default keyboard shortcuts created by core migrations.
The Id values of the default migrations are now hashed when they are created, making them match up with the Ids that the migration context will be searching for. A migration has also been added to migrate the existing actions to the new Id values, so that this change will take effect when R38 is deployed.
**Status**
> fix: Hash triggers for core migrations

- .husky/pre-commit
Pre-commit script fix
Failing on Linux and macOS.
Use $OSTYPE to detect the OS.
Force meteor to run in x86 on ARM Macs. (to be removed when upgrading to meteor that supports arm64) 
Tested only on Windows and macOS, not tested on Linux.
**Status**
> chore: fix pre-commit script to work on Linux and macOS

- meteor/lib/hash.ts
- meteor/lib/lib.ts
- meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts
- meteor/server/api/blueprints/__tests__/postProcess.test.ts
- meteor/server/api/blueprints/context/adlibActions.ts
- meteor/server/api/blueprints/context/syncIngestUpdateToPartInstance.ts
- meteor/server/api/blueprints/postProcess.ts
- meteor/server/api/ingest/generation.ts
- meteor/server/api/ingest/mosDevice/diff.ts
- meteor/server/cache/CacheCollection.ts
fix
PieceIds are derived from among many other strings, the SegmentId.
This means that when we move a Part between segment via mosRoStoryMove, all the pieces will be purged and recreated with different ids.
The ids are no longer based on the SegmentId, better matching how PartIds.
This has risk of duplicate id errors cropping up, so might be better for r38? @nytamin 
**Status**
> fix: make pieceIds generate without relying on the segmentId, so that they are stable when parts are moved between segments

- packages/documentation/docs/getting-started/installation/installing-a-gateway/rundown-or-newsroom-system-connection/rundown-editor.md
- packages/documentation/docs/getting-started/installation/installing-sofie-server-core.md
Docs update
Sofie Rundown Editor is not mentioned in the docs.
This PR adds basic links to the Rundown Editor repo and suggests using the Rundown Editor for demo deployments of Sofie.
There's some unrelated changes in `installing-sofie-server-core.md` which were caused by the auto formatter.
> docs: add links for the Sofie Rundown Editor

- meteor/lib/api/deviceConfig.ts
- meteor/lib/api/userActions.ts
- meteor/server/api/__tests__/userActions/system.test.ts
- meteor/server/api/peripheralDevice.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/rest/__tests__/rest.test.ts
- meteor/server/api/rest/rest.ts
- meteor/server/api/userActions.ts
- packages/server-core-integration/src/lib/configManifest.ts
Feature
The only way to disable a subDevice in a Peripheral Device is through the GUI
The unstable (v0) REST API now exposes a method to disable a SubDevice in a given PeripheralDevice. The PeripheralDevice's configuration manifest is inspected to make sure this is allowed.
**Status**
> feat: REST method for disabling subdevice

- meteor/server/api/playout/playout.ts
Only load pieceInstances that we know we the timings may need to be updated for, ie ones that come from the current or next part. This reduces data transferred from the database and reduces the search space for when we use the cache.
All piece instances in the currently active playlist are loaded.
I think the current and next part covers all piece instances that could possibly have a 'now' time that will be updated but do please correct me if I'm wrong here.
**Status**
> fix: strict select of pieceinstances in timelineTriggerTime

- meteor/client/ui/RundownView.tsx
- meteor/client/ui/Shelf/AdLibRegionPanel.tsx
- meteor/client/ui/Shelf/DashboardActionButtonGroup.tsx
- meteor/lib/api/triggers/actionFactory.ts
- meteor/lib/api/userActions.ts
- meteor/server/api/__tests__/peripheralDevice.test.ts
- meteor/server/api/__tests__/userActions/general.test.ts
- meteor/server/api/ingest/__tests__/ingest.test.ts
- meteor/server/api/ingest/mosDevice/__tests__/mosIngest.test.ts
- meteor/server/api/playout/__tests__/playout-executeAction.test.ts
- meteor/server/api/playout/__tests__/playout.test.ts
- meteor/server/api/playout/__tests__/timeline.test.ts
- meteor/server/api/playout/playout.ts
- meteor/server/api/userActions.ts
Bug fix
Users will sometimes press take multiple times close to each other when it looks like the first press did nothing.
If the second press is within 1s of the first it will be rejected.
If it is longer, then both takes will be performed
When the user does a take, the currentPartInstanceId is passed to the backend. This avoids the double-take problem as the currentPartInstance will have changed when the second one attempts to be executed and so will fail
**Status**
> feat: pass currentPartInstanceId into UserActions.take call

- packages/documentation/docs/getting-started/installation/installing-connections-and-additional-hardware/casparcg-server-installation.md
docs update
The links to the CasparCG Media Scanner point to the CasparCG Launcher.
The links now point to the correct place.
There are some unrelated changes caused by the auto formatter.
> docs: fix CasparCG Media Scanner links

- packages/documentation/docs/getting-started/installation/installing-a-gateway/rundown-or-newsroom-system-connection/installing-sofie-with-google-spreadsheet-support.md
- packages/documentation/docs/getting-started/installation/installing-blueprints.md
- packages/documentation/docs/main/features-and-configuration/concepts-and-architecture.md
- packages/documentation/docs/main/resources.md
- packages/documentation/versioned_docs/version-1.32.0/getting-started/installation/installing-blueprints.md
- packages/documentation/versioned_docs/version-1.32.0/main/features-and-configuration/concepts-and-architecture.md
- packages/documentation/versioned_docs/version-1.32.0/main/resources.md
Docs update
The demo blueprints are mentioned as spreadsheet blueprints.
The blueprints are now explicitly called demo blueprints instead of spreadsheet blueprints.
I also added a few more links to the [Rundown Editor](https://github.com/SuperFlyTV/sofie-automation-rundown-editor). There's also some unrelated style and formatting changes caused by the auto formatter.
> docs: rename spreadsheet-blueprints to demo-blueprints

- packages/playout-gateway/src/tsrHandler.ts
Bug fix
When errors from PGW are logged, the device names are old ("VizMSE Uninitialized", "Quantel device (uninitialized)"), ie not the ones up to date.
The up to date device names are logged ("VizMSE xxx.xxx.xxx.xxx", "Quantel xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx/default/xxxxxx")
> fix: PGW: old device names in log

- package.json
- scripts/fix-windows-yarn.js
Bug fix
Repo package install scripts don't work correctly on Windows.
Patches the yarn installation so that it works with `meteor yarn`
**Status**
> fix: win32 meteor yarn (Release 40)

- meteor/client/styles/contextMenu.scss
- meteor/client/styles/shelf/adLibPanel.scss
- meteor/client/ui/Shelf/AdLibListItem.tsx
- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/ShelfContextMenu.tsx
- meteor/lib/collections/RundownPlaylists.ts
Bug fix
AdLibs of different showStyle-bases are presented as compatible, even though it's not technically possible to mix AdLibs from one ShowStyle in another.
These AdLibs are now shown as disabled (grayed out) and will not be triggered when double-clicking.
**Status**
> fix: show adLibs from different show-styles as disabled

- meteor/client/ui/TestTools/Timeline.tsx
- meteor/lib/rundown/__tests__/infinites.test.ts
- meteor/lib/rundown/infinites.ts
- meteor/package-lock.json
Bug fix
When a Virtual Piece (generally, an infinite-capping "clear" Piece) is placed in the current Part, if it is on a different PieceLifeSpan than the one it's supposed to stop, the Virtual Piece will not be included in the result from `processAndPrunePieceInstanceTimings`, unless `includeVirtual` is enabled. Because of that, it will never actually stop the infinite Piece at the resolution stage and effectively result in the infinite Piece continuing.
Before adding a Piece to the result set of `processAndPrunePieceInstanceTimings`, the Piece is evaluated against …
> fix: infinites capped by virtuals

- meteor/lib/mediaObjects.ts
bug fix
Sofie sometimes detects the framerate of video packages incorrectly, particularly in the case of progressive scan files. This is because `buildPackageFormatString` looks at `codec_time_base` to determine a video's framerate. In certain video formats (such as XAVC MXF and H.264 MP4), `codec_time_base` is often double that of the video's actual framerate. Both ffmpeg and DaVinci Resolve export files which have this same characteristic. At first glance, it might seem that `codec_time_base` is counting fields instead of frames, but this also happens with progressive scan files. Beyond that, there are some progressive scan …
> fix: improve accuracy of package framerate detection

- meteor/client/styles/_itemTypeColors.scss
- meteor/client/styles/rundownView.scss
- meteor/client/ui/FloatingInspectors/InvalidFloatingInspector.tsx
- meteor/client/ui/SegmentStoryboard/SegmentStoryboard.scss
- meteor/client/ui/SegmentStoryboard/StoryboardPart.tsx
- meteor/client/ui/SegmentTimeline/Parts/InvalidPartCover.tsx
- meteor/client/ui/SegmentTimeline/Parts/SegmentTimelinePart.tsx
Feature
After `invalidReason` stopped being promoted to a notification, there was no way of identifying the reason for an invalid Part.
When hovering over an invalid Part, a floating inspector is shown with a notification about the reason for the invalid state, provided by the Blueprints.
**Status**
> feat(Timeline+Storyboard): Invalid Parts show hover inspector with invalidReason

- meteor/server/api/ingest/mosDevice/diff.ts
* ** (Bug fix, feature, docs update, ...)
Fix
When receiving a sendROMoveStories or some other mos operations, we will regenerate all the segments following the change
For most of those segments, only the rank has changed, which we have a shortcut for. Avoid re-running blueprints for these segments to speed up the ingest operations
**Status**
> fix: avoid regenerating segments when only the rank changes

- packages/documentation/docs/user-guide/installation/installing-package-manager.md
Docs update
Some Powershell users won't be able to start package-manager successfully - they need to add an extra pair of dashes.
The note is added so that all Powershell users who encounter the issue will know how to fix it.
> doc: package manager powershell note

- packages/corelib/src/lib.ts
- packages/corelib/src/mongo.ts
- packages/job-worker/src/__mocks__/collection.ts
- packages/job-worker/src/__tests__/rundown-updatePartInstanceRanks.test.ts
- packages/job-worker/src/blueprints/__tests__/context-adlibActions.test.ts
- packages/job-worker/src/cache/CacheBase.ts
- packages/job-worker/src/ingest/commit.ts
- packages/job-worker/src/playout/adlib.ts
- packages/job-worker/src/playout/cache.ts
- packages/job-worker/src/playout/lib.ts
- packages/job-worker/src/playout/pieces.ts
- packages/job-worker/src/rundown.ts
feature/fix
Rebase of https://github.com/nrkno/sofie-core/pull/696 for r41
Over time, the number of PartInstances loaded into the Cache increases. It only gets reduced when parts/segments are reset, which does not happen automatically (by design)
To avoid the amount of data continually growing, we can limit the PartInstances to be the Segments containing the previous, current and next PartInstances. It might be possible to reduce this further, but this much is a good starting point.
**Status**
> feat: reduce number of loaded PartInstances

- .github/workflows/node.yaml
- meteor/Dockerfile
- meteor/client/styles/rundownListFooter.scss
- meteor/client/ui/RundownList/RundownListFooter.tsx
- meteor/package.json
- meteor/scripts/generate-version-file.js
- meteor/server/api/snapshot.ts
Bug fix: Brings back a broken pipeline feature where the githash would be included in the `package.json` file under `versionExtended` key.
There is no `versionExtended` key in `package.json`
There is a `versionExtended` key in `package.json`. Also, the extended version string (with git hash) is presented in the User Interface, if you hover over the version number.
**Status**
> fix: expose versionExtended (git hash) in package.json on CI build

- meteor/client/ui/Prompter/PrompterView.tsx
- meteor/lib/api/prompter.ts
Bug fix
In non-ideal network situations, it's possible that the Piece/PieceInstance collection updates will not stream at once into the Prompter. If that takes more than 250 ms, then the prompter will update once (without a Piece of script) and then once again (with a Piece of Script shown again).
This change introduces an alternative timer that, if a Script Piece is not present in an update, a 2s delay will wait for that Script Piece to re-appear, before rendering it gone. This in turn, should prevent the Prompter scroll position locking to lock to a new Piece, …
> fix(Prompter): If collection changes are slow, Prompter may receive incomplete updates, and render some Script missing

- meteor/client/styles/shelf/dashboard.scss
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/NextInfoPanel.tsx
- meteor/client/ui/Shelf/PieceCountdownPanel.tsx
Bug fix (UI)
Setting a Scale other than 1 on some dashboard panels (NextInfoPanel and PieceCountdownPanel) affects their position change. Cause: changing fontSize on an element positioned using `em`.
Positioning on these panels is fixed to work exactly as other panels.
The additional variable (`--dashboard-panel-scale`) is not used by these panels, but used by TV 2's keyboard map. Can it stay there?
**Status**
> fix: dashboard panel scale affecting position

- meteor/client/ui/Settings/ConfigManifestSettings.tsx
- meteor/package.json
- meteor/yarn.lock
- packages/blueprints-integration/src/config.ts
- packages/corelib/src/deviceConfig.ts
- packages/package.json
- packages/playout-gateway/src/configManifest.ts
- packages/server-core-integration/src/lib/configManifest.ts
- packages/yarn.lock
This PR updates the code-standard-preset dependency, and as a consequence from this, a deprecated enum (`ConfigManifestEntryType.NUMBER`) has been removed.
> Chore: code standard preset update

- packages/documentation/docs/user-guide/features/prompter.md
- packages/documentation/docs/user-guide/features/sofie-views.mdx
- packages/documentation/versioned_docs/version-1.37.0/user-guide/features/prompter.md
- packages/documentation/versioned_docs/version-1.37.0/user-guide/features/sofie-views.mdx
- packages/documentation/versioned_docs/version-1.38.0/user-guide/features/prompter.md
- packages/documentation/versioned_docs/version-1.38.0/user-guide/features/sofie-views.mdx
Docs update: Fixes a typo in the param for vertical mirroring, which is really called `mirrorv`. Removes a repeated sentence. Makes spelling of _fullscreen_ consistent in the following paragraph (though I think both spellings are correct).
Fixes typo in the example url.
**Status**
> chore(docs): Fix typo and remove repeated sentence

- meteor/server/publications/timeline.ts
- packages/playout-gateway/src/tsrHandler.ts
Co-authored-by: Julian Waller <Julusian@users.noreply.github.com>
Co-authored-by: Johan Nyman <nytamin@users.noreply.github.com>
This PR introduces a guard against non-monotonic timeline resolution
It is possible that, when using the timeline fast-track, an "old" timeline can be sent, even though the new one has already been sent.
The generated timestamp is compared to ensure that "old" timelines aren't sent. This should also probably resolve issues where some sort of NTP-snafu would cause sending multiple timelines, as only one timeline will be sent.
* **Other …
> fix: guard against sending multiple timelines to PoGw

- packages/job-worker/src/playout/playout.ts
Bug fix
Whenever doing any activation, the `devicesMakeReady` method will be called for on the playoutDevices with `okToDestroyStuff` flag set to true.
If the rundown is already active, the `okToDestroyStuff` flag will be set to `false`, which should prevent visible glitches from the playout devices being reset.
**Status**
> fix(Playout): don't destroy stuff going from rehearsal to broadcast

- meteor/client/lib/ConnectionStatusNotification.tsx
- meteor/client/lib/MeteorReactComponent.ts
- meteor/client/lib/ReactMeteorData/ReactMeteorData.tsx
- meteor/client/lib/reactiveData/reactiveDataHelper.ts
- meteor/client/lib/triggers/TriggersHandler.tsx
- meteor/client/ui/ActiveRundownView.tsx
- meteor/client/ui/App.tsx
- meteor/client/ui/ClockView/PresenterScreen.tsx
- meteor/client/ui/Prompter/PrompterView.tsx
- meteor/client/ui/RundownList.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/SegmentStoryboard/SegmentStoryboardContainer.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/client/ui/Settings/SystemManagement.tsx
- meteor/client/ui/Settings/components/triggeredActions/TriggeredActionsEditor.tsx
- meteor/client/ui/Shelf/BucketPanel.tsx
- meteor/lib/api/pubsub.ts
- meteor/server/lib/customPublication.ts
- meteor/server/publications/buckets.ts
- meteor/server/publications/expectedPackages.ts
- meteor/server/publications/lib.ts
- meteor/server/publications/rundown.ts
- meteor/server/publications/studio.ts
- meteor/server/publications/timeline.ts
- meteor/server/security/showStyle.ts
- meteor/server/security/translationsBundles.ts
code quality
Most of the meteor publications are using parameters which are implicitly any. A few were defining types, but many were not.
In the UI, when subscribing to these, there was no type safety in place except for the id of the publication.
Our wrappings around the meteor methods have been updated to have strongly defined typings.
There is an interface describing the possible combinations which with some generics and some infered types, provides us with a type safe usages where typescript knows what the valid parameters are and what we are calling it with.
* …
> feat: strongly type meteor publications

- meteor/client/lib/triggers/TriggersHandler.tsx
Bugfix regarding Action Triggers
MountedAdLibTriggers are lost when ShowStyle config is updated (and in other scenarios causing the tracker in RundownView to rerun)
In a scenario when `isolatedAutorunWithCleanup` is called within an effect, the `currentComputation` might be stopped and replaced, triggering the cleanup, but the effect might not rerun due to the dependencies being identical. Manually stop trackers made with `isolatedAutorunWithCleanup` when no longer needed.
**Status**
> fix: make `isolatedAutorunWithCleanup` independent from `currentComputation`

- meteor/lib/collections/Timeline.ts
- meteor/server/lib/customPublication.ts
- meteor/server/publications/timeline.ts
- packages/job-worker/src/cache/CacheBase.ts
- packages/job-worker/src/cache/CacheObject.ts
- packages/job-worker/src/playout/cache.ts
- packages/job-worker/src/playout/lock.ts
- packages/job-worker/src/playout/playout.ts
- packages/playout-gateway/src/tsrHandler.ts
Bug fix
The `stoppedPlayback` timestamp can be incorrectly reported by the playout gateway, due to Core sending multiples of the same timeline.
The `published` property on the RoutedTimeline is removed, so that subsequent republishings of the same timeline through Timeline fast-track do not trigger a timeline update in playout-gateway. This is especially important when using the 'now' feature.
**Status**
> fix: stoppedPlayback is sometimes incorrectly reported for PartInstances

- meteor/client/ui/Shelf/ExternalFramePanel.tsx
Bug fix
When dragging an object from the external_frame iframe, keyboard shortcuts stop working
Keyboard shortcuts still work.
This has been tested to work
**Status**
> fix: reset focus when dragging from iframe

- meteor/yarn.lock
- packages/blueprints-integration/package.json
- packages/playout-gateway/package.json
- packages/playout-gateway/src/tsrHandler.ts
- packages/yarn.lock
Bug fix
If a device fails to initialize correctly in a `_updateDevices` pass due to a crash or a timeout, it still stays in TSR's "devices" list. Because there is no change in device settings, the device is never retried to initialize, causing it to be potentially stuck forever, even if it could initialize later correctly (say, the hardware device comes back online) and the overall Peripheral Device status cannot be properly evaluated.
Remove them from TSR if they failed to initialize and retry initializing them in `_updateDevices`.
Requires …
> fix(Playout Gateway): remove uninitialized devices from the list

- meteor/server/api/snapshot.ts
- packages/corelib/src/worker/studio.ts
- packages/job-worker/src/playout/snapshot.ts
- packages/shared-lib/src/__tests__/JSONBlob.spec.ts
- packages/shared-lib/src/lib/JSONBlob.ts
Wherever we do JSON.stringify and then JSON.parse() we risk bugs, because JSON.parse accepts `any`.
By using JSONBlob we ensure that typings are kept and it's not as risky to parse strings anymore.
Usage:
```typescript
interface A {
a: number
}
const aBlob: JSONBlob<A> = JSONBlobStringify({ a: 1 })
const a: A = JSONBlobParse(aBlob)
```
> Fix: JSONBlob

- meteor/client/ui/Prompter/PrompterView.tsx
Bug fix
The prompter can scroll to the wrong Part (it scrolls to the Part that _used to_ be the live Part instead of the new live Part.
This happens, because the refresh of the "inner" PrompterView may need to delay update to make sure that all the PieceInstances have streamed in.
The scroll operation scrolls to the specific PartInstance, instead of relying on "live" class being present on the prompter's element.
The PrompterView needs to be rewritten to move away from it's legacy architecture.
**Status**
> fix(Prompter): Prompter doesn't scroll to the correct Part when using followtake

- .github/workflows/node.yaml
fix
The codecov upload action often fails, causing the job to be reported as a failure
https://github.com/nrkno/sofie-core/actions/runs/3235435174/jobs/5299867326
Don't fail if the upload fails  
This is the default behaviour of the action
Additionally, update the action to latest
**Status**
> fix: allow codecov upload to fail

- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownViewEventBus.ts
- meteor/lib/api/triggers/actionFactory.ts
Bug fix
A notification isn't shown when creating a rundown snapshot using a hotkey
The action is piped through the RundownViewEventBus when running in the UI, so that the custom handling for the response from the backend can kick in.
**Status**
> fix(Action Triggers): A notification isn't shown when creating a Rundown Snapshot using a hotkey

- meteor/client/ui/TestTools/TimelineDatastore.tsx
- meteor/client/ui/TestTools/index.tsx
- meteor/lib/api/pubsub.ts
- meteor/lib/collections/TimelineDatastore.ts
- meteor/server/lib.ts
- meteor/server/publications/timeline.ts
- meteor/server/security/collections.ts
- meteor/server/security/studio.ts
- packages/blueprints-integration/src/action.ts
- packages/blueprints-integration/src/api.ts
- packages/blueprints-integration/src/common.ts
- packages/blueprints-integration/src/context.ts
- packages/corelib/src/dataModel/Collections.ts
- packages/corelib/src/dataModel/Ids.ts
- packages/corelib/src/dataModel/TimelineDatastore.ts
- packages/documentation/docs/for-developers/for-blueprint-developers/timeline-datastore.md
- packages/job-worker/src/__mocks__/collection.ts
- packages/job-worker/src/blueprints/context/adlibActions.ts
- packages/job-worker/src/db/collections.ts
- packages/job-worker/src/playout/actions.ts
- packages/job-worker/src/playout/adlib.ts
- packages/job-worker/src/playout/cache.ts
- packages/job-worker/src/playout/datastore.ts
- packages/job-worker/src/playout/playout.ts
- packages/playout-gateway/src/coreHandler.ts
- packages/playout-gateway/src/tsrHandler.ts
- packages/shared-lib/src/core/model/TimelineDatastore.ts
* Implements the Datastore API from the timeline-state-resolver (https://github.com/nrkno/sofie-timeline-state-resolver/pull/219)
* Implements a new TimelinedataStore collection
* Implements a cleanup method and a debug view for said collection
* Implements a blueprint AdlibAction API for the datastore collection
* Splits the AdlibActionContext into 2 such that the blueprints can use a small, fast context for adlib actions utilising only the datastore
**Left todo**
**Status**
> Feat: timeline datastore

- meteor/server/api/blueprints/migrationContext.ts
Even though the typings state it shouldn't be undefined, `settings.devices` is undefined here on a fresh install until at least one subdevice has been added to the playout-gateway. Before this fix, it would have to be added manually via the settings page before any blueprint migrations which also tried to insert devices could run successfully.
It's possible that there is a better place for this fix, but after a couple hours of searching I couldn't find the root cause.
> fix: prevent blueprint migrations which inserted playout-gateway subdevices on a fresh install from failing

- packages/documentation/docs/user-guide/installation/installing-package-manager.md
docs update
A `cd` command in the Package Manager installation instructions points to the wrong path.
The command has been updated to point to the correct path.
N/A
**Status**
> docs(Package Manager): correct cd command in installation instructions

- meteor/client/ui/Status/SystemStatus.tsx
- meteor/yarn.lock
- packages/blueprints-integration/package.json
- packages/playout-gateway/package.json
- packages/playout-gateway/src/coreHandler.ts
- packages/yarn.lock
This PR adds a button on the Viz-device in system status page, which when clicked will trigger a purge of a viz-rundown.
**Status**
> Fix: viz purge rundown

- meteor/server/security/peripheralDevice.ts
Bug fix
When executing any function on a sub-peripheral device (such as "restartCasparCG") and error was thrown: PeripheralDevice "xxxyyyzzz" not found
The device is found, and the function is executed
**Status**
> fix: bug fix: unable to executeFunction on sub-peripheralDevices

- meteor/lib/__tests__/lib.test.ts
- meteor/lib/collections/lib.ts
- meteor/lib/lib.ts
Bug fix
If for example `collection.findFetchAsync` throws instantly (like if providing an invalid argument) `makeReady` rejects right away. Since there is a `sleep(0)` in `collection.findFetchAsync`, the promise is therefore unhandled, thus causing Core to crash.
I've moved the sleep into `makePromise` and ensured that the resulting promise is handled from the start.
**Status**
> Bug fix: change how to wait for other Fibers in collections.*Async

- meteor/lib/collections/PackageInfos.ts
- meteor/server/api/cleanup.ts
- meteor/server/api/integration/expectedPackages.ts
- meteor/server/cronjobs.ts
- packages/corelib/src/dataModel/PackageInfos.ts
- packages/shared-lib/src/peripheralDevice/methodsAPI.ts
This PR adds the property `removeDelay` to PackageInfo, used to delay the removal of a PackageInfo, a feature used by Package Manager.
> Fix: packageInfo removeDelay

- .github/workflows/node.yaml
Fixes the issue where if there are multiple tags, only the first image name is "fully qualified" and can be pushed to the correct repository.
**Status**
> fix: in the event of multiple tags they should all have the correct name

- meteor/client/lib/EditAttribute.tsx
Bug fix
It's impossible to see the value `0`, since it's being replaced by `""`.
Instead of using `||` as fallback, the Int and Float inputs use a `??` operator, which allows the `0` value to show.
(cherry picked from commit 6616b7be6586654b8c9a913682f1b372cbbabd0c)
**Status**
> fix(EditAtribute): Number(0) isn't shown, because it's replaced with String("")

- meteor/__mocks__/helpers/database.ts
- meteor/lib/collections/Studios.ts
- meteor/lib/collections/Timeline.ts
- packages/blueprints-integration/package.json
- packages/blueprints-integration/src/api.ts
- packages/blueprints-integration/src/config.ts
- packages/blueprints-integration/src/content.ts
- packages/blueprints-integration/src/context.ts
- packages/blueprints-integration/src/migrations.ts
- packages/blueprints-integration/src/rundown.ts
- packages/blueprints-integration/src/studio.ts
- packages/blueprints-integration/src/timeline.ts
- packages/blueprints-integration/src/util.ts
- packages/corelib/src/dataModel/Studio.ts
- packages/corelib/src/dataModel/Timeline.ts
- packages/job-worker/package.json
- packages/job-worker/src/playout/lookahead/findObjects.ts
- packages/job-worker/src/playout/lookahead/index.ts
- packages/playout-gateway/package.json
- packages/playout-gateway/src/tsrHandler.ts
- packages/shared-lib/package.json
- packages/shared-lib/src/core/model/Ids.ts
- packages/shared-lib/src/core/model/Timeline.ts
- packages/shared-lib/src/tsr.ts
Feature
Some types are copied between playout-gateway and corelib/meteor, as there is nowhere that they can be placed due to the dependency on tsr/tsr-types.
The tsr-types dependency has been moved from blueprints-integration to shared-lib. While this does mean that some gateways (ingest/package-manager) will have the dependency unnecessarily, it is a small no-dependency library so has little impact on size.
This lets us move some more types into shared-lib, for better reuse across the sofie components.
While some changes were made to …
> fix: refactor playout-gateway types into shared-lib

- meteor/client/ui/RundownView/RundownTiming/RundownTimingProvider.tsx
Bug fix
When queuing a Part at the end of a Playlist, timing information for this Part is not reported. This results in the UI drawing the queued Part and the Playhead incorrectly, in some cases resulting in a Part that is not visible to the user.
If a Part is marked as an `adlib-part` orphan and its parent Segment is found but it cannot otherwise be placed in the list of Parts, the Part is added to the end of the list.
If R49 is closed for contributions then I will rebase onto R50 when a branch is available.
**Status**
> fix: Queued parts at the end of a playlist

- .github/workflows/node.yaml
Bug fix
GHA Node CI fails if there is no tag and it can't push to GHCR
Check if tags are defined before trying to run the GHCR push
**Status**
> fix: check if a push to GHCR is even possible

- packages/job-worker/src/__mocks__/context.ts
- packages/job-worker/src/workers/context.ts
Feature
ShowStyle Variants are not sorted, or sorted using _id.
Uses the `_rank` on ShowStyleVariants to return them sorted.
This is a follow up to roll out ShowStyleVariant ranking to the various places where it can be used for sorting and selecting based on that order.
**Status**
> feat: sorted show style variants

- packages/documentation/docs/user-guide/features/prompter.md
Bug fix, the "showoverunder" parameter was missing from the documentation.
Verified that the parameter works as expected by testing on Xpro1 running 1.44.2-0.
**Status**
> chore: Added missing 'showoverunder' parameter

- packages/shared-lib/src/peripheralDevice/methodsAPI.ts
Bug fix
Package-manager is using r44 libraries which are not as strict on typings.
In r48 this changed with https://github.com/nrkno/sofie-core/pull/788, which exposes the methods in a 'typesafe' way.
A couple of methods were missing on the interface, causing them to not be exposed by server-core-integration
The methods which are already implemented are now exposed in the interfaces, making them available for gateways
**Status**
> fix: missing package-manager methods

- packages/playout-gateway/src/coreHandler.ts
- packages/playout-gateway/src/tsrHandler.ts
Bug fix
Sometimes, when using JSON formatter, log context information is exploded from a string into an object, resulting in an entry looking like this:
```javascript
{0:"H", 1:"e", 2:"l", 3:"l", 4:"o", 5:" ", 6:"W", 7: "o", 8:"r", 9:"l", 10:"d"}
```
This is not good.
Before forwarding context from TSR or attaching the context to the log, the context is sanitized so that it's always an object.
**Status**
> fix(PoGw): resolve issues with reporting context from TSR

- .github/workflows/prune-docker-images.yaml
Prune docker images from GHCR using https://github.com/vlaurin/action-ghcr-prune. <s>I think that with this current configuration this workflow will delete **all untagged images**, but will not delete any tagged images. At least that has been my experience with testing using different combination of the available filters. 
What I would like to be able to do is delete all untagged images, keep all release images and keep 10 feature images. But so far I haven't been able to configure the action like that. If I specify a number of images to keep, untagged images are included in the count. </s>
**This workflow will** 
- Delete all untagged images.
- Keep tags that start with release and version number …
> chore: prune docker images from ghcr

- meteor/client/ui/Settings/ShowStyle/OutputLayer.tsx
- meteor/client/ui/Settings/ShowStyle/SourceLayer.tsx
- meteor/client/ui/Settings/Studio/Mappings.tsx
Fix
While adding various overrides to mappings to work in my local environment I realised that it wasn't possible to easily check where I had made changes without expanding a lot of mappings.
This adds a button to clear the overrides, as a way of indicating that there are overrides. Clicking it will clear the overrides.
For any mappings/layers which were created in the ui and have no blueprint backing, it is shown as disabled, as an indication that it is an override, but it can't be cleared in this way
**Status**
> fix: indicate which layers/mappings have overrides

- packages/job-worker/src/blueprints/__tests__/context-events.test.ts
- packages/job-worker/src/blueprints/context/OnTimelineGenerateContext.ts
This PR is being opened on behalf of [TV 2 Norway](https://github.com/tv2norge).
Bug fix
If two or more lookahead sessions in the same AB pool are active for the same `lookaheadForPartId`, they will receive the same AB session ID even if they are for different sessions (as determined by `sessionName`).
Now, `sessionName` is checked when attempting to find an existing `lookaheadSession`. This is in line with earlier bits in the same function which also check for existing sessions.
**Status**
> fix: don't give out the same lookahead AB session ID to sessions with different names

- packages/blueprints-integration/src/api.ts
- packages/job-worker/src/__mocks__/context.ts
- packages/job-worker/src/blueprints/__tests__/config.test.ts
- packages/job-worker/src/blueprints/config.ts
- packages/job-worker/src/playout/upgrade.ts
- packages/job-worker/src/workers/context.ts
This PR adds the studio's current framerate to the `BlueprintConfigCoreConfig` interface, thereby making it available to blueprints.
The blueprints don't know the framerate of the studio.
A `frameRate` property is available on the `coreConfig` argument provided to `preprocessConfig` and `applyConfig`.
**Status**
> feat: add studio frameRate to coreConfig

- packages/job-worker/src/playout/lib.ts
bug fix
During a headline sequence, take a FULL, then STK, then recue the already played FULL.  
Attempting to take the FULL results in an 'internal server error'
The sequence above is now playable
No task for this, it was found and fixed while testing other playout issues that required running this flow.
I think (but am not 100% sure) that this is safe, as I don't think we allow referencing keyframe ids anywhere else in the timeline. I don't think this will cause problems with length of the ids becoming too long, but I havent verified this …
> fix: ensure keyframes have unique ids

- meteor/lib/mediaObjects.ts
This PR is being opened on behalf of TV 2 Norway.
Bug fix
In the Sofie GUI, messages using this translation render with `{{format}}` visible.
Instead of printing `{{format}}`, the actual intended data is printed.
**Status**
> fix: media format error translation data

- packages/shared-lib/src/package-manager/packageInfo.ts
This PR is being opened on behalf of TV 2 Norway.
Bug fix
The types for `FFProbeDeepScan` unintentionally recurse.
The conflicting interface has been renamed and the `payload` property on `FFProbeDeepScan` updated to point to the renamed interface, instead of itself.
**Status**
> fix: avoid name clash in FFProbeDeepScan types which caused unintended and inaccurate type recursion

- packages/shared-lib/src/package-manager/package.ts
Bug fix
The shared-lib restricts the properties one can set on the `sideEffect` property of an `ExpectedPackage`.
The `sideEffect` property has _known_ properties, but allows the blueprints to specify custom ones, that can, at will, be supported by Package Manager. This uncouples Package Manager from Sofie Core and allows Blueprints to make use of new features in Package Manager, without involving Core, at the expense of lack of strong types.
**Status**
> fix: Package Manager API custom Side-effect

- meteor/lib/api/rundown.ts
- meteor/server/api/ingest/actions.ts
- meteor/server/api/ingest/genericDevice/actions.ts
- meteor/server/api/ingest/lib.ts
- meteor/server/api/rundown.ts
- meteor/server/api/userActions.ts
- packages/corelib/src/error.ts
- packages/job-worker/src/ingest/__tests__/ingest.test.ts
- packages/job-worker/src/ingest/commit.ts
- packages/job-worker/src/ingest/ingestRundownJobs.ts
- packages/job-worker/src/ingest/lock.ts
- packages/job-worker/src/ingest/mosDevice/__tests__/mosIngest.test.ts
feature
When the user clicks delete for a Rundown in the Lobby, if the Rundown is active the delete will fail and no failure is reported to the user.
An error message will be shown when the delete fails.  
This will be shown when the rundown is either already orphaned, or when the rundown transitions into being orphaned
**Status**
> feat: report inability to remove rundown to the caller SOFIE-1131

- meteor/client/styles/rundownView.scss
- meteor/client/ui/FloatingInspectors/VTFloatingInspector.tsx
Styling tweaks for improved usability.
Removed the "Clip: " filename label from hover pop-ups for clips.
Restyled the clip filename text to be less prominent.
Made the hover pop-ups slightly more space-optimized by shrinking the the pop-up's icon and tightening some margins.
Tweaked the segment header notice counter so that it looks better with multi-digit numbers. Tweaked the same counter's background to appear more circular.
**Status**
> chore: Removed the "Clip: " filename label from hover pop-ups for clips.

- meteor/__mocks__/helpers/jest.ts
- meteor/server/api/__tests__/userActions/mediaManager.test.ts
Add `waituntil()` function, for use in tests
Sometimes tests fail randomly, [such as this one](https://github.com/nrkno/sofie-core/actions/runs/4490302734/jobs/7897200526), because they are dependent on time, and the tests run slow sometimes in CI.
CI tests are more roboust. `waituntil` runs the test preducate multiple times until it passes (or times out).
> chore: add waituntil() function for use in unit tests

- packages/job-worker/src/playout/lookahead/__tests__/findForLayer.test.ts
- packages/job-worker/src/playout/lookahead/__tests__/findObjects.test.ts
- packages/job-worker/src/playout/lookahead/__tests__/lookahead.test.ts
- packages/job-worker/src/playout/lookahead/findForLayer.ts
- packages/job-worker/src/playout/lookahead/findObjects.ts
- packages/job-worker/src/playout/lookahead/index.ts
- packages/job-worker/src/playout/lookahead/util.ts
- packages/job-worker/src/playout/timeline/generate.ts
- packages/job-worker/src/playout/timeline/rundown.ts
bug fix
lookahead can add an timed object referencing an object in an inTransition piece that is not on the timeline
these pieces are filtered before lookahead searches them for objects.
**Status**
> fix: lookahead loading skipped wipe for remainder of the part SOFIE-2168

- meteor/client/lib/__tests__/rundownTiming.test.ts
- meteor/client/lib/rundownTiming.ts
- meteor/client/ui/RundownView/RundownTiming/CurrentPartRemaining.tsx
- meteor/client/ui/RundownView/RundownTiming/RundownTimingProvider.tsx
This PR has been opened by SuperFly.tv on behalf of EVS Broadcast Equipment.
Bug fix.
When taking from one Part to another, the timing data for the previous Part lingers in the context provided by the `RundownTimingProvider` and is provided to the `CurrentPartRemaining` component. This results in the coundown continuing to display the countdown for the previous Part.
To fix this issue, two measures have been taken:
1. The `RundownTimingProvider` now reports what the `currentPartInstanceId` was when it performed the timing calculation as part of the `RundownTimingContext` …
> Fix: out of sync playhead countdown

- meteor/client/ui/RundownView.tsx
- meteor/client/utils/globalStores.ts
- meteor/lib/api/pubsub.ts
- meteor/lib/mediaObjects.ts
- meteor/server/publications/studio.ts
Bug fix
The `PackageContainerPackageStatus` collection can be very reactive, because the `modified` field is getting updated all the time as Package Manager is working. This can cause components to re-render for no reason, other than receiving a new object through a cursor (due to the `modified` having changed).
A new publication for `PackageContainerPackageStatus` is created that omits the `modified` field. This should limit the amount of reactivity on the wire and in the Rundown View, where the `modified` field isn't used anyway. …
> fix: lower reactivity for PackageContainerPackageStatus

- packages/corelib/src/playout/__tests__/pieces.test.ts
- packages/corelib/src/playout/pieces.ts
Bug fix
When creating the `piece_group_control` it has classes provided from the caller. This array is being reused across all the groups in the part, resulting in them using the same array reference.
When `onTimelineGenerate` modifies this property, it gets applied to every piece in the part
Clone the `classes` array before using it
One of the timelineObjects I found. I was testing a lot of rapid camera cuts.
```
{
"id" : "piece_group_control_kSk7b8NmS96qmHZREy_kckQ02DQ__KFnLAQcCicZr8xhYw_4PCDeCegxyTeSnSqk",
"objectType" : "rundown", …
```
> fix: piece group objects within a part bleeding classes

- meteor/server/api/client.ts
Bug fix
When you open the Package Manager peripheral device Status page, Core can crash with an uncaught exception, if the device is not assigned to a studio.
The thrown error will be returned back to the client instead of crashing Core.
**Status**
> fix: Package Manager status page crash

- meteor/server/publications/lib/ReactiveCacheCollection.ts
- packages/shared-lib/src/lib/__tests__/protectedString.spec.ts
- packages/shared-lib/src/lib/protectedString.ts
Adds toString() to ProtectedString
This is to make linters like SonarLint happy, so that they don't think that stringifying a ProtectedString results in an "[object: object]"
> chore: add toString() to ProtectedString

- meteor/client/ui/SegmentTimeline/Parts/SegmentTimelinePart.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SmallParts/SegmentTimelinePartHoverPreview.tsx
Bug fix
The squiggly budget gap line rarely lines up with the editorial line:
It always lines up: 
**Status**
> fix: update budget gap line calculations to prevent it from extending past the editorial line

- scripts/install-and-build.mjs
- scripts/run.mjs
Bug fix
Sofie fails to start on certain environments, such as within the [`pm2`](https://pm2.keymetrics.io/) process manager.
Sofie starts in these environments.
I'm surprised that this isn't better documented or that it isn't in the types, but the entire `hasColors` function can be _missing_ under certain execution conditions. This PR checks for it before attempting to use it.
**Status**
> fix: on some terminals, hasColors is undefined

- meteor/client/lib/__tests__/rundownTiming.test.ts
- meteor/client/lib/rundownTiming.ts
- meteor/client/lib/ui/pieceUiClassNames.ts
- meteor/client/styles/rundownView.scss
- meteor/client/ui/SegmentContainer/PieceElement.tsx
- meteor/client/ui/SegmentTimeline/Parts/FlattenedSourceLayers.tsx
- meteor/client/ui/SegmentTimeline/Parts/OutputGroup.tsx
- meteor/client/ui/SegmentTimeline/Parts/SegmentTimelinePart.tsx
- meteor/client/ui/SegmentTimeline/Parts/SourceLayer.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.scss
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SmallParts/SegmentTimelinePartHoverPreview.tsx
- meteor/client/ui/SegmentTimeline/SmallParts/SegmentTimelineSmallPartFlag.tsx
- meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
Bug fix
There are some problems with rendering Small Parts in the Timeline view after #903 was merged.
Before:
As it's visible, the Small Parts overlay is not correctly aligned (it's not in the correct position of the timeline), the flags are incorrectly placed, etc. Also, the "Parts duration" counter incorrectly shows the "display duration" instead of the actual "expected duration" sum of the Parts.
There should be no problems with Small Parts. Also, the "relative" rendering mode for Parts was removed, because the only place that used it was the Small Parts …
> fix: small parts after #903

- meteor/client/lib/forms/SchemaFormTable/ArrayTable.tsx
- meteor/client/lib/forms/SchemaFormTable/ObjectTable.scss
- meteor/client/lib/forms/SchemaFormTable/ObjectTable.tsx
- meteor/client/lib/forms/SchemaFormTable/TableEditRow.tsx
Feature
Nested config tables are not allowed.
Nested config tables are allowed.
Nested tables have alternating white and light gray background colors, as well as cumulative 10px left indents per each level. Only tables up to 4 levels deep will be styled. If someone actually needs more than that, we can amend the CSS.
**Status**
> feat: allow nested config tables

- packages/job-worker/src/playout/timeline/generate.ts
Bug fix
Adding children to a timeline object group causes an error saying there are no children in the timeline object group.
Instead of deleting the `children` array after flattening its children out, this instead replaces it with an empty one, to make `superfly-timeline` happy and prevent it from throwing in `validateTimeline`.
**Status**
> fix: don't error when flattening timeline group children

- meteor/server/publications/peripheralDeviceForDevice.ts
- packages/shared-lib/src/core/model/peripheralDevice.ts
This PR has been opened by SuperFly.tv on behalf of EVS Broadcast Equipment.
Bug/regression fix.
Previously, gateways such as the Spreadsheet Gateway would be able to retrieve OAuth settings from Core, but this data is currently unavailable.
The missing OAuth information has been added to the `PeripheralDeviceForDevice` custom publication.
**Status**
> fix: Expose OAuth credentials to peripheral device

- packages/blueprints-integration/src/common.ts
This PR has been opened by SuperFly.tv on behalf of EVS Broadcast Equipment.
Bug fix
JSON config values are stored in the database as JSON objects, but the config presets can't provide objects as defaults in all cases (notably within tables).
Presets can provide an arbitrary object as a config value for use with JSON config types.
**Status**
> fix: Allow JSON objects in config presets

- meteor/client/styles/rundownView.scss
- meteor/client/ui/SegmentStoryboard/SegmentStoryboard.scss
Bug fix.
Currently, Timeline and Storyboard segment views on the Rundown page won't break in case the viewport size is too small (narrow).
With these changes, both Timeline and Storyboard segments will break the same as the List segment breaks.
**Status**
> fix: timeline and storyboard view break

- meteor/server/lib/customPublication/optimizedObserverBase.ts
- packages/mos-gateway/src/coreHandler.ts
- packages/mos-gateway/src/mosHandler.ts
- packages/playout-gateway/src/coreHandler.ts
- packages/playout-gateway/src/tsrHandler.ts
bug fix
when reconnecting to core, playout and mos gateway are both manually restarting their subscriptions, as well as the subscriptions automatically restarting themselves. 
Additionally, it was found that each time a subdevice was started/restarted in playout-gateway it would start a new subscription to its `PeripheralDeviceCommands`, and would not stop subscriptions when stopping/restarting the subdevice, causing that number to grow. This is particularly problematic when the subdevice is crashing, or unable to connect for a while, as each restart attempt would result in an additional subscription.
In mos-gateway, when …
> fix: gateway subscription leaking SOFIE-2442

- meteor/__mocks__/defaultCollectionObjects.ts
- meteor/client/ui/Settings/Studio/Generic.tsx
- meteor/lib/api/rest.ts
- meteor/server/api/playout/DOCS.md
- meteor/server/api/rest/v1/typeConversion.ts
- meteor/server/api/studio/api.ts
- meteor/server/migration/0_1_0.ts
- meteor/server/migration/X_X_X.ts
- meteor/server/migration/__tests__/migrations.test.ts
- meteor/server/publications/pieceContentStatusUI/__tests__/checkPieceContentStatus.test.ts
- packages/corelib/src/dataModel/Studio.ts
- packages/job-worker/src/__mocks__/defaultCollectionObjects.ts
- packages/job-worker/src/blueprints/__tests__/config.test.ts
- packages/job-worker/src/ingest/__tests__/ingest.test.ts
- packages/job-worker/src/playout/__tests__/playout.test.ts
- packages/job-worker/src/playout/take.ts
- packages/shared-lib/src/core/constants.ts
Feature
The minimum take span is hardcoded to 1000ms.
The minimum take span may now be configured on a per-studio basis:
**Status**
> feat: make the minimum take span configurable on a per-studio basis

- meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
Changes the timing of the hoverscrub to be calculated every frame.
When hovering over a moving part without moving the mouse, the hoverscrub will be paused even though the piece is moving underneath the mouse.
Hoverscrub accurately reflects the position of the mouse, regardless of whether it is being moved.
**Status**
> fix: seek time for hoverscrub while playing

- meteor/lib/mediaObjects.ts
Bug fix
If Package Manager produces a Package Status with a value unknown to Core, the Piece will be shown without zebras, as that will register as an "UNKNOWN" state.
An unknown Package Status will be translated to a `SOURCE_MISSING` Piece status.
**Status**
> fix: add fallback for unknown package statues SOFIE-2468

- meteor/client/ui/SegmentList/LinePartTimeline.tsx
- meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
- meteor/client/ui/SegmentTimeline/Renderers/VTSourceRenderer.tsx
Bug fix
The rundown view shows a countdown-to-freeze and freeze frame icicles for looping media.
These things are no longer shown for looping media.
**Status**
> fix: hide countdown and icicles on looping media

- meteor/client/lib/rundownTiming.ts
- meteor/client/ui/SegmentList/LinePartTimeline.tsx
Bugfix
If a Part has `expectedDuration: 0` the countdown to the end of that Part, next to the "onAir" line, always counts from "0:00" and up.
If a Part has `expectedDuration: 0` and is a member of a displayDurationGroup, the countdown will start at whetever is left in that displayDurationGroup and count down "through" "0:00" and up.
Also, some duplicated code was removed in the rundown timing calculator.
**Status**
> fix(Timing): expectedDuration=0 members of displayDuration groups countdown don't inherit displayDurationGroup duration

- meteor/client/collections/index.ts
- meteor/client/ui/ClipTrimPanel/ClipTrimDialog.tsx
- meteor/client/ui/ClipTrimPanel/ClipTrimPanel.tsx
- meteor/client/ui/SegmentTimeline/withMediaObjectStatus.tsx
- meteor/lib/api/pubsub.ts
- meteor/server/publications/studio.ts
code cleanup 
This was used in an attempt to get the previewUrl of a piece. This would not work with package-manager, and involved more complexity than necessary.
The previewurl is now taken from the piece content status publication.
To help achieve this, the component was rewritten to be functional.
The `MediaObjects` publication is now unused, so has been removed
**Status**
> feat: remove MediaObjects collection from client SOFIE-2402

- meteor/client/ui/Prompter/prompter.ts
- packages/blueprints-integration/src/documents/part.ts
- packages/job-worker/src/blueprints/context/lib.ts
feature
The same part title is used for the prompter, countdown and rundown views.
However, in the prompter we don't have any more information about the part other than the title (elsewhere we have at least the type).  
This lets the blueprints specify a part title specifically for the prompter. This can be as detailed or not as they wish. If unset, the normal title property is used, so this will have no impact unless explicitly set.
**Status**
> feat: add `prompterTitle` property SOFIE-2404

- meteor/server/publications/packageManager/expectedPackages/contentCache.ts
- meteor/server/publications/packageManager/expectedPackages/contentObserver.ts
- meteor/server/publications/packageManager/expectedPackages/publication.ts
- meteor/server/publications/pieceContentStatusUI/bucket/bucketContentCache.ts
- meteor/server/publications/pieceContentStatusUI/bucket/bucketContentObserver.ts
- meteor/server/publications/pieceContentStatusUI/bucket/publication.ts
- meteor/server/publications/pieceContentStatusUI/rundown/publication.ts
- meteor/server/publications/pieceContentStatusUI/rundown/reactiveContentCache.ts
- meteor/server/publications/pieceContentStatusUI/rundown/rundownContentObserver.ts
- meteor/server/publications/segmentPartNotesUI/publication.ts
- meteor/server/publications/segmentPartNotesUI/reactiveContentCache.ts
- meteor/server/publications/segmentPartNotesUI/rundownContentObserver.ts
bug fix
The custom publications are based around watching (observing) changes to mongo collections, and triggering the publication to be re-evaluated when this happens. The granularity to these re-evaluations varies depending on the publication and what changed.
Due to the nature of our data model, and how the subscriptions are setup, some of these observers and invalidations are more complex than others. In some cases we have observers which depend on the documents that match other observers.  
For example the `UISegmentPartNotes` publication is subscribed to for a `RundownPlaylist`. We are then watching the segments and …
> fix: custom publications overly reactive

- packages/job-worker/src/blueprints/context/SyncIngestUpdateToPartInstanceContext.ts
- packages/shared-lib/src/core/constants.ts
This PR makes sure a blueprint can not update the length of an autonext part instance to be shorter than the time it has been on-air for
Setting a shorter time is allowed and doing this will cause the playout-gateway to believe the next part should have been playing for x seconds already, which looks _quite_ ugly on air.
**Status**
> fix: Duration update while on air trips up autonext (Sofie 1599)

- packages/blueprints-integration/src/context.ts
- packages/job-worker/src/blueprints/context/ShowStyleContext.ts
Feature
It is not possible for blueprints to get the full, dynamic list of Source and Output layers from the ShowStyle.
The above operations are now possible.
**Status**
> feat: allow getting the Source and Output layers from the ShowStyle context

- packages/documentation/docs/for-developers/for-blueprint-developers/intro.md
- packages/documentation/docs/for-developers/intro.md
- packages/documentation/docs/for-developers/libraries.md
- packages/documentation/docs/for-developers/worker-threads-and-locks.md
- packages/documentation/docs/user-guide/concepts-and-architecture.md
- packages/documentation/docs/user-guide/configuration/settings-view.md
- packages/documentation/docs/user-guide/features/api.md
- packages/documentation/docs/user-guide/features/prompter.md
- packages/documentation/docs/user-guide/features/sofie-views.mdx
- packages/documentation/docs/user-guide/further-reading.md
- packages/documentation/docs/user-guide/installation/initial-sofie-core-setup.md
- packages/documentation/docs/user-guide/installation/installing-a-gateway/intro.md
- packages/documentation/docs/user-guide/installation/installing-a-gateway/rundown-or-newsroom-system-connection/installing-sofie-with-google-spreadsheet-support.md
- packages/documentation/docs/user-guide/installation/installing-a-gateway/rundown-or-newsroom-system-connection/mos-gateway.md
- packages/documentation/docs/user-guide/installation/installing-blueprints.md
- packages/documentation/docs/user-guide/installation/installing-connections-and-additional-hardware/README.md
- packages/documentation/docs/user-guide/installation/installing-connections-and-additional-hardware/casparcg-server-installation.md
- packages/documentation/docs/user-guide/installation/installing-connections-and-additional-hardware/vision-mixers.md
- packages/documentation/docs/user-guide/installation/installing-package-manager.md
- packages/documentation/docs/user-guide/installation/installing-sofie-server-core.md
- packages/documentation/docs/user-guide/installation/intro.md
- packages/documentation/docs/user-guide/intro.md
Fix links in the documentation that did not end in `.md`
https://github.com/nrkno/Sofie-TV-automation/issues/54
Links end in `.md`, see https://github.com/facebook/docusaurus/issues/8693#issuecomment-1441547554 as to why this is nexessary
**Status**
> chore: fix documentation linking

- meteor/server/publications/pieceContentStatusUI/checkPieceContentStatus.ts
Bug fix
Audio-only pieces will often display a warning about their corresponding files missing video.
This warning has been disabled for pieces which reside on an `AUDIO` source layer. If there is a better heuristic, let me know.
**Status**
>  fix: don't display a warning when an audio piece is missing video

- meteor/client/ui/Status/SystemStatus.tsx
Also set all other properties of the modal to match a similar modal with the same message, presented somewhere else in the system - for consistency.
Fix
Modal title says "Delete"
Modal title says "Restart"
Also, conforms this modal to another similar one for consistency.
**Status**
> fix: Changes the wrong title "Delete" to "Restart".

- meteor/client/lib/forms/SchemaFormForCollection.tsx
- meteor/client/lib/forms/SchemaFormInPlace.tsx
- meteor/client/lib/forms/SchemaFormTable/ArrayTable.tsx
- meteor/client/lib/forms/SchemaFormTable/ArrayTableRow.tsx
- meteor/client/lib/forms/SchemaFormTable/ObjectTable.tsx
- meteor/client/lib/forms/SchemaFormTable/TableEditRow.tsx
- meteor/client/lib/forms/SchemaFormWithOverrides.tsx
- meteor/client/lib/forms/schemaFormUtil.tsx
- meteor/client/ui/Settings/BlueprintConfigSchema/CategoryEntry.tsx
- meteor/client/ui/Settings/Studio/Devices/GenericSubDevices.tsx
- meteor/client/ui/Settings/Studio/Mappings.tsx
- packages/documentation/docs/for-developers/json-config-schema.md
feature
The `required` field in the schema defines whether the typescript property comes out as optional.
This can be useful to use in some cases, to mark a dropdown as being allowed to have no value selected.
In particular, this is useful in combination with the sofie-enums, to allow for 0-1 values to be selected.  
This change informs each control about whether it is marked as required, and utilises this for the dropdowns to add a 'None' value
**Status**
> feat: respect json schema required field in ui SOFIE-2436

- meteor/client/styles/customizations/nrk/shelf/taPanel.scss
- meteor/client/styles/customizations/readme.md
- meteor/client/ui/Shelf/DashboardPanel.tsx
Feature
Enables DashboardPanel to render CustomClasses for overriding CSS styling.
Adds a NRK-specific styling file providing "RK5/TA-panel" styles intended to be used by shelf panels.
**Status**
> feat: DashboardPanel adds customClasses to DashboardPanel

- packages/live-status-gateway/src/topics/activePlaylist.ts
Bug fix
Adlib names have unprocessed interpolation markers in them, such as `{{fileName}}`.
These strings are now properly interpolated.
**Status**
> fix(LiveStatus): interpolate adlib names

- packages/job-worker/src/playout/abPlayback/abPlaybackSessions.ts
- packages/job-worker/src/playout/pieces.ts
bug fix
Sofie resolves the piece timeline, to be able to provide concrete times to the ab resolved, `onTimelineGenerate` and other places.  
If a piece is resolved to have a duration of 0, that gets lost during the resolving, so that it ends up with no duration.
It now treats a duration of 0 as a valid value, preserving it rather than replacing it with undefined.
Some minor tweaks have been made so that lookahead ab sessions use a start time that is json serializable, as this confused us while …
> fix: zero duration pieces breaking ab resolver

- meteor/yarn.lock
- packages/blueprints-integration/package.json
- packages/playout-gateway/package.json
- packages/playout-gateway/src/coreHandler.ts
- packages/playout-gateway/src/index.ts
- packages/playout-gateway/src/tsrHandler.ts
- packages/yarn.lock
This includes a couple of fixes for playout-gw:
- Device settings were not retrieved on start up, this caused the TSR to start in single-threaded mode
- Logs made from console.log in libraries would only show the first argument, more arguments would be put on the object (i.e. `console.log(123, 'a log')` result in `{ 0: "a", 1: " ", 2: "l", 3: "o", 4: "g" , message: 123}`)
- Errors logged from the devices using `.emit('error', ...)` now serialise the emitted error correctly (previously would just log en empty object)
- Bumped TSR improving terminate implementation of multiple devices
**Status**
> sisyfos use multiple restarts to create stable connection (Sofie 2576)

- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
This updates the scroll behaviour for the "go to part" action, as is used when clicked on part identifiers 
Inconsistent zoom and scroll
Mostly* consistent zoom and scroll. Part should fill up the space between the 2 red lines, denoted by where the next line should be in a playing part and the space left on the right side with default sizing. (As indicated by blue arrows)
\* some edge cases remain, but they are either not easily fixable or not very problematic..
**Status**
> fix: go-to-part action

- packages/server-core-integration/src/lib/process.ts
Bug fix
`server-core-integration` uses an undeclared `winston` dependency.
Replace the `winston` type import with an internal interface definition of a common logger, for more logging flexibility.
Fixes #925 
**Status**
> fix(Server Integration): don't rely on winston types in `server-core-integration`, have own logger interface

- meteor/__mocks__/helpers/jest.ts
- meteor/server/__tests__/cronjobs.test.ts
- meteor/server/api/__tests__/peripheralDevice.test.ts
- meteor/server/publications/lib/__tests__/rundownsObserver.test.ts
Modify some unit tests that often time out due to that we triggered the Fake Timers a lot. Now, we're using waitUntil() and trigger the Fake Timers less times in between each check
Tests often fail randomly, likely due to the CI worker is under heavy CPU load.
Reduced risk of randomly failing tests
> Chore: Fix time based tests

- meteor/lib/api/rest/v1/playlists.ts
- meteor/lib/api/triggers/actionFactory.ts
- meteor/server/api/rest/v1/playlists.ts
- packages/job-worker/src/workers/studio/child.ts
fix
when a useraction calls into the job-worker, an expected failure will result in an error log line of that expected failure
those failures are now logged at the info level
This also includes a fix for a stable api endpoint where it was returning an error instead of throwing it.
**Status**
> fix: don't log UserError messages at error level from the job-worker SOFIE-2592

- .github/pull-request-template.md
- .github/workflows/node.yaml
Code test coverage information on release branches does not seem to be reliable. It is not very informative and obscures the "at a glance" quality of the CI pipeline we have by producing false negatives.
"Send coverage" set will not be executed on release branches.
**Status**
> chore: do not send code test coverage to CodeCov on release branches

- meteor/client/lib/triggers/TriggersHandler.tsx
Bug fix
An error is reported when an empty "Keyboard" trigger is created in Action Triggers
"Empty" Keyboard combos are ignored.
**Status**
> fix: Ignore empty hotkey triggers (SOFIE-2702)

- meteor/server/api/__tests__/peripheralDevice.test.ts
- meteor/server/api/peripheralDevice.ts
- packages/playout-gateway/src/coreHandler.ts
- packages/server-core-integration/src/lib/coreConnection.ts
This PR attempts to fix a memory-leak/crash we've seen in a production environment.
Playout Gateway was in an initialization loop, where it was unable to initialize some devices (likely due to a network issue). This caused issues in Core, eventually leading to out-of-memory and crash.
(Not tested yet) Reduced load on Core, when Playout Gateway re-initializes devices.
**Status**
> Fix: Memory leak on initialize loop (SOFIE-2632)

- packages/live-status-gateway/src/collections/adLibActions.ts
- packages/live-status-gateway/src/collections/adLibs.ts
- packages/live-status-gateway/src/collections/globalAdLibActions.ts
- packages/live-status-gateway/src/collections/globalAdLibs.ts
- packages/live-status-gateway/src/coreHandler.ts
Bug fix.
The Live Status Gateway doesn't populate a list of AdLibs until the first Part of a Rundown is taken.
The list is now populated on activate.
This PR also includes a fix for a bug where the Live Status Gateway would not restart when requested.
**Status**
> fix: AdLibs don't appear in Live Status Gateway until first take

- meteor/client/ui/Settings/DeviceSettings.tsx
- meteor/client/ui/Status/SystemStatus.tsx
- meteor/lib/clientUserAction.ts
Bug fix
`Uncaught error happened in GUI: ***Unknown error in handleAccept***` is printed to the log in certain cases
The problem was that we didn't persist the React event in once case, meaning that it got recycled, loosing it's type information by the time we tried to construct `eventContextForLog`. The event should now be persisted for creating the log entry. Also, the log line produced if the context can't be created should now be much easier to understand and pin down to a source.
**Status**
> fix: Initiating restart from status page could end up with an "N/A" event context

- meteor/client/lib/clientAPI.ts
- meteor/client/ui/RundownView.tsx
- meteor/lib/api/client.ts
- meteor/server/__tests__/cronjobs.test.ts
- meteor/server/api/client.ts
- meteor/server/api/peripheralDevice/executeFunction.ts
- meteor/server/cronjobs.ts
- packages/playout-gateway/src/tsrHandler.ts
fix
The handling of cronjob CasparCG restarts is improved to produce more better errors, and minimise logging at the error level.
Additionally, some typings for the ui have improved for executing tsr actions.
This relies on https://github.com/nrkno/sofie-timeline-state-resolver/pull/295 for accurate logging
**Status**
> fix: CasparCG restart error: Timeout after 10000ms SOFIE-2588

- meteor/server/api/ExternalMessageQueue.ts
- meteor/server/api/cleanup.ts
Bug fix
This is a couple of lines that look to be actual bugs, when I found when enabling `noImplicitAny` in the typescript config
**Status**
> fix: avoid doing `[0]` on a promise instead of on the awaited result

- packages/job-worker/src/playout/adlibAction.ts
bug fix
Bucket adlib-actions can and should generage expectedPackages for their media.  
But they cannot use the `listenForPackageUpdates` flow to be regenerated when this changes.  
They also cannot fetch any generated package infos when they are executed
This allows them to fetch any generated package infos when they are executed.  
While not the full flow implementation, this is the easy and safe portion which allows bucket adlib-actions to execute with knowledge on the status of their expectedpackages
**Status**
> fix: allow BucketAdlibAction to access PackageInfos SOFIE-2655

- packages/blueprints-integration/src/abPlayback.ts
- packages/corelib/src/dataModel/RundownPlaylist.ts
- packages/job-worker/src/playout/abPlayback/__tests__/abPlayback.spec.ts
- packages/job-worker/src/playout/abPlayback/abPlaybackResolver.ts
- packages/job-worker/src/playout/abPlayback/applyAssignments.ts
- packages/shared-lib/src/core/model/Timeline.ts
This PR has been opened by SuperFly.tv on behalf of EVS Broadcast Equipment (henceforth EVS).
Feature change.
A/B players must be referred to by numeric index.
Player Ids can be provided as strings.
**Status**
> feat: A/B player Ids as strings

- packages/openapi/api/definitions/playlists.yaml
An OpenAPI definition update, which can be considered a fix for those who use the OpenAPI definitions to generate client code
`/playlists/{playlistId}/set-next-segment` is defined to use the PUT method, but it has been agreed [and implemented](https://github.com/nrkno/sofie-core/blob/7fbcbaf362833eb98a0c0a4d2d4430e3c352c50a/meteor/server/api/rest/v1/index.ts#L1455-L1457) to use POST
The OpenAPI definition for `/playlists/{playlistId}/set-next-segment` defines a POST method
**Status**
> fix(openapi): change setNextSegment method to POST instead of PUT

- packages/job-worker/src/playout/__tests__/timeline.test.ts
- packages/job-worker/src/playout/adlibUtils.ts
- packages/job-worker/src/playout/model/PlayoutPartInstanceModel.ts
- packages/job-worker/src/playout/model/implementation/PlayoutPartInstanceModelImpl.ts
- packages/job-worker/src/playout/take.ts
- packages/job-worker/src/playout/timeline/generate.ts
- packages/job-worker/src/playout/timeline/multi-gateway.ts
bug fix
Using the 'play from here' context menu option will always play from the start of the selected part
It now plays from the correct point within the part
**Status**
> fix: Playout ignores 'Play from here' offset SOFIE-2356

- packages/live-status-gateway/api/schemas/segments.yaml
- packages/live-status-gateway/src/topics/__tests__/segmentsTopic.spec.ts
- packages/live-status-gateway/src/topics/segmentsTopic.ts
A feature: new property exposed by the Live Status Gateway in the `segments` topics.
Segment identifier is not available to subscribers of the LSG.
Segment identifier is available to subscribers of the LSG.
**Status**
> feat(live-status-gw): segment identifiers

- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
Bug fix in the GUI.
Segment identifier is shown twice: it appears in its usual place and at the bottom of the container.
Segment identifier is shown only once, where it's expected.
**Status**
> fix: Duplicated segment identifiers in the GUI

- meteor/client/ui/TestTools/DeviceTriggers.tsx
- meteor/server/api/deviceTriggers/StudioObserver.ts
Bug fix
When a Rundown is reset, the `deviceTriggersPreview` publication becomes empty.
The `deviceTriggersPreview` is correctly refreshed after a rundown reset.
**Status**
> fix: mounted device triggers preview reset rundown issue

- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
This is a Bug fix
The Rundown View can crash under some circumstances
> fix: Cannot read properties of undefined (reading 'parentElement') at startLive SOFIE-2772

- meteor/client/ui/Settings/SnapshotsView.tsx
- meteor/client/ui/Status/SystemStatus.tsx
> chore: refactor SystemStatus and SnapshotsView to avoid MeteorReactComponent SOFIE-2751

- meteor/client/ui/Settings/RundownLayoutEditor.tsx
> chore: refactor RundownLayoutEditor to avoid MeteorReactComponent SOFIE-2751

- meteor/client/ui/Status/ExternalMessages.tsx
> chore: refactor Status/ExternalMessages to avoid MeteorReactComponent SOFIE-2751

- meteor/client/ui/TestTools/Mappings.tsx
- meteor/client/ui/TestTools/index.tsx
> chore: refactor TestTools to avoid MeteorReactComponent SOFIE-2751

- meteor/client/ui/RundownView.tsx
- meteor/client/ui/RundownView/RundownSystemStatus.tsx
- meteor/client/ui/Shelf/ShelfDashboardLayout.tsx
- meteor/client/ui/Shelf/SystemStatusPanel.tsx
> chore: refactor `RundownSystemStatus` to avoid `MeteorReactComponent` SOFIE-2751

- packages/job-worker/src/cache/lib.ts
- packages/job-worker/src/ingest/ingestCache.ts
- packages/job-worker/src/playout/timings/timelineTriggerTime.ts
This is a: Code improvement
This reworks a couple of loose usages of `DbCacheWriteCollection`, as a precursor to the main SOFIE-2672 PR which wants to remove this class.
While it does add a bit of complexity to these usages, it means the much more complex blob of `DbCacheWriteCollection` can be removed soon, so it is worth the limited complexity in these locations.
The `diffAndStoreObjects` method will be used by SOFIE-2672 elsewhere too.
> feat: remove some usages of `DbCacheWriteCollection` SOFIE-2672

- meteor/server/api/deviceTriggers/RundownContentObserver.ts
> fix: cleanup for deviceTriggers RundownContentObserver failing SOFIE-2834

- meteor/client/lib/ReactMeteorData/ReactMeteorData.tsx
- meteor/client/ui/RundownView.tsx
> chore: refactor RundownView to avoid MeteorReactComponent SOFIE-2751

- meteor/server/publications/packageManager/expectedPackages/generate.ts
- meteor/server/publications/pieceContentStatusUI/rundown/regenerateItems.ts
This fixes two bugs:
1) When adlibbing pieces, the package status checks for the adlibbed pieces would never be ok.
2) the package manager expected packages publication was not deleting packages correctly, causing it to grow until package manager restarted
> fix: package status bugs SOFIE-2836

- packages/openapi/api/actions.yaml
- packages/openapi/api/definitions/showstyles.yaml
This PR is contributed by me.
This is a
The ShowStyleVariant specification contains what amounts to a syntax error, with the `required` and `additionalProperties` mis-indented.
Syntax error is fixed.
Also, the `x-logo` OpenAPI extension is used to provide a logo for the generated docs, if supported.
No testing required.
> fix(OpenAPI): ShowStyleVariants `additionalProperties` and `required` properties were mis-indented

- meteor/client/ui/Shelf/ExternalFramePanel.tsx
When dropping an item from a mos plugin into Sofie, the item should be an `ncsItem`. The main slug-property of an ncsItem is called `itemSlug`. However, Sofie is expecting to read a property called `objSlug`, which pr. definition doesn’t exist on ncsItems.
If a mos plugin provides an on-spec ncsItem, Sofie will fail to read its slug.
Sofie will try to correctly look for a property of itemSlug, then fall back to the old behaviour of wrongly looking for objSlug. Meaning this change is backwards compatible/non-breaking.
Dropping this snippet into a Bucket will prior to this fix lead to `bucketAdlibImport` running with an empty string as the name property. After this fix, the string "ExampleClip" should appear as the name …
> fix: looks for the correct property itemSlug on ncsItems

- packages/server-core-integration/src/lib/ddpClient.ts
- packages/server-core-integration/src/lib/subscriptions.ts
This is a: 
Bug fix
When using core-integration (so gateways or other external applications):
```typescript
const coreConnection = new CoreConnection(coreOptions)
await coreConnection.autoSubscribe('rundownPlaylists', myArguments)
```
If there is an error when subscribing (for example: a `Match.test()` throws, due to invalid arguments), the error is swallowed silently.
The error is now thrown.
> fix(core-integration): handle subscription error

- meteor/client/ui/FloatingInspectors/L3rdFloatingInspector.tsx
- meteor/client/ui/FloatingInspectors/NoraFloatingInspector.tsx
This is a R50 version of https://github.com/nrkno/sofie-core/pull/1119, as there are merge conflicts
When hovering over a nora piece, the preview doesn't show once the renderer loads. It will load for the second piece you hover over.
This gets worse if there are multiple renderers used on the page, as it is the first piece each time the renderer url changes that doesnt display.
> fix: nora hoverscrub not showing content on first load SOFIE-2819 (r50)

- packages/live-status-gateway/src/collections/rundownHandler.ts
This is a: 
Bug fix
In the Live Status Gateway, Adlibs that before the first take are sourced from the Rundown where the Next part is, have their layers reported as invalid until the first Take.
Adlib layers are reported correctly even before the first Take.
Start the LSG and connect to it. Subscribe to the `activePlaylist` topic. Activate a Rundown Playlist. Observe the adlibs returned by the LSG.
> fix(live-status-gw): adLibs having invalid layers before the first take

- meteor/server/api/rest/v1/playlists.ts
- meteor/server/api/userActions.ts
- packages/corelib/src/worker/studio.ts
- packages/job-worker/src/playout/__tests__/playout-executeAction.test.ts
- packages/job-worker/src/playout/adlibAction.ts
This is a: 
Bug fix
Since around https://github.com/nrkno/sofie-core/pull/1077, `privateData` of Adlib Actions appears in the User Action Log when executing an adlib through the HTTP API. This is undesired as its confusing (privateData does not originate from the request) and it adds noise to the logs (in our case it contains entire Parts and Pieces generated ahead of time).
`privateData` of Adlib Actions no longer appears in the User Action Log. It is fetched later, in the worker, just like when executing an adlib through Meteor API.
> fix: remove adlib action's publicData from userLog SOFIE-2939

- meteor/yarn.lock
- packages/job-worker/package.json
- packages/job-worker/src/blueprints/cache.ts
- packages/package.json
- packages/yarn.lock
This exposes a `fetch` global into blueprints, using `node-fetch` as the implementation.
While we are using `got` elsewhere, it feels bad to introduce `got` v11 into new usages, given that the current release of got is v14. It does appear to be getting security patches, but for how long?
By using `fetch`, it should provide a more seamless experience once we update to node18, as the builtin `fetch` implementation will be usable instead. `node-fetch` also looks to be better maintained, even though this is using the previous major version.
This is not necessary for R50, but it makes testing with storybuilder much easier as it allows for developing without needing package-manager to be setup and running.
> feat: add `node-fetch` as a global to blueprint execution SOFIE-1367

- packages/corelib/src/playout/timings.ts
- packages/job-worker/src/__mocks__/collection.ts
- packages/job-worker/src/blueprints/context/watchedPackages.ts
- packages/job-worker/src/db/collection.ts
- packages/job-worker/src/db/collections.ts
- packages/job-worker/src/ingest/generationSegment.ts
- packages/job-worker/src/ingest/model/IngestModel.ts
- packages/job-worker/src/ingest/model/IngestSegmentModel.ts
- packages/job-worker/src/ingest/model/implementation/IngestModelImpl.ts
- packages/job-worker/src/ingest/model/implementation/IngestPartModelImpl.ts
- packages/job-worker/src/ingest/model/implementation/IngestSegmentModelImpl.ts
- packages/job-worker/src/ingest/model/implementation/utils.ts
This is a: Bug fix / Feature
Blueprints can mark ExpectedPackages as ones they are listening to. When PackageInfos are updated which belong to these packages, sofie will re-run the ingest for those segments automatically.
During ingest, after calling `getSegment`, if any packages returned were not known of before the `getSegment` call, then we check if the listening behaviour should be triggered immediately.  
It now performs a quick check to see if there are any `PackageInfos` which would have been returned to the blueprints when they asked, and if so it will re-run `getSegment` with a fresh copy of the `PackageInfos`
This is to catch cases where the blueprints define a dependency on a 'new' expectedPackage A, which already exists in the …
> fix: check if segment should be immediately regenerated during ingest SOFIE-2887

- meteor/client/styles/rundownView.scss
- meteor/client/ui/FloatingInspectors/NoraFloatingInspector.tsx
- packages/blueprints-integration/src/content.ts
This is a:  Feature
The NORA hover preview is currently fixed at being run at a resolution of 1920x1080.
The blueprints are able to specify a different resolution for the hover preview window, so that it can more accurately represent the content as it will be shown on video walls with other aspect ratios
This requires custom blueprints which set the properties
> feat: allow blueprints to specify a custom resolution for NORA hover preview SOFIE-2840

- meteor/client/ui/Settings/ShowStyle/SourceLayer.tsx
- meteor/i18n/nb.po
- meteor/i18n/nn.po
- meteor/i18n/template.pot
- meteor/public/locales/nb/translations.json
- meteor/public/locales/nn/translations.json
This is a: GUI label clarification
GUI label for `sourceLayer.onPresenterScreen` is "Display on Presenter's Screen"
This is confusing for our Admins, since it doesn't really convey what the setting does.
GUI label for `sourceLayer.onPresenterScreen` is "Treat as Main content"
with hint: "When set, Pieces on this Source Layer will be used to display summaries, thumbnails etc for the Part in GUIs."
Our Admins confirms this label is clearer for them.
No testing needed
> fix: rename 'onPresenterScreen' description in GUI

- meteor/client/ui/SegmentTimeline/withMediaObjectStatus.tsx
- meteor/lib/api/rundownNotifications.ts
- meteor/server/publications/packageManager/expectedPackages/generate.ts
- meteor/server/publications/pieceContentStatusUI/bucket/publication.ts
- meteor/server/publications/pieceContentStatusUI/checkPieceContentStatus.ts
- meteor/server/publications/pieceContentStatusUI/rundown/publication.ts
- meteor/server/publications/pieceContentStatusUI/rundown/reactiveContentCache.ts
- meteor/server/publications/pieceContentStatusUI/rundown/regenerateItems.ts
- meteor/server/publications/pieceContentStatusUI/rundown/rundownContentObserver.ts
- packages/corelib/src/dataModel/ExpectedPackages.ts
In various scenarios, pieces would be missing correct content statuses.
These issues were introduced by #942
> fix: clip content statuses regressions SOFIE-2993

- meteor/client/lib/__tests__/rundown.test.ts
- meteor/client/lib/__tests__/rundownTiming.test.ts
- meteor/client/lib/rundown.ts
- meteor/client/lib/rundownTiming.ts
- meteor/client/ui/ClockView/PresenterScreen.tsx
- meteor/client/ui/RundownView/RundownTiming/RundownTimingProvider.tsx
- meteor/client/ui/RundownView/RundownTiming/SegmentDuration.tsx
- meteor/client/ui/SegmentContainer/withResolvedSegment.ts
- meteor/client/ui/SegmentList/SegmentList.tsx
- meteor/client/ui/SegmentList/SegmentListContainer.tsx
- meteor/client/ui/SegmentList/SegmentListHeader.tsx
- meteor/client/ui/SegmentStoryboard/SegmentStoryboard.tsx
- meteor/client/ui/SegmentStoryboard/SegmentStoryboardContainer.tsx
- meteor/client/ui/SegmentTimeline/Parts/FlattenedSourceLayers.tsx
- meteor/client/ui/SegmentTimeline/Parts/OutputGroup.tsx
- meteor/client/ui/SegmentTimeline/Parts/SegmentTimelinePart.tsx
- meteor/client/ui/SegmentTimeline/Parts/SourceLayer.tsx
- meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
- meteor/client/ui/SegmentTimeline/Renderers/MicSourceRenderer.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/client/ui/SegmentTimeline/SmallParts/SegmentTimelinePartHoverPreview.tsx
- meteor/client/ui/SegmentTimeline/SmallParts/SegmentTimelineSmallPartFlag.tsx
- meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
- meteor/client/ui/SegmentTimeline/TimelineGrid.tsx
- meteor/client/ui/Shelf/SegmentTimingPanel.tsx
- packages/corelib/src/playout/timings.ts
This PR is posted on behalf of the NRK.
This is a:
Bug fix
Calculating the Diff requires knowing all Part's expectedDurations, that means that in order to calculate the Diff, one needs to have all the Pieces for a Playlist loaded. The GUI trims down the amount of data it needs in local cache ("minimongo") in order to maximize performance, and as such, will only have some Pieces loaded at any given time. The Presenters' screen for example will only have the Pieces for the current and next Part loaded. This causes the Diff to be different on the Presenters' screen and in the Rundown View. The Diff in the Rundown View changes as the user scrolls around the page.
The expectedDuration calculation does not consider Pieces prerolls. This will introduce minimal (in real-life scenarios) …
> fix(Client): Piece-dependency for expectedDuration calculation causes the Diff to be inconsistent (SOFIE-3004)

- packages/live-status-gateway/src/collections/adLibActionsHandler.ts
- packages/live-status-gateway/src/collections/adLibsHandler.ts
- packages/live-status-gateway/src/collections/globalAdLibActionsHandler.ts
- packages/live-status-gateway/src/collections/globalAdLibsHandler.ts
- packages/live-status-gateway/src/collections/partHandler.ts
- packages/live-status-gateway/src/collections/partInstancesHandler.ts
- packages/live-status-gateway/src/collections/partsHandler.ts
- packages/live-status-gateway/src/collections/pieceInstancesHandler.ts
- packages/live-status-gateway/src/collections/playlistHandler.ts
- packages/live-status-gateway/src/collections/rundownHandler.ts
- packages/live-status-gateway/src/collections/rundownsHandler.ts
- packages/live-status-gateway/src/collections/segmentHandler.ts
- packages/live-status-gateway/src/collections/segmentsHandler.ts
- packages/live-status-gateway/src/collections/showStyleBaseHandler.ts
- packages/live-status-gateway/src/collections/studioHandler.ts
- packages/live-status-gateway/src/coreHandler.ts
- packages/live-status-gateway/src/topics/activePlaylistTopic.ts
- packages/live-status-gateway/src/topics/adLibsTopic.ts
- packages/live-status-gateway/src/topics/root.ts
- packages/live-status-gateway/src/topics/segmentsTopic.ts
- packages/live-status-gateway/src/topics/studioTopic.ts
- packages/live-status-gateway/src/wsHandler.ts
This is a: 
Code improvement / Log level improvement
The Live Status Gateway outputs lots of excessive `info` level logs. When in use, it can output hundreds of thousands log entries a day. Some of them inform about individual document updates, heartbeat (sent out every 2 seconds), information about collection handlers and topics receiving or sending updates, etc.
`info` level is now mostly used for lifecycle events (initialization, connecting/disconnecting, subscribing/unsubscribing). Less relevant messages are demoted to `debug` or in few cases to `silly`.
~~It's a draft, awaiting merge of https://github.com/nrkno/sofie-core/pull/1131 after which I'll rebase this to release51~~
> refactor(live-status-gw): reassign log levels

- meteor/server/api/deviceTriggers/RundownsObserver.ts
- meteor/server/publications/lib/__tests__/rundownsObserver.test.ts
- meteor/server/publications/lib/rundownsObserver.ts
- meteor/server/publications/pieceContentStatusUI/rundownContentObserver.ts
We have identified that there is a memory leak in Sofie that gets worse each day.
Through some local testing, I identified a scenario where this happens and verified it with some debug logging.
To reproduce:
1. Add two or more rundowns into a playlist
2. In the ui, manually remove one of those rundowns from the playlist.
At this point, the debug logging will show that the observers have been re-created to just consider the rundowns which remain in the playlist 
4. In the ui, manually delete the rundown which is no longer in the playlist
The debug logging will show that the publication was invalidated from deleting of this rundown.
The issue was that whenever we re-created this RundownsObserver, we would not call the …
> fix: stop old observers when re-creating nested observers SOFIE-3016

- packages/job-worker/src/__mocks__/collection.ts
- packages/job-worker/src/ingest/commit.ts
- packages/job-worker/src/playout/model/PlayoutRundownModel.ts
- packages/job-worker/src/playout/model/implementation/PlayoutRundownModelImpl.ts
- packages/job-worker/src/playout/model/implementation/PlayoutSegmentModelImpl.ts
- packages/job-worker/src/playout/model/implementation/__tests__/PlayoutRundownModelImpl.spec.ts
- packages/job-worker/src/playout/model/implementation/__tests__/PlayoutSegmentModelImpl.spec.ts
- packages/job-worker/src/playout/model/implementation/__tests__/SavePlayoutModel.spec.ts
This is a: Code improvement
New unit tests
> chore: add tests for portions of PlayoutModelImpl SOFIE-2670

- meteor/client/ui/Prompter/PrompterView.tsx
We have reported issues in prod where the prompter "jump" in case of content changes (ie doesn't scroll to the new position correctly).
We also see quite a few `Read anchor could not be found after update` errors in our logs.
I haven't been able to properly reproduce the issue, but I believe it is related to the `getScrollAnchor` method returning an anchor which doesn't exist after the update.
I've rewritten the `getScrollAnchor` algorithm to no return a list of anchors instead of a single one, order in falling "order of importance".
When the content changes, if `restoreScrollAnchor` fails to find the first anchor, it can now continue and try the next ones after that.
* Use the Prompter, scroll to various positions.
* …
> feat: New Prompter scroll algorithm (SOFIE-3082)

- packages/job-worker/src/__mocks__/context.ts
- packages/job-worker/src/__mocks__/defaultCollectionObjects.ts
- packages/job-worker/src/playout/__tests__/actions.test.ts
- packages/job-worker/src/playout/activePlaylistActions.ts
This is a:
Bug fix
When activating a Rundown from rehearsal, the Scratchpad Segment is not removed.
When activating a Rundown from rehearsal, the Scratchpad Segment is removed and the current-playing PartInstance is reset.
See above.
* This PR affects the Rundown activation playout logic
> fix: clear Scratchpad on Rundown activation (SOFIE-2575)

- meteor/client/ui/RundownList/DragAndDropTypes.ts
- meteor/client/ui/RundownList/RundownDropZone.tsx
- meteor/client/ui/RundownList/RundownListItem.tsx
- meteor/client/ui/RundownList/RundownPlaylistUi.tsx
In the rundown list page, when dragging a rundown which is not grouped in a playlist, a dropbox is shown to create it in a new playlist.
This has no visible effect, as the rundown is moved into a non-grouped playlist, giving the same result as before.
When dragging a rundown which is alone in a flattened playlist, don't show the drop box
This is a minor ui change
> fix: hide create playlist drop box when dragging a rundown not in a multi-rundown playlist SOFIE-2462

- meteor/server/api/deviceTriggers/RundownContentObserver.ts
- meteor/server/api/deviceTriggers/StudioObserver.ts
When using a streamdeck through the input gateway, when resetting the rundown any rundown based actions on the streamdeck will go blank and will no longer work.
They would return upon deactivating and reactivating the rundown, or restarting sofie.
This was due to a value being used non-reactively, causing incorrect invalidations when resetting the rundown.
This PR affects the input gateway
> fix: input gateway devices lose rundown actions on reset SOFIE-3134

- meteor/lib/MeteorApply.ts
- meteor/lib/lib.ts
- meteor/lib/logging.ts
- packages/job-worker/src/workers/parent-base.ts
…1190)
This is a: Code improvement 
It is in [Meteor's nature ](https://guide.meteor.com/methods#methods-vs-rest) to only send a single method call at a time, so if a previous method call takes a long time to finish executing (or the response was delayed due to network issues), the next method call will be delayed.
When this happens, we currently don't have a way to detect that this has happened, and have no way of knowing which method was delayed, and why.
This PR attempts to help troubleshooting this by adding logging for when a client method is sent late, due to being blocked by other method calls from that client.
This PR affects how the web client sends data to the server.
Fairly high priority, we'll likely look into merging this …
> Fix: MeteorApply as alternative to Meteor.apply, to log delayed sent method calls (SOFIE-3236)

- packages/corelib/src/__tests__/error.spec.ts
- packages/shared-lib/src/lib/stringifyError.ts
If there is an error in a method run in a job worker, the error logged looks like this:
```
Ingest operation "mosInsertStory" failed: [object Object] , undefined
=> awaited here:
at Function.Promise.await (/opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at server/api/ingest/lib.ts:40:12
at /opt/core/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
``` 
```
Ingest operation "mosInsertStory" failed: Error: Test error!, Error: Test error!
at \sofie-core-R50\packages\job-worker\dist\ingest\mosDevice\mosStoryJobs.js:100:19
at \sofie-core-R50\packages\job-worker\dist\ingest\lock.js:37:38
at processTicksAndRejections …
```
> fix: make stringifyError handle UserError better (SOFIE-3337)

- packages/corelib/src/playout/processAndPrune.ts
- packages/job-worker/src/playout/__tests__/timeline.test.ts
- packages/job-worker/src/playout/timeline/piece.ts
- packages/job-worker/src/playout/timings/timelineTriggerTime.ts
This is a:Bug fix
When adlibbing a clip (or another piece with preroll) into the current part, a subsequent update to the timeline will cause the start of the adlibbed piece to drift earlier, by the preroll amount
* This PR affects playout.
This happens because while the start of the piece is 'now', the preroll gets added here https://github.com/nrkno/sofie-core/blob/b700f568b20c698df82e387e2671179c0b939539/packages/corelib/src/playout/pieces.ts#L106-L127
But then once it is a concrete number (set to the start of that object), the preroll isnt added, causing it to shift.
> fix: compensate for piece preroll for adlibbed pieces SOFIE-3369

- packages/mos-gateway/src/CoreMosDeviceHandler.ts
- packages/mos-gateway/src/coreHandler.ts
- packages/playout-gateway/src/coreHandler.ts
- packages/playout-gateway/src/tsrHandler.ts
Feature
When changing the blueprint configuration through the API peripheralDevice subdevices can be added and removed. Currently the removal leaves the subdevice in place with a status of 'BAD' and with the message 'Uninitialized'.
This change forces the subdevice to be removed in this specific case.
The change is intended as a step towards allowing a Sofie instance to be completely reconfigured via API between productions.
* This PR affects mos-gateway and playout-gateway subdevices.
> feat: Ensure peripheralDevice subdevice removal when requested

- packages/corelib/src/playout/__tests__/infinites.test.ts
- packages/corelib/src/playout/processAndPrune.ts
A sequence of events could cause the wrong piece to briefly play following a take.
It needs a segment of 2 parts, the first without a super, the second with a super (which is outOnSegmentEnd).
1) play the first part
1) adlib an outOnSegmentChange super
1) take into the second part
1) cue an adlib part
1) take the adlib part and observe the wrong super showing briefly
the outOnSegmentChange super was not getting stopped correctly, resulting in it being present later than it should, causing its higher priority to win and replace the correct super
> fix: adlibbed super fighting with planned super timings SOFIE-3378

- meteor/client/lib/parsers/mos/__tests__/mosSample1.json
- meteor/client/lib/parsers/mos/__tests__/mosSample2.json
- meteor/client/lib/parsers/mos/mosXml2Js.ts
- meteor/package.json
- meteor/server/api/ingest/mosDevice/actions.ts
- meteor/yarn.lock
- packages/job-worker/src/ingest/mosDevice/__tests__/__snapshots__/mosIngest.test.ts.snap
- packages/job-worker/src/ingest/mosDevice/__tests__/mock-mos-data.ts
- packages/mos-gateway/package.json
- packages/mos-gateway/src/CoreMosDeviceHandler.ts
- packages/shared-lib/package.json
- packages/yarn.lock
This is a:
Code improvement
See https://github.com/nrkno/sofie-mos-connection/pull/103
All incoming MOS data will now be strings, no automatic number conversions
See https://github.com/nrkno/sofie-mos-connection/pull/103
> fix: update mos-connection dependency (SOFIE-3006)

- meteor/client/ui/Prompter/PrompterView.tsx
- meteor/client/ui/Prompter/prompter.ts
This is a:
Bug fix
When the prompter is positioned in a “next-to-be-next” Part, making it become next will make the Prompter jump to the “was-next-just-before/now-is-on-air” Part. The position of the prompter needs to be just right for this to happen, such as when using “go to next/previous part”. Other positions can work too, but the window of tolerance for this is pretty small.
Prompter should maintain its position when the Part in the viewport is repositioned in ENPS, when Parts are repositioned around the Part in the viewport, it should also maintain it’s position when setting the position “just right” (such as explained in Observed behavior section) and doing Takes in Sofie.
This PR affects the prompter
This Bug Fix is critical for …
> fix: resolve an issue with prompter jumping when Parts become PartInstances

- .github/workflows/node.yaml
- .github/workflows/prerelease-libs.yml
This is a: CI bug fix
There was [an issue in the CI](https://github.com/nrkno/sofie-core/actions/runs/11014653966/job/30588750698) Release step where the openAPI client generated by `hatamiarash7/openapi-generator@v0.3.0` caused the subsequent `yarn build:main` to fail.
The CI step was added in https://github.com/nrkno/sofie-core/pull/1182 but since it failed I temporarily disabled the step in release51.
I did a bit of investigation and came to the conclusion that the `hatamiarash7/openapi-generator` isn't really needed, instead just running `yarn build` seems to generate the artifacts needed (test [npm publish](https://www.npmjs.com/package/@sofie-automation/openapi/v/1.51.0-nightly-chore-openapi-ci-fix-20240925-072200-7c918ac.0?activeTab= …
> re-enable build step for openapi for test and publishing

- packages/corelib/src/dataModel/RundownPlaylist.ts
- packages/job-worker/src/blueprints/context/OnTimelineGenerateContext.ts
- packages/job-worker/src/playout/abPlayback/__tests__/abPlayback.spec.ts
- packages/job-worker/src/playout/abPlayback/__tests__/abPlaybackResolver.spec.ts
- packages/job-worker/src/playout/abPlayback/__tests__/abSessionHelper.spec.ts
- packages/job-worker/src/playout/abPlayback/__tests__/applyAssignments.spec.ts
- packages/job-worker/src/playout/abPlayback/abPlaybackResolver.ts
- packages/job-worker/src/playout/abPlayback/abPlaybackSessions.ts
- packages/job-worker/src/playout/abPlayback/abSessionHelper.ts
- packages/job-worker/src/playout/abPlayback/applyAssignments.ts
- packages/job-worker/src/playout/abPlayback/index.ts
- packages/job-worker/src/playout/resolvedPieces.ts
- packages/job-worker/src/playout/timeline/part.ts
- packages/job-worker/src/playout/timeline/piece.ts
- packages/job-worker/src/playout/timeline/rundown.ts
- packages/shared-lib/src/core/model/Timeline.ts
This is a: Bug fix / Feature
This is a couple of intertwined changes. It might be possible to pull the feature out into its own PR if wanted, but its a pretty isolated opt-in functionality and overlaps in area with the fixes.
Each change is a separate commit in this PR.
There is a limitation in the AB logic, where an infinite piece is not allowed to share a session with any other piece. This limitation was added originally because a `sessionName` was described as needing to be unique within a segment, once out of that segment, it is hard to be sure that the name won't be reused unless care is taken to ensure it is globally unique.  
This PR allows sessions to opt into being treated as a globally unique id. This allows for skipping a lot of …
> AB session issues

- packages/job-worker/src/playout/timeline/piece.ts
- packages/job-worker/src/playout/timeline/rundown.ts
This pull request is posted on behalf of **BBC**.
This is a Bug fix.
When a part has autoNext set to true as well as a piece with Post Roll the take will be done too early (exactly by the amount of postroll), in addition the infinites may stop at odd times
Auto next take is done at the correct time (after the expectedDuration has passed), and the infinites do not interrupt.
This PR affects the timeline generation.
This Bug Fix is a blocker for us, please review and merge it as soon as possible.
> Bug fix: currentPart timeline duration should respect postroll in autonext

- .github/workflows/prune-container-images.yml
- .github/workflows/prune-tags.yml
- .github/workflows/trivy.yml
This is a workflow usability improvement
Some of the Github Actions workflows are nrk specific, or make assumptions and do not make sense to run for others.
These workflows are either disabled for anyone other than nrkno
I have not tested this, but the changes match a guard on an existing workflow https://github.com/nrkno/sofie-core/blob/master/.github/workflows/sonar.yaml#L15
Github actions workflows
Ideally as soon as possible, this adds noise for our team due to the workflows failing. 
Our master branch is currently mirroring yours, so we can't easily fix directly on our side
> chore: disable nrk specific workflows

- packages/job-worker/src/playout/adlibUtils.ts
When using `stopPiecesOnLayers` inside an adlib-action, it does not any pieces which have a fixed duration. This is because `plannedStoppedPlayback` is now set when constructing the timeline, so is known even before the piece starts playing.
It now checks whether that `plannedStoppedPlayback` is in the past, instead of just whether it is set.
> fix: clear pieces with fixed duration

- meteor/client/lib/__tests__/rundownTiming.test.ts
- meteor/client/lib/rundownTiming.ts
- packages/corelib/src/playout/timings.ts
This is a: **Bug Fix**
- The current playing segment timer will have its duration reduced by the amount of postroll the previous on-air part has
- If the current part has an autonext, the next segment will have its duration and time-till-on-air padded with the duration of the current part. The duration will be counting down
- Postroll is accounted for in the timing calculations (Postroll is not valid in any display timing since it plays after the part has ended)
- If a timestamp for lastStartedPlayback is in the future it will be ignored by the display calculations since that means the part hasn't actually started yet
Rundown timing in the UI
> Fix: UI Timing: Postroll and autonext timing

- packages/job-worker/src/playout/timeline/rundown.ts
When a `outOnRundownChange` infinite is playing in the current part, and you take into a new part the infinite continues.
But if the new part has a piece on the same layer with a non-zero start time, the infinite continuation piece will not play.
This is because the end time of the infinite piece doesn't correctly get translated from time within the part, to the mangled timings that infinites use, as it needs to start earlier than the current part.
This PR affects the timeline generation.
This likely affects R51 too, so could probably be backported there, but we found and fixed it on R52
> fix: on change infinites incorrect collision ends

- packages/job-worker/src/blueprints/context/adlibActions.ts
- packages/job-worker/src/playout/adlibAction.ts
- packages/job-worker/src/playout/debug.ts
- packages/job-worker/src/playout/lib.ts
- packages/job-worker/src/playout/model/PlayoutModel.ts
- packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
- packages/job-worker/src/studio/model/StudioBaselineHelper.ts
- packages/job-worker/src/studio/model/StudioPlayoutModel.ts
- packages/job-worker/src/studio/model/StudioPlayoutModelImpl.ts
- packages/job-worker/src/studio/routeSet.ts
Follow up to #1272
When toggling a routeset which affects ab-players, this should also regenerate the timeline so that the timeline is using the correct set of ab-players.
This will now check whether a routeset may affect the timeline, and will regenerate it if so.
This means it should have no additional cost for routesets which do not control an abplayer.
> fix: regenerate timeline after routeset

- packages/job-worker/src/ingest/syncChangesToPartInstance.ts
This fixes a bug where `syncIngestChangesToPartInstances` would only call `validateAdlibTestingPartInstanceProperties` for a partInstance if the blueprint method produced any notes.
I haven't tested this, as we are not currently using either one of these features, this is something I noticed while implementing another change.
This looks to have been introduced as a bad rebase during https://github.com/nrkno/sofie-core/commit/f2281bda6e61808e4417edeb1a7cba834e752cbd#diff-8af2b9f79873bd3db961e678a8e722803844318f4fdb1f7e63a972f71e818c53
This PR affects the syncIngestChanges flow, when also using adlib-testing rundowns.
> fix: always call `validateAdlibTestingPartInstanceProperties` during `syncIngestChangesToPartInstances`

- packages/job-worker/src/playout/model/PlayoutPartInstanceModel.ts
- packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
- packages/job-worker/src/playout/model/implementation/PlayoutPartInstanceModelImpl.ts
This is a:
Bug fix
It's impossible to send metadata using the `onRundownTimingEvent` callback for the very last PartInstance of the Rundown, since the callback is not called on deactivating the Rundown.
`onRundownTimingEvent` is called on deactivating a Rundown with a currentPartInstance.
This PR affects Rundown deactivation and metadata flow.
We intend to finish the development on this feature in two weeks time.
> fix(job-worker): queue a PartInstanceTimingEvent on deactivation (SOFIE-3470)

- packages/job-worker/src/playout/model/PlayoutModel.ts
- packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
- packages/job-worker/src/playout/model/services/QuickLoopService.ts
- packages/job-worker/src/playout/quickLoopMarkers.ts
- packages/webui/src/client/lib/rundownTiming.ts
This pull request is posted on behalf of the **BBC**.
This is a: Bug Fix
- Inconsistent countdown timers in the UI when a loop is active
- When changing the loop while it was on-air, already played segments could be included
- Consistent countdown timers in the UI when a loop is active
- Segments that are added to the loop after it has started playing will be reset upon inclusion
This PR affects Countdown Timers when the loop is active and this PR affects the setting QuickLoop markers.
> fix: QuickLoop timers are inconsistent

- packages/job-worker/src/ingest/syncChangesToPartInstance.ts
where the partInstance to be updated where in another rundown than the rundown in the provided context / playoutRundownModel
This is a:
Bug fix
To reproduce the issue:
* Have a playlist with multiple rundowns in it, from an NRCS
* Activate and Taks
* Update the Rundown in the NRCS or trigger "Reload NRCS Data"
There is a "Segment xyz not found" error, that originates from the `getPieceInstancesForPart()` function.
I figured out that the issue was that `getPieceInstancesForPart()` was called with a `Part` from rundown B but the `playoutModel` was from Rundown A.
I added a special case for when the `playoutRundownModel` is for another Rundown than the Part, we use the correct one instead from the PlayoutModel.
This PR affects ingest …
> Fix: Bug "Segment xyz not found" (SOFIE-3544)

- packages/corelib/src/dataModel/Segment.ts
- packages/job-worker/src/ingest/commit.ts
- packages/job-worker/src/ingest/model/IngestSegmentModel.ts
- packages/job-worker/src/ingest/model/implementation/DocumentChangeTracker.ts
- packages/job-worker/src/ingest/model/implementation/SaveIngestModel.ts
- packages/job-worker/src/playout/infinites.ts
- packages/job-worker/src/playout/model/implementation/LoadPlayoutModel.ts
- packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
- packages/job-worker/src/playout/timeline/generate.ts
This is a:
Bug fix
We have experienced various issues in production related to error messages of the `Segment "xyz" not found` type.
While we haven't confidently identified the core issue we have found a few potential problems introduced in release51.
* If the NRCS removes a Part that is currently the `previous` Part in Sofie, the `syncChangesToPartInstances` failed because the Segment of the previous PartInstance was not found.
The fix: Include previous PartInstance in the orphan-Segment-check, so that the Segment will now be orphaned instead of removed.
* If the NRCS removes the first Part in a Segment, this changes the id of the Segment (this is normal). There was a potential situation in the `updatePartInstancesSegmentIds` method where …
> Fix: segment not found issues (SOFIE-3626)

- packages/job-worker/src/playout/__tests__/selectNextPart.test.ts
- packages/job-worker/src/playout/selectNextPart.ts
To replicate:
- Have a final segment with multiple parts
- Take the first part in the final segment
- Queue a previous segment (Queue, not set as next)
- Take remaining parts
- Sofie gets stuck on final part with an error stating that there are no more parts (despite previous segment showing the little queue green triangle)
I suspect this will affect earlier releases too, but I am not setup to test in earlier versions
> fix: `queuedSegmentId` ignored when taking last part of the rundown

- packages/job-worker/src/playout/timeline/rundown.ts
This looks to have been introduced by #1276
To reproduce:
1) Take an infinite (Out on Rundown Change)
1) Clear the layer via an AdLib Action stopPiecesOnLayers or stopPieceInstances
1) Take the infinite again
1) Clear the layer via an AdLib Action stopPiecesOnLayers or stopPieceInstances
1) Observe error in UI and logs
`Error: Error in generated timeline: Validation failed: Error: "enable.end" and "enable.duration" cannot be combined`
> fix: Unable to clear infinites

- meteor/server/publications/partInstancesUI/publication.ts
- meteor/server/publications/partsUI/publication.ts
- packages/meteor-lib/src/api/pubsub.ts
- packages/webui/src/client/ui/ClockView/CameraScreen/index.tsx
- packages/webui/src/client/ui/ClockView/PresenterScreen.tsx
- packages/webui/src/client/ui/Prompter/PrompterView.tsx
- packages/webui/src/client/ui/RundownView.tsx
- packages/webui/src/client/ui/Settings/components/triggeredActions/TriggeredActionEntry.tsx
- packages/webui/src/client/ui/Settings/components/triggeredActions/TriggeredActionsEditor.tsx
When using the 'Action Triggers' settings page, it would not correctly show previews related to the current segment.
This was due to the ui subscribing to the 'parts' collection, but then using the 'uiparts' collection.
Q) should this be using parts or ui parts? I want to say parts as this is a settings page, but its trying to match playout behaviour so maybe should be using uiparts? it only needs the document ids, so it probably doesn't matter.
Additionally, when performing a take, this would not be reflected correctly in this ui, the tracker hook was missing a dependency.
I also found that the uiPartInstances publication had a rundownIds parameter that was unused by the publication implementation. This would cause the …
> fix: action trigger settings ui previews

- packages/documentation/docs/user-guide/further-reading.md
Updated the broken link to the Sofie Slack channel.
Part of the Sofie team at SuperFly.tv
This is a:
Broken Slack invite link.
Working Slack invite link.
Documentation
ASAP
> Fixed broken Slack invite link

- meteor/client/lib/ReactMeteorData/ReactMeteorData.tsx
- meteor/client/ui/RundownView.tsx
This is a:
Bug fix
The RundownView will show a spinner when removing a Rundown from a Playlist, e.g. via MOS active
The RundownView should now be stable, however the ShowStyleVariants publication ready state may not be accurate.
* This PR affect the RundownView
> fix: RundownView shows spinner when unMOSing a Rundown from a Playlist (SOFIE-3539)

- meteor/server/api/deviceTriggers/RundownContentObserver.ts
- meteor/server/api/deviceTriggers/StudioDeviceTriggerManager.ts
- meteor/server/api/deviceTriggers/observer.ts
- meteor/server/publications/lib/ReactiveCacheCollection.ts
This is a:
Bug fix
Given a specific set of conditions and user actions, Sofie Core log starts showing `Undefined Device Trigger context for studio`, and Device Trigger actions stop working until a reactivation/rundown reload. Also, some AdLib previews would "go away" during Rundown Activation/Reactivation, leaving these buttons "blank" in Input Gateway.
Device Trigger Actions publications were rebuilt using the Collections promise API, solving the described problem. The root of the problem was that Fibers were getting in the way and making code that was assumed to work in sequence work in parallel. By employing Promises, much of the code has been parallelized, resulting in - what feels like - a very consistent experience at the Input …
> fix(Core/Publications/Device Triggers): Device Action Studio Context gets lost, Adlib previews are unstable (SOFIE-3638)

- meteor/client/ui/Settings/SnapshotsView.tsx
- meteor/server/api/snapshot.ts
This is a:
Code improvement / DevX improvement
It is only possible to upload snapshots directly, which means that whats uploaded is equivalent to the original Rundown.
Now one can choose to "Ingest from Snapshot", where Sofie will only read the ingestData from the snapshot and pipe it through the current blueprints to recreate the Rundown(s) within.
This is useful for blueprint development or troubleshooting.
This PR affects snapshot restoring.
Not urgent, but we would like to get this merged into the in-development release
> Add option to upload and ingest ingestData from snapshot (SOFIE-3553)

- packages/webui/src/client/styles/_itemTypeColors.scss
- packages/webui/src/client/styles/_variables.scss
- packages/webui/src/client/styles/notifications.scss
- packages/webui/src/client/styles/rundownView.scss
- packages/webui/src/client/styles/shelf/adLibPanel.scss
- packages/webui/src/client/styles/shelf/dashboard.scss
- packages/webui/src/client/styles/supportAndSwitchboardPanel.scss
- packages/webui/src/client/ui/SegmentList/LinePartPieceIndicator/PieceIndicatorMenu.scss
- packages/webui/src/client/ui/SegmentList/SegmentList.scss
- packages/webui/src/client/ui/SegmentStoryboard/SegmentStoryboard.scss
- packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnail.scss
- packages/webui/src/client/ui/Status/media-status/MediaStatusList.scss
This is a:
Code improvement
When starting up in development mode, there are a lot of warnings in the console:
```
DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
[VITE] rules will be changing to match the behavior specified by CSS in an upcoming
[VITE] version. To keep the existing behavior, move the declaration above the nested
[VITE] rule. To opt into the new behavior, wrap the declaration in `& {}`.
[VITE]
[VITE] More info: https://sass-lang.com/d/mixed-decls
[...]
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
[VITE]
[VITE] Recommendation: math.div($segment-header-width, 2) or calc($segment-header-width / 2)
[VITE]
[VITE] More info and …
```
> Fix scss deprecation warnings

- packages/webui/src/client/ui/RundownView/RundownTiming/RundownTimingProvider.tsx
- packages/webui/src/client/ui/RundownView/RundownTiming/withTiming.tsx
- packages/webui/src/client/ui/SegmentTimeline/SegmentTimeline.tsx
- packages/webui/src/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- packages/webui/src/client/ui/SegmentTimeline/TimelineGrid.tsx
This is a: Code improvement
This tackles a small bit of tech debt, removing the use of a deprecated react feature. This deprecation results in multiple long error messages in the browser console when in development mode.
I think I have understood the reactivity that it was subject to before and matched that, it would be good for the reviewer to verify that.
Refs:
https://react.dev/reference/react/Component#static-contexttypes
https://legacy.reactjs.org/docs/legacy-context.html
I have done a little testing, nothing looks obviously wrong to me but I am not 100% sure what the side effects of this could be.
This affects the rundown and other playout UI pages.
> chore: replace react contextTypes with modern alternatives

- meteor/server/lib.ts
- packages/webui/vite.config.mts
In development, the sofie logo is not showing in the ui
This was broken by #1332, which renamed the default logo file to resolve an issue where the logo selection in the settings was not being respected (I think broken by #1230, when changing how static files are served)
> fix: sofie logo not showing in dev

- packages/job-worker/src/playout/model/PlayoutModel.ts
- packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
- packages/job-worker/src/playout/take.ts
- packages/job-worker/src/playout/timings/partPlayback.ts
This is a:
Bug fix
Hold mode didn't work at all because it would go straight from pending to Completed without modifying the Hold-TO PartInstance. Also, timeline wasn't updated when Hold was being Completed.
The `PENDING` -> `ACTIVE` -> `COMPLETED` cycle is wholly handled inside the `take` job in job-worker. The misleading code that would switch the Hold state inside `cycleSelectedPartInstances` has been removed and a new method, `resetHoldState` has been added to handle the situation of an auto-take happening while Hold is enabled. Inner functions for Hold have been renamed to reflect what they were doing.
* This PR affects the Hold logic.
* This Bug Fix is critical for us, please review and merge it as soon as possible.
> fix: Hold mode doesn't work at all (SOFIE-3661)

- packages/live-status-gateway/src/index.ts
- packages/playout-gateway/src/index.ts
This is a:
Bug fix
Sometimes, Playout Gateway outputs an object as the "message" member of the JSONL-formated logging output to std streams.
Message is ensured not to be an object.
* This PR affects logging
* We intend to finish the development on this feature in two weeks time.
> fix: Make sure that Playout Gateway never puts an object into the message field of the JSONL log output (SOFIE-3679)

- meteor/server/api/rest/v1/playlists.ts
- meteor/server/lib/rest/v1/playlists.ts
- packages/openapi/api/definitions/playlists.yaml
the openAPI currently does not include the ignoreQuickLoop option in move-next-part
ignoreQuickLoop has been added as an optional attribute in move-next-part
This affects only the openAPI
The addition has not been tested locally, as this requires java engine to be installed.
> Feat: OpenAPI move-next-part add ignoreQuickLoop as optional attribute

- packages/job-worker/src/ingest/commit.ts
- packages/job-worker/src/ingest/updateNext.ts
This is a:
Bug fix
#1358 introduced a bugfix for an issue where the current MOS Story for the Next PartInstance is deleted which caused the ingest & playout side to "lock up", unable to create the Playout Model. That fix, while working, is problematic because:
1. It's not merge-able into `release52`
2. It breaks the overall flow of data through the models, by causing a playout-related decision to be made at ingest time.
The fix is reworked into a new algorithm that:
1. Prevents the deletion of the Segment containing the nextPart instance
2. Allows the flow to be unchanged up until `ensureNextPartIsValid`
3. Allows `ensureNextPartIsValid` to discover that the next PartInstance is `orphaned: deleted` and select something else (much like the …
> fix: a better fix for the deleted PartInstance problem

- packages/blueprints-integration/src/content.ts
- packages/webui/src/client/styles/rundownView.scss
- packages/webui/src/client/ui/FloatingInspectors/VTFloatingInspector.tsx
Currently there's only Script support in script layers
This PR adds support in VT's for scripts and FirstWords-LastWords in hover via Blueprints.
The feature should not change current behaviour unless it's added in Blueprints.
This PR affects the UI only
This PR had been tested and approved by bbc
> Feat: Ability to add scripts and FirstWords/LastWords on VT's

- meteor/server/__tests__/cronjobs.test.ts
- meteor/server/cronjobs.ts
This is a:
Bug fix
CasparCG servers will be restarted during "Low Season" (between 4:00 and 5:00) if the CasparCG restart cronjob is enabled
CasparCG cronjob will check if there's an active rundown in the Studio that owns the CasparCG to be restarted. If there is, the restart will be skipped until next day.
> fix(Cronjob): don't restart CasparCG using the nightly cronjob if there's a Rundown active in the Studio (SOFIE-3618)

- packages/blueprints-integration/src/documents/piece.ts
- packages/corelib/src/playout/__tests__/timings.test.ts
- packages/corelib/src/playout/timings.ts
- packages/job-worker/src/blueprints/context/lib.ts
- packages/job-worker/src/playout/timeline/__tests__/__snapshots__/rundown.test.ts.snap
- packages/job-worker/src/playout/timeline/__tests__/rundown.test.ts
- packages/job-worker/src/playout/timeline/generate.ts
- packages/job-worker/src/playout/timeline/part.ts
- packages/job-worker/src/playout/timeline/pieceGroup.ts
- packages/job-worker/src/playout/timeline/rundown.ts
- packages/webui/src/client/lib/__tests__/rundownTiming.test.ts
All pieces from a part are included in the keepalive region of a part during a transition. This can lead to unintended effects, such as graphics starting their out animation too late.
Each piece can opt out of being included in this keepalive region.
This adds some framework and initial tests for the timeline generation, focusing specifically on how the part and piece groups are arranged.
This PR affects the timeline generation. 
When reviewing, I would recommend reviewing the first commit of pure refactoring before the rest of the changes
> feat: exclude pieces from part keepalive

- meteor/server/api/rest/v1/typeConversion.ts
- meteor/server/lib/rest/v1/showstyles.ts
- meteor/server/publications/pieceContentStatusUI/checkPieceContentStatus.ts
- packages/blueprints-integration/src/content.ts
- packages/shared-lib/src/core/model/ShowStyle.ts
- packages/webui/src/client/styles/_itemTypeColors.scss
- packages/webui/src/client/styles/rundownView.scss
- packages/webui/src/client/styles/shelf/adLibPanel.scss
- packages/webui/src/client/styles/shelf/dashboard.scss
- packages/webui/src/client/ui/ClockView/CameraScreen/index.tsx
- packages/webui/src/client/ui/PieceIcons/PieceCountdown.tsx
- packages/webui/src/client/ui/PieceIcons/PieceIcon.tsx
- packages/webui/src/client/ui/PieceIcons/Renderers/RemoteSpeakInputIcon.tsx
- packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardSecondaryPiece.tsx
- packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartThumbnail/Renderers/ThumbnailRendererFactory.tsx
- packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnail.scss
- packages/webui/src/client/ui/Settings/ShowStyle/SourceLayer.tsx
This pull request is posted on behalf of the **BBC**.
This contribution is an addition to the existing source layers.
- Added an additional source layer type for **Lighting**, no additional features added for this but it is useful to have for organisation
- Added a new source layer type called **Remote Speak**: this is similar to a live speak but the VT Content is replaced with a Remote source.
- Adjusted the styling of the Live Speak pieces to have slightly different proportions and made it easier to distinguish to colours
This PR mostly affects how pieces are displayed in the UI.
Not urgent, but we would be nice to have in release 52 :)
> feat: add new SourceLayer Types

- packages/job-worker/src/playout/timeline/multi-gateway.ts
This is a:
Bug fix
Some timeline objects are not denowified, because they don't match the expected geometry of the `deNowifyCurrentPieces` function. Because of this, starting Infinite Pieces via AdLibs is unreliable in terms of device state changes taking effect.
The issue can be discovered via a log message starting with:
> Some timeline objects have unexpected now times!
`deNowifyCurrentPieces` collects timeline objects that can't be denowified by it and a second pass is done in `deNowifyInfinites` after `updatePlannedTimingsForPieceInstances` runs that will do a recursive search through the timelineObjs to calculate the appropriate `enable.start` value.
* This PR affects the playout logic in general.
* This Bug Fix is critical for us, …
> fix(Playout): infinite AdLib Items' timeline objects are not denowified (SOFIE-3665)

- meteor/server/migration/1_52_0.ts
This is a:
Bug fix
Studio `settings` are migrated as defaults instead of overrides, unlike the other properties (like `routeSets`).
Studio settings are migrated as overrides, since they are manually entered.
> fix: Studio migrations (SOFIE-3798)

- meteor/server/publications/buckets.ts
This is a:
Bug fix
Bucket AdLib Pieces' and Bucket AdLib Actions' `privateData` is exposed to the frontend via publications.
There are no defined constraints regarding what can be placed in `privateData` of Bucket AdLib Pieces and Bucket AdLib Actions, however if any (sub)property within it starts with a `$`, minimongo will throw on the frontend, and some parts of the UI will refuse to render (likely just the contents of the bucket). It's a common practice [citation needed] to store entire Pieces generated ahead of time, including their timeline objects (which oftentimes contain a `$references` property), in `privateData` of AdLib Actions, therefore this bug is likely to occur for anyone who does that in their blueprints. Besides that, …
> fix(Core): omit privateData in bucket adlib pieces and actions publications

- packages/blueprints-integration/src/context/onSetAsNextContext.ts
- packages/blueprints-integration/src/context/partsAndPieceActionContext.ts
- packages/job-worker/src/blueprints/__tests__/context-OnSetAsNextContext.test.ts
- packages/job-worker/src/blueprints/__tests__/context-OnTakeContext.test.ts
- packages/job-worker/src/blueprints/__tests__/context-adlibActions.test.ts
- packages/job-worker/src/blueprints/context/OnSetAsNextContext.ts
- packages/job-worker/src/blueprints/context/OnTakeContext.ts
- packages/job-worker/src/blueprints/context/adlibActions.ts
- packages/job-worker/src/blueprints/context/services/PartAndPieceInstanceActionService.ts
This pull request is posted on behalf of the BBC.
This is a: Enhancement
- Blueprints can set public and private data on segments but have no way to read this information back
- Blueprints can use the getSegment method on the `Action`/ `OnSetAsNext `/ `OnTake` contexts
This PR affects the blueprint contexts
> feat(Blueprint API): Expose Segments in blueprint contexts

- packages/playout-gateway/src/coreHandler.ts
This is a:
Bug fix (just affecting logs)
When an error occurs in executeAction, the following would be logged: `{"message":"executeFunction error: function toString() { [native code] }","level":"error"}`, which is not very helpful
The error will be properly stringified as in other places in the code
Just logs of the Playout Gateway in case `executeAction` throws
> fix: stringify error in executeAction

- packages/job-worker/src/blueprints/context/services/PartAndPieceInstanceActionService.ts
- packages/job-worker/src/blueprints/context/services/__tests__/PartAndPieceInstanceActionService.test.ts
- packages/job-worker/src/ingest/__tests__/ingest.test.ts
- packages/job-worker/src/playout/adlibUtils.ts
This is a:
Bug fix
Pieces that should start at the beginning of the Part following the dynamically inserted one, will start in the dynamically inserted Part instead. See: https://github.com/nrkno/sofie-core/issues/1392
The problem is in the rank of the inserted part, initially set to a placeholder 99999, which tricks the logic finding infinites to continue into believing that the inserted part is the very last part of the segment.
In order to fix the bug, the operations are reordered: first the new rank of the part is calculated, then the infinites to continue are gathered.
This PR affects the Sofie Core playout logic around adlibbing, specifically queueing adlib parts.
We consider the bug to be severe, because it leads to unexpected …
> fix: prevent queued Part from hijacking infinite Pieces from the following Part(s)

- packages/webui/src/client/ui/TestTools/Timeline.tsx
Currently there's no way to see abSessions in test tools
if there's an abSessions object in the TimelineObject, AB-Sessions will be displayed in the timeline after the content.
As the abSessions are not part of the `ResolvedTimelineObjectInstance<Content>` but still in the object, a ts-expect-error has been added.
Only the testtools timeline
> feat(Test Tools): show AB-Session in Timeline

- scripts/install-and-build.mjs
This is a: Code improvement 
If I have yarn 1 / yarn classic installed on my system, I get some errors such as `'run' not a executable command` and the like, which are hard to troubleshoot for a new developer.
When running install-and-build, the script will catch the issue early and provide a user friendlier feedback.
> chore: add check to install-and-build script to disallow yarn 1

- packages/blueprints-integration/src/context/syncIngestChangesContext.ts
- packages/job-worker/src/blueprints/context/SyncIngestUpdateToPartInstanceContext.ts
- packages/job-worker/src/ingest/__tests__/syncChangesToPartInstance.test.ts
- packages/job-worker/src/ingest/syncChangesToPartInstance.ts
> [!NOTE]  
> This is a rebase of the PR for release53 of https://github.com/nrkno/sofie-core/pull/1408
This is a regression believed to be introduced by https://github.com/nrkno/sofie-core/pull/1035
The `removePartInstance` method on `SyncIngestUpdateToPartInstanceContext` is broken, it did not reset the PartInstance correctly.
This PR reimplements this for the new model approach.
As part of this, some refactoring was done first, to make it easier to unit test portions of this logic. Not many tests have been added as part of this, but tests have been added for `removePartInstance`.
I have not looked into backporting this fix to earlier releases, but I suspect it would be pretty straightforward to rebase it without the …
> fix: reimplement `removePartInstance` flow for `syncChangesToPartInstances`

- packages/meteor-lib/src/uiTypes/Adlib.ts
- packages/webui/src/client/ui/Shelf/AdLibListView.tsx
- packages/webui/src/client/ui/Shelf/AdLibPanel.tsx
This is a: Bug fix / feature
Global Adlibs on hidden sourcelayers will now be shown in the shelf. 
Prior to this they were able to get hotkeys assigned, but they wouldn't be listed.
Blueprints can instead set the `hidden` property on the adlibs to hide them (still getting hotkeys)
> fix: don't hide global adlibs from hidden sourceLayers

- packages/corelib/src/dataModel/RundownPlaylist.ts
- packages/job-worker/src/playout/abPlayback/__tests__/abPlayback.spec.ts
- packages/job-worker/src/playout/abPlayback/__tests__/abPlaybackResolver.spec.ts
- packages/job-worker/src/playout/abPlayback/__tests__/applyAssignments.spec.ts
- packages/job-worker/src/playout/abPlayback/abPlaybackResolver.ts
- packages/job-worker/src/playout/abPlayback/abPlaybackSessions.ts
- packages/job-worker/src/playout/abPlayback/applyAssignments.ts
- packages/job-worker/src/playout/abPlayback/index.ts
This is a:  Feature
The AB notifications that were added in https://github.com/nrkno/sofie-core/pull/1303 have been reworded to be more descriptive. Instead of a notification saying `Failed to assign players for {{count}} sessions`, a notification will be raised per failed session, which lists the pieces that requested the failed session `Failed to assign AB player for {{pieceNames}}`
Additionally the console logging for the ab logic has been improved to always include the `sessionName` as defined by blueprints. This is to make it easier to debug ab sessions for blueprint developers.
> feat: improve ab notifications and logging

- packages/documentation/docs/for-developers/contribution-guidelines.md
This is a personal contribution.
This is a:
Bug fix
The Contribution Guidelines are unclear on what the RFC should contain, who their target audience is, and when one should open one.
A couple of paragraphs have been added to explain:
* Why the RFC's exist
* Who is the target audience for the RFC
* What is useful in an RFC
* Where the discussion happens: either workshops or RFC comments, as needed
This PR affects the Contribution Guidelines
Not urgent, but I would like to get this merged into the master release, since it's project meta-documentation.
> chore(docs): Clarify the RFC process more

- packages/webui/src/client/styles/studioScreenSaver.scss
- packages/webui/src/client/ui/ClockView/ClockView.tsx
- packages/webui/src/client/ui/Prompter/PrompterView.tsx
- packages/webui/src/client/ui/StudioScreenSaver/StudioScreenSaver.tsx
This feature has been made on behalf of BBC
Feature
Currently you can't see if a screen is the prompter, presenter or director screen when the screen saver is active.
A screenName option has been added to the screensaver
UI
> Feature: Show screen-name in screen-saver

- packages/mos-gateway/src/mosHandler.ts
this fix is made on behalf of BBC
Bug fix
Currently hot standby was not registered correctly, and thus not active if enabled.
Hotstandby is now testing for the full device name.
This is only affecting mos-gateway in hotStandby mode.
This is a priority bug fix from bbc.
> Fix: Hot standby was not referring to the devices full name

- meteor/server/api/deviceTriggers/RundownsObserver.ts
- meteor/server/publications/lib/PromiseDebounce.ts
- meteor/server/publications/lib/rundownsObserver.ts
- packages/job-worker/src/playout/snapshot.ts
This contains a couple of fixes:
Some publications which use PromiseDebounce (specifically using the `trigger()` method), are not reporting errors due to the behaviour of PromiseDebounce. This adds some simple try/catch logging.
When restoring some snapshots, I was having issues with the ids in the ingest cache collections not lining up. This adjusts how the ids are generated to make those link up correctly.
> fix: some snapshots not restoring correctly due to id generation order & publications lost errors

- packages/job-worker/src/playout/timeline/multi-gateway.ts
This PR is opened on behalf of TV 2 Norge
This is a:
Bug fix 
In multi-gateway mode, when dynamically inserting a Piece with a `start: 'now'` into the current Part, duration of the piece is not respected. The piece correctly starts immediately, and is shown in the UI as having a defined duration, but on the playout side it lasts till the end of the Part.
Piece ends according to its duration.
This PR affects playout, specifically adlib pieces (or actions that insert pieces that start 'now')
Technical details: piece control groups had their `duration` lost in `deNowifyCurrentPieces`.
This fix is tricky in terms of adding regression tests or asserting that that it does not introduce any other regressions because this area does not seem covered by existing unit tests, therefore I didn't …
> fix: duration of pieces with 'now' start time

- meteor/server/api/peripheralDevice.ts
- packages/corelib/src/dataModel/PeripheralDevice.ts
- packages/webui/src/client/ui/Settings/DeviceSettings.tsx
- packages/webui/src/client/ui/Settings/Studio/Devices/GenericSubDevices.tsx
- packages/webui/src/client/ui/Settings/Studio/Devices/ParentDevices.tsx
- packages/webui/src/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx
- packages/webui/src/client/ui/Settings/components/GenericDeviceSettingsComponent.tsx
I haven't tested if this bug is present in R52, based on the findings it may want backporting
Navigating to the peripheraldevice page for a subdevice would crash, trying to read a property off undefined:
```
Cannot read properties of undefined (reading 'subdeviceManifest')
TypeError: Cannot read properties of undefined (reading 'subdeviceManifest')
at GenericAttahcedSubDeviceSettingsComponent
```
This is because since R50, the `configManifest` property should not be set on subdevices. This is enforced by the migration `PeripheralDevice cleanup unused properties on child devices`.
But the types say the propery must exist, resulting in typescript not flagging the type error.
The types have been updated to reflect this, and …
> fix: `PeripheralDevice.configManifest` is an optional field

- packages/webui/src/client/ui/Prompter/PrompterView.tsx
This PR updates the code from the previous PR (https://github.com/nrkno/sofie-core/pull/1436) to be forwards-compatible with Bootstrap, introduced with release53. In release52 this will have no effect.
> fix(EAV-555): make prompter animations compatible with bootstrap

- packages/live-status-gateway/src/topics/root.ts
This pull request is posted on behalf of the BBC.
This is a:
Bug fix
Live status gateway subscriptions fail as the gateway doesn't actually setup any topics on startup.
Live status gateway subscriptions work
Live Status Gateway
> fix: Live Status Gateway subscription name check

- packages/webui/jest.config.cjs
- packages/webui/src/client/lib/__tests__/lib.test.ts
- packages/webui/src/client/lib/lib.tsx
This is a Bug fix
Clocks on screensaver pages etc. start counting when they are loaded and update approximately every second after that. This means they are an average of 0.5 seconds behind and can be .999 seconds behind in the worst case.
Here's an example of 4 clocks running together, with the system clock visible at the top right:
https://github.com/user-attachments/assets/1731b0ea-a412-4893-9107-207b9ba27b36
Clocks will update at the next whole interval, e.g. if they are loaded at 12:00:00.523, they will try to update 477ms later at 12:00:01.000 exactly.
Here's an example of 4 clocks running together, with the system clock visible at the top right:
https://github.com/user-attachments/assets/e85fb2ff-8f79-42e4-8343-f272a6d29a26
They are now in sync to within a few frames. My machine …
> fix: Improve clock accuracy

- meteor/server/api/ingest/mosDevice/mosIntegration.ts
- packages/job-worker/src/blueprints/cache.ts
- packages/job-worker/src/playout/timeline/multi-gateway.ts
This pull request is posted on behalf of NRK.
In release51, `node-fetch` was exposed to blueprints. That was removed as builtin `fetch` was expected to be available, but it is blocked by the sandbox and has to be explicitly provided.
A line of logging in the mos handling is incorrect
Adds some logging to the timeline generation to make sure that any objects that failed to be de-nowified are logged as an error.
> fix: missing fetch for blueprints, and minor logging changes

- meteor/Dockerfile
- meteor/Dockerfile.circle
- packages/.yarnrc.yml
- packages/documentation/docs/user-guide/installation/installing-sofie-server-core.md
- packages/live-status-gateway/Dockerfile
- packages/live-status-gateway/Dockerfile.circle
- packages/mos-gateway/Dockerfile
- packages/mos-gateway/Dockerfile.circle
- packages/playout-gateway/Dockerfile
- packages/playout-gateway/Dockerfile.circle
This pull request is posted on behalf of Superfly
When launching the docker images with extra arguments, the syntax is clunky. Because of the way the images are built, you have to do a `docker run playout-gateway node dist/index.js -host core -port 3000`. In other words, it requires the user of the image to know how to launch the application inside of the docker image. 
This is hard enough, that [until recently](https://github.com/Sofie-Automation/sofie-core/pull/1444) the Sofie documentation was wrong and would say to do `docker run playout-gateway yarn start -host core -port 3000` which would actually fail with a corepack error. 
This command changed a while back, I suspect when we updated to yarn 3.
So this is not friendly to those deploying sofie.
The documentation …
> fix!: docker images using CMD instead of ENTRYPOINT

- packages/webui/src/client/styles/main.scss
This is made on behalf of BBC
After conversion to Bootstrap labels on all links are underlined
The reason for this is that the React Link component uses the "a"-tag, and that has a default underline decorator.
A global text-decorator: none has been added for "a"-tags, as the default style.
Have been checking links in Rundown view and in System status
Links in the UI.
> Fix: Underscore on all links after conversion to Bootstrap

- packages/playout-gateway/src/tsrHandler.ts
This PR has been opened by SuperFly.tv on behalf of EVS Broadcast Equipment (henceforth EVS).
This is a:
Bug fix
Under some circumstances, particularly seen during device initialisation, a connectionChanged message leads to dereference of an undefined variable leading to an unhandled promise rejection.
The potentially undefined variable is tested before dereferencing.
* This PR affects status updates from TSR devices.
We would like to get this merged into the in-development release.
> fix: Race condition in device change handling

- packages/webui/src/client/ui/PreviewPopUp/PreviewPopUp.scss
- packages/webui/src/client/ui/PreviewPopUp/PreviewPopUpContent.tsx
- packages/webui/src/client/ui/PreviewPopUp/PreviewPopUpContext.tsx
This is a bug fix.
After implementation of the new hover previews, styling on the In-Out words in VT preview was missing.
Styling on the VT hover previews
UI hover previews.
> fix: In-Out words was placed and styled wrong

- packages/webui/src/client/ui/PreviewPopUp/PreviewPopUp.tsx
- packages/webui/src/client/ui/PreviewPopUp/Previews/IFramePreview.tsx
- packages/webui/src/client/ui/PreviewPopUp/Previews/VTPreview.tsx
This PR is made on the behalf of BBC
After introduction of the new hover previews, bbc has experiences UI Crashes
Some of hover components was constantly re-rendering and re-triggering itself.
Ensuring the useEffects only triggers when needed, fixed the issue.
UI
This is an urgent fix for bbc
Manual testing in multiple rundowns has been performed with positive outcome.
> fix: Memory leaks in Hover Previews

- packages/webui/src/client/ui/Settings/Studio/PackageManager/AccessorTableRow.tsx
This is a:
Bug fix
Package Manager failed with error message: 
`TypeError: this.accessor.ISAUrls.join is not a function`
Sofie GUI now saves ISAUrls as arrays of strings, as was intended
This PR affects Package Manager
…cessors.${accessorId}.ISAUrls to an array of strings
> Fix: input type of PM Quantel Accessor ISAURLs (SOFIE-4126)
